### PR TITLE
Geometry_Engine: Weldsize added to profiles

### LINKED ISSUE #1251: Geometry_Engine: ShapeProfile FabricatedBoxProfile weldSize parameter doesn't work.
#### Description:
The FabricatedBoxProfile doesn't show a weldSize > 0. 

#### How to replicate:
Give weldSize a bigger input number than 0.

#### Expected behaviour:
image

#### Test file(s):

https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=CJWjNz&cid=0b727f4a%2Daf39%2D4d1d%2D8942%2D0c26c33d7c20&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssue1251%2DFabricatedBoxProfile%20weldSize%20doesn%27t%20work

### PR DESCRIPTION
**Pull request by JonathanNillius**
### NOTE: Depends on 
#1277 
   
### Issues addressed by this PR
Ready for review!
The old PR clashes with other changes. This new PR should not.

Closes #1251  

### Test files
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=CJWjNz&cid=0b727f4a%2Daf39%2D4d1d%2D8942%2D0c26c33d7c20&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DPullRequest1277%20weldSize

Test by changing weldSize to larger than 0 and look if a weld is shown in the profile.

### CODE REVIEW

File: Geometry_Engine/Create/ShapeProfileCurves.cs [hunk 1]
```diff
@@ -176,19 +180,32 @@ public static List<ICurve> BoxProfileCurves(double width, double height, double
...
             List<ICurve> box = RectangleProfileCurves(width, height, 0);
-            List<ICurve> innerBox = RectangleProfileCurves(width - 2 * webThickness, height - (topFlangeThickness + botFlangeThickness), 0);
-            double diff = botFlangeThickness- topFlangeThickness;
 
-            if (diff != 0)
-            {
-                Vector v = new Vector() { X = 0, Y = diff / 2, Z = 0 };
-                innerBox = innerBox.Select(x => Geometry.Modify.ITranslate(x, v)).ToList();
-            }
+            List<ICurve> welds = new List<ICurve>();
```
Comment (IsakNaslundBh) [inline Geometry_Engine/Create/ShapeProfileCurves.cs]: Will need a check here somewhere if the weldsize is 0 or not. If it is zero, currently 0-length lines are added to the edges. 
image

basically, if weld-size == 0, make sure it does the same thing as before, if not, what you have here seem fine!

File: Geometry_Engine/Create/ShapeProfileCurves.cs [hunk 2]
```diff
@@ -34,32 +34,36 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
-        public static List<ICurve> IProfileCurves(double tft, double tfw, double bft, double bfw, double wt, double wd, double r1, double r2)
+        public static List<ICurve> IProfileCurves(double tft, double tfw, double bft, double bfw, double wt, double wd, double r1, double r2, double weldSize)
```
Comment (IsakNaslundBh) [inline Geometry_Engine/Create/ShapeProfileCurves.cs]: A bit scary to allow both root radius and weld size, but as this mostly is an internal method being called indirectly it could be fine. Could be good if you could have a quick look at adding warning or splitting up in two different methods though I think.
