### PR TITLE
Security_Engine: Camera Field of View - cone shape calculation fix

### LINKED ISSUE #3100: Security_Engine: Camera Field of View - cone shape calculation
#### Description:

The shape of camera field of view is incorrect. For horizontal field view equals 1000, the distance between cone corner points is wrong (~970):
image

### PR DESCRIPTION
**Pull request by michal-pekacki**
### Issues addressed by this PR

Closes #3100 

Corrected calculation of camera field of view cone shape. This change is to precise the value of horizontal field of view:

Before (HoV = 1000):
image

After (HoV = 1000):
image

### CODE REVIEW

**Comment by michal-pekacki** [comment]
@BHoMBot check required

**Comment by michal-pekacki** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

File: Security_Engine/Query/ViewCone.cs [hunk 1]
```diff
@@ -48,7 +48,7 @@ public static PolyCurve ViewCone(this CameraDevice cameraDevice)
             Point targetLocation = cameraDevice.TargetPosition;
             double radius = targetLocation.Distance(cameraLocation);
```
Comment (vietle-bh) [inline Security_Engine/Query/ViewCone.cs:49]:
```suggestion
            double fieldOfViewRadius = targetLocation.Distance(cameraLocation);
```

File: Security_Engine/Query/ViewCone.cs [hunk 2]
```diff
@@ -48,7 +48,7 @@ public static PolyCurve ViewCone(this CameraDevice cameraDevice)
...
             double horizontal = cameraDevice.HorizontalFieldOfView;
```
Comment (vietle-bh) [inline Security_Engine/Query/ViewCone.cs:50]:
```suggestion
            double fieldOfViewArcLength = cameraDevice.HorizontalFieldOfView;
```

File: Security_Engine/Query/ViewCone.cs [hunk 3]
```diff
@@ -48,7 +48,7 @@ public static PolyCurve ViewCone(this CameraDevice cameraDevice)
...
-            double angle = Math.Atan(horizontal / radius);
+            double angle = Math.Asin(horizontal / (2 * radius)) * 2;
```
Comment (vietle-bh) [inline Security_Engine/Query/ViewCone.cs:51]:
```suggestion
            double fieldOfViewAngle = Math.Asin(horizontal / (2 * radius)) * 2;
```

File: Security_Engine/Query/ViewCone.cs [hunk 4]
```diff
@@ -48,7 +48,7 @@ public static PolyCurve ViewCone(this CameraDevice cameraDevice)
...
 
             Vector direction = BH.Engine.Geometry.Create.Vector(cameraLocation, cameraDevice.TargetPosition);
```
Comment (vietle-bh) [inline Security_Engine/Query/ViewCone.cs:53]:
```suggestion
            Vector viewDirection = BH.Engine.Geometry.Create.Vector(cameraLocation, cameraDevice.TargetPosition);
```

**Review by vietle-bh — COMMENTED** [review]
I had to ask you what these meant, so let's save future readers the trouble :bowtie:

File: Security_Engine/Query/ViewCone.cs (hunk 1 above)
Comment (michal-pekacki) [reply Security_Engine/Query/ViewCone.cs:49]: To be more precise, I used `coneRadius`

File: Security_Engine/Query/ViewCone.cs (hunk 2 above)
Comment (michal-pekacki) [reply Security_Engine/Query/ViewCone.cs:50]: To be more precise, I used `coneArcLength`

File: Security_Engine/Query/ViewCone.cs (hunk 3 above)
Comment (michal-pekacki) [reply Security_Engine/Query/ViewCone.cs:51]: To be more precise, I used `coneAngle`

**Comment by michal-pekacki** [comment]
@BHoMBot check required

**Comment by michal-pekacki** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check unit-tests

**Review by vietle-bh — APPROVED** [review]
It now works as expected 👍 

camera test 1

camera test 2

**Comment by michal-pekacki** [comment]
@FraserGreenroyd unit-tests fails somewhere outside of the PR - it would be nice if you can check it

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 14786230946

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge
