### PR TITLE
BHoM_Engine: Added BHoMWebsiteURL.cs

### LINKED ISSUE #3081: BHoM Website URL
#### What is missing/incorrect?

Need a method that returns the up-to-date URL for the BHoM website.

### PR DESCRIPTION
**Pull request by desaiwangBH**
Added method to generate up-to-date BHoM website URL

### Issues addressed by this PR

Closes #3081 

- Method call that returns up-to-date BHoM website URL

### CODE REVIEW

File: BHoM_Engine/Query/BHoMWebsiteURL.cs [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+
+        [Description("Generates the BHoM Website URL.")]
+        [Output("url", "Fully qualified URL for BHoM website.")]
+        public static string BHoMWebsiteURL()
+        {
+
```
Comment (FraserGreenroyd) [inline BHoM_Engine/Query/BHoMWebsiteURL.cs:39]:
```suggestion
```

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
Approved based on code review.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 14138464303

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge
