### PR TITLE
Structure_Engine: Add Create, Compute and Modify method descriptions

### LINKED ISSUE #1028: Structure_Engine: Add Bar.SetGeometry(Polyline) method for 2-node polylines

### LINKED ISSUE #1180: Structure_Engine: Create methods documentation
#### Describe the documentation issue:
- [ ] Various methods are not documented

#### What is missing/incorrect?
Code attributes are missing from methods in the Create folder of the Structure_Engine.

### LINKED ISSUE #1181: Structure_Engine: Modify methods documentation
#### Describe the documentation issue:
- [ ] Various methods are not documented

#### What is missing/incorrect?
Code attributes are missing from methods in the Modify folder of the Structure_Engine.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #1180 
Closes #1181 
Closes #1028 

Adding quantities, descriptions, inputs and outputs to Create methods in the Structure_Engine.

### Changelog

- Fixing making sure SetGeometry for bar work for any linear curve, not just Line.

### Additional comments

@peterjamesnugent you are up again 😉

### CODE REVIEW

File: Structure_Engine/Create/Elements/Panel.cs [hunk 1]
```diff
@@ -39,55 +40,39 @@ public static partial class Create
...
-        {
-            return Panel(new List<ICurve>(outlines), property, name);
-        }
-
-        /***************************************************/
-
+        [Description("Creates a list of Panels based on a collection of outline curves. \n" + 
+                     "Method will distribute the outlines such that the outermost curve will be assumed to be an external outline of a panel, and any curve contained in this outline will be assumed as an opening of this Panel. \n" +
+                     "Any outline curve inside an opening will again be assumed to be the outline of a new Panel.")]
+        [Input("outline", "A collection of outline Curves representing outlines of external edges and opening used to create the Panel(s).")]
```
Comment (FraserGreenroyd) [inline Structure_Engine/Create/Elements/Panel.cs]: Should this be `outlines`?

Comment (IsakNaslundBh) [reply Structure_Engine/Create/Elements/Panel.cs]: yep, thanks!

File: Structure_Engine/Create/Constraints/BarRelease.cs [hunk 2]
```diff
@@ -30,23 +33,21 @@ public static partial class Create
...
         /***************************************************/
 
-        public static BarRelease BarRelease(Constraint6DOF startConstraint, Constraint6DOF endConstraint, string name = "")
-        {
-            return new BarRelease { StartRelease = startConstraint, EndRelease = endConstraint, Name = name };
-        }
-
-        /***************************************************/
-
+        [Description("Creates a Bar release that is fully fixed in both ends, i.e. all degrees of freedom, translational and rotational will be fixed.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Constraints/BarRelease.cs]: BarRelease that is fully fixed at both ends

File: Structure_Engine/Create/Constraints/BarRelease.cs [hunk 3]
```diff
@@ -30,23 +33,21 @@ public static partial class Create
...
+        [Input("name", "Name of the BarRelease. Defaults to FixFix.")]
+        [Output("release", "The created fully fixed BarRelease.")]
         public static BarRelease BarReleaseFixFix( string name = "FixFix")
         {
             return new BarRelease { StartRelease = FixConstraint6DOF(), EndRelease = FixConstraint6DOF(), Name = name };
         }
 
         /***************************************************/
 
+        [Description("Creates a Bar release that is pinned in both ends, i.e. all translational degrees of freedom will be fixed, and rotational released, with one exception. The RX release on the start will be fixed to avoid instability of the Bar, to prevent it from spinning around its own axis.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Constraints/BarRelease.cs]: BarRelease that is pinned at both ends
rotating about it's on local x-axis

File: Structure_Engine/Create/Constraints/BarRelease.cs [hunk 4]
```diff
@@ -60,16 +61,34 @@ public static BarRelease BarReleasePinPin(string name = "PinPin")
 
         /***************************************************/
 
+        [Description("Creates a Bar release that is pinned in one end and axially releaased in the other. \n" +
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Constraints/BarRelease.cs]: at one end

File: Structure_Engine/Create/Constraints/BarRelease.cs [hunk 5]
```diff
@@ -60,16 +61,34 @@ public static BarRelease BarReleasePinPin(string name = "PinPin")
...
+                     "This means that the start node will have all tranlational degrees fixed as well as the RX, to avoid instability, i.e. to prevent the Bar from spinning around its own axis. \n" +
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Constraints/BarRelease.cs]: rotating about it's local x-axis

File: Structure_Engine/Create/Constraints/BarRelease.cs [hunk 6]
```diff
@@ -60,16 +61,34 @@ public static BarRelease BarReleasePinPin(string name = "PinPin")
...
+                     "The end node will have the translational y and z directions fixed, all other free, i.e. it will be free to rotate as well as tranlate along the axis of the Bar.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Constraints/BarRelease.cs]: The end node will be fixed in the y-axis and z-axis translationally, all degrees of freedom will be free, i.e. it will be free to rotate as well as translate about the local x-axis of the Bar.

File: Structure_Engine/Create/Constraints/LinkConstraint.cs [hunk 7]
```diff
@@ -32,6 +36,11 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+
+        [Description("Creates a LinkConstraint from a list of booleans. True denotes fixity.")]
+        [Input("name", "Name of the created LinkConstraint. Important for this to be set for multiple structural packages to be able to recognise this object.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Constraints/LinkConstraint.cs]: This is required for various structural packages to create the object.

File: Structure_Engine/Create/Elements/IElement0D/NewElement0D.cs [hunk 8]
```diff
@@ -33,6 +37,11 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Creates a new Element0D, appropriate to the input type. For this case the appropriate type for the Bar will be a new Node, in the position provided. \n" +
+                     "Method required for any IElement1D element that contains IElement0D(s).")]
+        [Input("bar", "Bar just used to determain the appropriate type of IElement0D to create.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Elements/IElement0D/NewElement0D.cs]: Bar is used to determine the appropriate type of IELement0D to create.

File: Structure_Engine/Create/Elements/IElement1D/NewElement1D.cs [hunk 9]
```diff
@@ -34,13 +39,23 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Creates a new Element1D, appropriate to the input type. For this case the appropriate type for the Opening will be a new Edge, in the position provided. \n" +
+                     "Method required for any IElement2D.")]
+        [Input("opening", "Opening just used to determain the appropriate type of IElement1D to create.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Elements/IElement1D/NewElement1D.cs]: is used to determine

File: Structure_Engine/Create/Elements/IElement1D/NewElement1D.cs [hunk 10]
```diff
@@ -34,13 +39,23 @@ public static partial class Create
...
         public static IElement1D NewElement1D(this Opening opening, ICurve curve)
         {
             return new Edge { Curve = curve.IClone() };
         }
 
         /***************************************************/
 
+        [Description("Creates a new Element1D, appropriate to the input type. For this case the appropriate type for the Panel will be a new Edge, in the position provided. \n" +
+                     "Method required for any IElement2D.")]
+        [Input("panel", "Panel just used to determain the appropriate type of IElement1D to create.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Elements/IElement1D/NewElement1D.cs]: is used to determine

File: Structure_Engine/Create/Elements/IElement2D/NewInternalElement2D.cs [hunk 11]
```diff
@@ -32,6 +37,10 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Creates a new Element2D, appropriate to the input type. For this case the appropriate type for the Panel will be a new Opening, in the position provided. \n" +
+                     "Method required for any IElement2D that contians internal IElement2Ds.")]
+        [Input("panel", "Panel just used to determain the appropriate type of IElement2D to create.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Elements/IElement2D/NewInternalElement2D.cs]: is used to determine

File: Structure_Engine/Create/Elements/Node.cs [hunk 12]
```diff
@@ -34,6 +38,11 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Created a Node from a Cartesian soordinate system. The position of the Node will be the Orgin, and the Orientation of the node will match the axes of the Coordinate system.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Elements/Node.cs]: coordinate system

File: Structure_Engine/Create/Elements/Node.cs [hunk 13]
```diff
@@ -34,6 +38,11 @@ public static partial class Create
...
+        [Input("coordinates", "The Cartesian coordinate system to control the position and orientation of the Node.")]
+        [Input("name", "The name of the created Node.")]
+        [InputFromProperty("support")]
+        [Output("node", "The created Structural Node")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Elements/Node.cs]: structural

File: Structure_Engine/Create/Elements/Panel.cs [hunk 14]
```diff
@@ -39,55 +40,39 @@ public static partial class Create
...
-        {
-            return Panel(new List<ICurve>(outlines), property, name);
-        }
-
-        /***************************************************/
-
+        [Description("Creates a list of Panels based on a collection of outline curves. \n" + 
+                     "Method will distribute the outlines such that the outermost curve will be assumed to be an external outline of a panel, and any curve contained in this outline will be assumed as an opening of this Panel. \n" +
+                     "Any outline curve inside an opening will again be assumed to be the outline of a new Panel.")]
+        [Input("outlines", "A collection of outline Curves representing outlines of external edges and opening used to create the Panel(s).")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Elements/Panel.cs]: curve

File: Structure_Engine/Create/Loads/AreaTemperatureLoad.cs [hunk 15]
```diff
@@ -38,12 +38,20 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
-        public static AreaTemperatureLoad AreaTemperatureLoad(Loadcase loadcase, double t, IEnumerable<IAreaElement> objects, LoadAxis axis = LoadAxis.Global, bool projected = false, string name = "")
+        [Description("Creates an uniform temprature load to be applied to Area elements such as Panels and FEMeshes.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/AreaTemperatureLoad.cs]: temperature 
area

File: Structure_Engine/Create/Loads/AreaUniformlyDistributedLoad.cs [hunk 16]
```diff
@@ -38,6 +38,14 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Creates an uniformly distributed load to be applied to Area elements such as Panels and FEMeshes.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/AreaUniformlyDistributedLoad.cs]: area

File: Structure_Engine/Create/Loads/AreaUniformlyDistributedLoad.cs [hunk 17]
```diff
@@ -38,6 +38,14 @@ public static partial class Create
...
+        [InputFromProperty("loadcase")]
+        [InputFromProperty("pressure")]
+        [Input("objects", "The collection of elements the load should be applied to.")]
+        [InputFromProperty("axis")]
+        [InputFromProperty("projected")]
+        [Input("name", "The name of the created load.")]
+        [Output("AreaUDL", "The created AreaUniformlyDistributedLoad.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/AreaUniformlyDistributedLoad.cs]: Area outputs generally capitalised?

File: Structure_Engine/Create/Loads/BarPrestressLoad.cs [hunk 18]
```diff
@@ -38,6 +38,12 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Creates an pre-stress load to be applied to Bars.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/BarPrestressLoad.cs]: a
prestress

File: Structure_Engine/Create/Loads/BarTemperatureLoad.cs [hunk 19]
```diff
@@ -37,7 +37,16 @@ public static partial class Create
         /***************************************************/
         /**** Public Methods                            ****/
         /***************************************************/
-       
+
+
+        [Description("Creates an uniform temprature load to be applied to Bars.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/BarTemperatureLoad.cs]: a

File: Structure_Engine/Create/Loads/BarVaryingDistributedLoad.cs [hunk 20]
```diff
@@ -38,17 +38,31 @@ public static partial class Create
...
+        [InputFromProperty("momentB")]
+        [InputFromProperty("axis")]
+        [InputFromProperty("projected")]
+        [Input("name", "The name of the created load.")]
+        [Output("barVarLoad", "The created BarVaryingDistributedLoad.")]
+        public static BarVaryingDistributedLoad BarVaryingDistributedLoad(Loadcase loadcase, BHoMGroup<Bar> group, double distanceFromA = 0, Vector forceA = null, Vector momentA = null, double distanceFromB = 0, Vector forceB = null, Vector momentB = null, LoadAxis axis = LoadAxis.Global, bool projected = false, string name = "")
         {
             if ((forceA == null || forceB == null) && (momentA == null || momentB == null))
-                throw new ArgumentException("Bar varying load requires either the force at A and B OR the moment at A and B to be defined");
+                throw new ArgumentException("Bar varying load requires either the force at A and B AND/OR the moment at A and B to be defined");
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/BarVaryingDistributedLoad.cs]: and/or

File: Structure_Engine/Create/Loads/GravityLoad.cs [hunk 21]
```diff
@@ -38,6 +38,12 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Creates a gravity load to be applied to Area elements such as Panels and FEMeshes as well as Bar elements.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/GravityLoad.cs]: area

File: Structure_Engine/Create/Loads/LoadCombination.cs [hunk 22]
```diff
@@ -33,13 +37,13 @@ public static partial class Create
...
         /***************************************************/
 
-        public static LoadCombination LoadCombination(string name, int number, IEnumerable<Tuple<double, ICase>> factoredCases)
-        {
-            return new LoadCombination { LoadCases = factoredCases.ToList(), Name = name, Number = number };
-        }
-
-        /***************************************************/
-
+        [Description("Creates a LoadCombination from two matching lists of load cases and factors.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/LoadCombination.cs]: Creates a  load combination from two equal length lists of load cases and factors.

File: Structure_Engine/Create/Loads/LoadCombination.cs [hunk 23]
```diff
@@ -33,13 +37,13 @@ public static partial class Create
...
+        [Input("name", "The name of the load combination. Important for this to be set for multiple structural packages to be able to recognise this object.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/LoadCombination.cs]: This is required for various structural packages to create the object.

File: Structure_Engine/Create/Loads/LoadCombination.cs [hunk 24]
```diff
@@ -33,13 +37,13 @@ public static partial class Create
...
+        [InputFromProperty("number")]
+        [Input("cases", "The cases to be assigned to the LoadCombination. This list should have the exact same length as the factors.")]
+        [Input("factors", "The factor to scale each of the cases with.  This list should have the exact same length as the cases.")]
+        [Input("excludeZeroFactorCases", "If set to true, any case that has a coresponding factor of 0 will NOT be added to the case.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/LoadCombination.cs]: corresponding

File: Structure_Engine/Create/Loads/PointAcceleration.cs [hunk 25]
```diff
@@ -38,6 +38,14 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Creates a point acceleration to be applied to Node elements.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/PointAcceleration.cs]: Nodes (remove elements)

File: Structure_Engine/Create/Loads/PointAcceleration.cs [hunk 26]
```diff
@@ -56,6 +64,14 @@ public static PointAcceleration PointAcceleration(Loadcase loadcase, BHoMGroup<N
 
         /***************************************************/
 
+        [Description("Creates a point acceleration to be applied to Node elements.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/PointAcceleration.cs]: Nodes (remove elements)

File: Structure_Engine/Create/Loads/PointDisplacement.cs [hunk 27]
```diff
@@ -38,6 +38,14 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Creates a point displacement to be applied to Node elements.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/PointDisplacement.cs]: Nodes (remove elements)

File: Structure_Engine/Create/Loads/PointDisplacement.cs [hunk 28]
```diff
@@ -57,6 +65,14 @@ public static PointDisplacement PointDisplacement(Loadcase loadcase, BHoMGroup<N
 
         /***************************************************/
 
+        [Description("Creates a point displacement to be applied to Node elements.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/PointDisplacement.cs]: Nodes (remove elements)

File: Structure_Engine/Create/Loads/PointLoad.cs [hunk 29]
```diff
@@ -38,6 +38,14 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Creates a point load to be applied to Node elements.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/PointLoad.cs]: Nodes (remove elements)

File: Structure_Engine/Create/Loads/PointLoad.cs [hunk 30]
```diff
@@ -57,6 +65,14 @@ public static PointLoad PointLoad(Loadcase loadcase, BHoMGroup<Node> group, Vect
 
         /***************************************************/
 
+        [Description("Creates a point load to be applied to Node elements.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/PointLoad.cs]: Nodes (remove elements)

File: Structure_Engine/Create/Loads/PointVelocity.cs [hunk 31]
```diff
@@ -38,6 +38,14 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Creates a point velocity to be applied to Node elements.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/PointVelocity.cs]: Nodes (remove elements)

File: Structure_Engine/Create/Loads/PointVelocity.cs [hunk 32]
```diff
@@ -57,6 +65,14 @@ public static PointVelocity PointVelocity(Loadcase loadcase, BHoMGroup<Node> gro
 
         /***************************************************/
 
+        [Description("Creates a point velocity to be applied to Node elements.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/PointVelocity.cs]: Nodes (remove elements)

File: Structure_Engine/Create/Loads/PointVelocity.cs [hunk 33]
```diff
@@ -38,6 +38,14 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Creates a point velocity to be applied to Node elements.")]
+        [InputFromProperty("loadcase")]
+        [InputFromProperty("group", "Objects")]
+        [InputFromProperty("translation", "TranslationalAcceleration")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/PointVelocity.cs]: TranslationalVelocity

File: Structure_Engine/Create/Loads/PointVelocity.cs [hunk 34]
```diff
@@ -38,6 +38,14 @@ public static partial class Create
...
+        [InputFromProperty("rotation", "RotationalAcceleration")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Loads/PointVelocity.cs]: RotationalVelocity

File: Structure_Engine/Create/Offsets/Offset.cs [hunk 35]
```diff
@@ -30,6 +34,14 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Creates a Offset defining offsets for Bar objects from its end Nodes to be applied in analysis packages.")]
+        [Input("startX", "Offset of the StartNode along the local x-axis, i.e. along the tangent.", typeof(Length))]
+        [Input("startY", "Offset of the StartNode along the local y-axis, i.e. along the axis perpendicular to the normal and tangent (generally minor axis).", typeof(Length))]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Offsets/Offset.cs]: The y-axis is typically the major axis.

File: Structure_Engine/Create/Offsets/Offset.cs [hunk 36]
```diff
@@ -30,6 +34,14 @@ public static partial class Create
...
+        [Input("startZ", "Offset of the StartNode along the local z-axis, i.e. along the normal (generally major axis).", typeof(Length))]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Offsets/Offset.cs]: The z-axis is typically the minor axis.

File: Structure_Engine/Create/Offsets/Offset.cs [hunk 37]
```diff
@@ -30,6 +34,14 @@ public static partial class Create
...
+        [Input("endX", "Offset of the EndNode along the local x-axis, i.e. along the tangent.", typeof(Length))]
+        [Input("endY", "Offset of the EndNode along the local y-axis, i.e. along the axis perpendicular to the normal and tangent (generally minor axis).", typeof(Length))]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Offsets/Offset.cs]: as above

File: Structure_Engine/Create/Offsets/Offset.cs [hunk 38]
```diff
@@ -30,6 +34,14 @@ public static partial class Create
...
+        [Input("endZ", "Offset of the EndNode along the local z-axis, i.e. along the normal (generally major axis).", typeof(Length))]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Offsets/Offset.cs]: as above

File: Structure_Engine/Create/SectionProperties/ConcreteSection.cs [hunk 39]
```diff
@@ -41,8 +42,8 @@ public static partial class Create
         /***************************************************/
 
         [Description("Creates a rectangular solid concrete section from input dimensions. Please note that all units are in S.I., that is meters [m].")]
-        [Input("height", "Height of the section [m].")]
-        [Input("width", "Width of the section [m].")]
+        [Input("height", "Height of the section.", typeof(Length))]
+        [Input("width", "Width of the section.", typeof(Length))]
         [Input("material", "Concrete material to be used on the section. If null a default material will be extracted from the database.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/ConcreteSection.cs]: applied to the section

File: Structure_Engine/Create/SectionProperties/ConcreteSection.cs [hunk 40]
```diff
@@ -55,10 +56,10 @@ public static ConcreteSection ConcreteRectangleSection(double height, double wid
...
         [Description("Creates a rectangular solid concrete section from input dimensions. Please note that all units are in S.I., that is meters [m].")]
-        [Input("height", "Full height of the section [m].")]
-        [Input("webThickness", "Thickness of the web [m].")]
-        [Input("flangeWidth", "Width of the flange [m].")]
-        [Input("flangeThickness", "Thickness of the flange [m].")]
+        [Input("height", "Full height of the section.", typeof(Length))]
+        [Input("webThickness", "Thickness of the web.", typeof(Length))]
+        [Input("flangeWidth", "Width of the flange.", typeof(Length))]
+        [Input("flangeThickness", "Thickness of the flange.", typeof(Length))]
         [Input("material", "Concrete material to be used on the section. If null a default material will be extracted from the database.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/ConcreteSection.cs]: applied to the section

File: Structure_Engine/Create/SectionProperties/SteelSection.cs [hunk 41]
```diff
@@ -41,12 +42,12 @@ public static partial class Create
         /***************************************************/
 
         [Description("Creates a steel I-section from input dimensions. Please note that all units are in S.I., that is meters [m].")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/SteelSection.cs]: Are we able to use quantities in the description?

File: Structure_Engine/Create/SectionProperties/SteelSection.cs [hunk 42]
```diff
@@ -58,13 +59,13 @@ public static SteelSection SteelISection(double height, double webThickness, dou
...
-        [Input("botFlangeWidth", "Width of the bottom flange [m].")]
-        [Input("botFlangeThickness", "Thickness of the bottom flange [m].")]
-        [Input("weldSize", "Optional fillet weld size between web and flanges. Meassured as the distance between intersection of web and flange perpendicular to the edge of the weld [m].")]
+        [Input("height", "Full height of the section.", typeof(Length))]
+        [Input("webThickness", "Thickness of the web.", typeof(Length))]
+        [Input("topFlangeWidth", "Width of the top flange.", typeof(Length))]
+        [Input("topFlangeThickness", "Thickness of the top flange.", typeof(Length))]
+        [Input("botFlangeWidth", "Width of the bottom flange.", typeof(Length))]
+        [Input("botFlangeThickness", "Thickness of the bottom flange.", typeof(Length))]
+        [Input("weldSize", "Optional fillet weld size between web and flanges. Meassured as the distance between intersection of web and flange perpendicular to the edge of the weld.", typeof(Length))]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/SteelSection.cs]: measured

File: Structure_Engine/Create/SectionProperties/SteelSection.cs [hunk 43]
```diff
@@ -76,11 +77,11 @@ public static SteelSection SteelFabricatedISection(double height, double webThic
...
         [Description("Creates a steel box-section from input dimensions. Please note that all units are in S.I., that is meters [m].")]
-        [Input("height", "Full height of the section [m].")]
-        [Input("width", "Full width of the section [m].")]
-        [Input("thickness", "Thickness of the webs and flanges [m].")]
-        [Input("innerRadius", "Optional inner corner radius. Commonly set equal to the thickness [m].")]
-        [Input("outerRadius", "Optional outer corner radius. Commonly set to 1.5-2 times the thickness [m].")]
+        [Input("height", "Full height of the section.", typeof(Length))]
+        [Input("width", "Full width of the section.", typeof(Length))]
+        [Input("thickness", "Thickness of the webs and flanges.", typeof(Length))]
+        [Input("innerRadius", "Optional inner corner radius. Commonly set equal to the thickness.", typeof(Length))]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/SteelSection.cs]: Typically

File: Structure_Engine/Create/SectionProperties/SteelSection.cs [hunk 44]
```diff
@@ -76,11 +77,11 @@ public static SteelSection SteelFabricatedISection(double height, double webThic
...
+        [Input("outerRadius", "Optional outer corner radius. Commonly set to 1.5-2 times the thickness.", typeof(Length))]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/SteelSection.cs]: Typically

File: Structure_Engine/Create/SectionProperties/SteelSection.cs [hunk 45]
```diff
@@ -76,11 +77,11 @@ public static SteelSection SteelFabricatedISection(double height, double webThic
...
         [Input("material", "Steel material to be used on the section. If null a default material will be extracted from the database.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/SteelSection.cs]: applied to

File: Structure_Engine/Create/SectionProperties/SteelSection.cs [hunk 46]
```diff
@@ -92,11 +93,11 @@ public static SteelSection SteelBoxSection(double height, double width, double t
...
-        [Input("height", "Full height of the section [m].")]
-        [Input("width", "Full width of the section [m].")]
-        [Input("webThickness", "Thickness of the webs [m].")]
-        [Input("flangeThickness", "Thickness of the flanges [m].")]
-        [Input("weldSize", "Optional fillet weld size between inside of web and flanges. Meassured as the distance between intersection of web and flange perpendicular to the edge of the weld [m].")]
+        [Input("height", "Full height of the section.", typeof(Length))]
+        [Input("width", "Full width of the section.", typeof(Length))]
+        [Input("webThickness", "Thickness of the webs.", typeof(Length))]
+        [Input("flangeThickness", "Thickness of the flanges.", typeof(Length))]
+        [Input("weldSize", "Optional fillet weld size between inside of web and flanges. Meassured as the distance between intersection of web and flange perpendicular to the edge of the weld.", typeof(Length))]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/SteelSection.cs]: measured

File: Structure_Engine/Create/SectionProperties/SteelSection.cs [hunk 47]
```diff
@@ -92,11 +93,11 @@ public static SteelSection SteelBoxSection(double height, double width, double t
...
         [Input("material", "Steel material to be used on the section. If null a default material will be extracted from the database.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/SteelSection.cs]: applied to

File: Structure_Engine/Create/SectionProperties/SteelSection.cs [hunk 48]
```diff
@@ -41,12 +42,12 @@ public static partial class Create
...
-        [Input("rootRadius", "Optional fillet radius between inner face of flange and face of web [m].")]
-        [Input("toeRadius", "Optional fillet radius at the outer edge of the flange [m].")]
+        [Input("height", "Full height of the section.", typeof(Length))]
+        [Input("webThickness", "Thickness of the web.", typeof(Length))]
+        [Input("flangeWidth", "Width of the top and bottom flange.", typeof(Length))]
+        [Input("flangeThickness", "Thickness of the top and bottom flange.", typeof(Length))]
+        [Input("rootRadius", "Optional fillet radius between inner face of flange and face of web.", typeof(Length))]
+        [Input("toeRadius", "Optional fillet radius at the outer edge of the flange.", typeof(Length))]
         [Input("material", "Steel material to be used on the section. If null a default material will be extracted from the database.")]
         [Input("name", "Name of the steel section.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/SteelSection.cs]: All of these should include: This is required for most structural packages to create the section.

File: Structure_Engine/Create/SectionProperties/SteelSection.cs [hunk 49]
```diff
@@ -108,8 +109,8 @@ public static SteelSection FabricatedSteelBoxSection(double height, double width
         /***************************************************/
 
         [Description("Creates a circular hollow steel section from input dimensions. Please note that all units are in S.I., that is meters [m].")]
-        [Input("diameter", "Outer diameter of the section [m].")]
-        [Input("thickness", "Plate thickness of the section [m].")]
+        [Input("diameter", "Outer diameter of the section.", typeof(Length))]
+        [Input("thickness", "Plate thickness of the section.", typeof(Length))]
         [Input("material", "Steel material to be used on the section. If null a default material will be extracted from the database.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/SteelSection.cs]: applied to

File: Structure_Engine/Create/SectionProperties/SteelSection.cs [hunk 50]
```diff
@@ -121,9 +122,9 @@ public static SteelSection SteelTubeSection(double diameter, double thickness, S
         /***************************************************/
 
         [Description("Creates a rectangular solid steel section from input dimensions. Please note that all units are in S.I., that is meters [m].")]
-        [Input("height", "Height of the section [m].")]
-        [Input("width", "Width of the section [m].")]
-        [Input("cornerRadius", "Optional corner radius for the section [m].")]
+        [Input("height", "Height of the section.", typeof(Length))]
+        [Input("width", "Width of the section.", typeof(Length))]
+        [Input("cornerRadius", "Optional corner radius for the section.", typeof(Length))]
         [Input("material", "Steel material to be used on the section. If null a default material will be extracted from the database.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/SteelSection.cs]: applied to

File: Structure_Engine/Create/SectionProperties/SteelSection.cs [hunk 51]
```diff
@@ -135,7 +136,7 @@ public static SteelSection SteelRectangleSection(double height, double width, do
         /***************************************************/
 
         [Description("Creates a circular solid steel section from input dimensions. Please note that all units are in S.I., that is meters [m].")]
-        [Input("diameter", "Diameter of the section [m].")]
+        [Input("diameter", "Diameter of the section.", typeof(Length))]
         [Input("material", "Steel material to be used on the section. If null a default material will be extracted from the database.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/SteelSection.cs]: applied to (assume you'll just do a find and replace for the rest.

File: Structure_Engine/Create/SectionProperties/SteelSection.cs [hunk 52]
```diff
@@ -165,12 +166,12 @@ public static SteelSection SteelTSection(double height, double webThickness, dou
         /***************************************************/
 
         [Description("Creates a steel L-section from input dimensions. Please note that all units are in S.I., that is meters [m].")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/SteelSection.cs]: Angle section?

File: Structure_Engine/Create/SectionProperties/TimberSection.cs [hunk 53]
```diff
@@ -41,9 +42,9 @@ public static partial class Create
         /***************************************************/
 
         [Description("Creates a rectangular solid timber section from input dimensions. Please note that all units are in S.I., that is meters [m].")]
-        [Input("height", "Height of the section [m].")]
-        [Input("width", "Width of the section [m].")]
-        [Input("cornerRadius", "Optional corner radius for the section [m].")]
+        [Input("height", "Height of the section.", typeof(Length))]
+        [Input("width", "Width of the section.", typeof(Length))]
+        [Input("cornerRadius", "Optional corner radius for the section.", typeof(Length))]
         [Input("material", "Timber material to be used on the section. If null a default material will be extracted from the database.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/TimberSection.cs]: applied to

File: Structure_Engine/Create/Loads/BarTemperatureLoad.cs (hunk 19 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Create/Loads/BarTemperatureLoad.cs]: beaten by exceptions again! https://english.stackexchange.com/questions/4700/is-it-a-uniform-or-an-uniform

File: Structure_Engine/Create/Offsets/Offset.cs (hunk 35 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Create/Offsets/Offset.cs]: No, the y-axis is generally the minor. Rotation about the y-axis is major axis bending though.

File: Structure_Engine/Create/Offsets/Offset.cs (hunk 36 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Create/Offsets/Offset.cs]: as above

File: Structure_Engine/Create/SectionProperties/SteelSection.cs (hunk 41 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Create/SectionProperties/SteelSection.cs]: currently not, no, and I am not sure if it would make sense to do so, given that the inputs might vary. Could ofc get rid of this part of the description, but think it might be helpful?

File: Structure_Engine/Create/Offsets/Offset.cs (hunk 35 above)
Comment (peterjamesnugent) [reply Structure_Engine/Create/Offsets/Offset.cs]: I have not really heard the y-axis referred to as the minor axis - my immediate though is that it was referring to the major/minor bending axis. 

Perhaps it could be a source of confusion because typically you would say Iy is the second moment of area about the major axis (y-axis) as in [3.2.5](https://www.steelforlifebluebook.co.uk/explanatory-notes/ec3-ukna/properties/).

File: Structure_Engine/Create/SectionProperties/SteelSection.cs (hunk 41 above)
Comment (peterjamesnugent) [reply Structure_Engine/Create/SectionProperties/SteelSection.cs]: The inputs all have the quantities of [length], so is it necessary in the description too?

File: Structure_Engine/Create/Constraints/Constraint6DOF.cs [hunk 54]
```diff
@@ -31,13 +35,12 @@ public static partial class Create
...
-        {
-            return new Constraint6DOF { Name = name };
-        }
-
-        /***************************************************/
-
+        [Description("Creates a Constraint6DOF from a list of fixities and spring values.")]
+        [Input("name", "Name to be used for the Constraint. This is required for various structural packages to create the object.")]
+        [Input("fixity", "Should be a list of 6 booleans, in the order TransX, TranxY, TransZ, RotX, RotY, RotZ. If true, the fixity is set to fixed. If false, the fixity is set to free or spring, depending if the double values provided are 0 or not.")]
+        [Input("values", "Should be a list of 6 doubles with positive values (>= 0), in the orderTransX, TranxY, TransZ, RotX, RotY, RotZ. If zero, and corresponding fixity is false, the DOF will be free. If non-zero, these values will be set as the spring values. \n" +
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Constraints/Constraint6DOF.cs]: I think we can get rid of the "Should be"

File: Structure_Engine/Create/Constraints/Constraint6DOF.cs [hunk 55]
```diff
@@ -31,13 +35,12 @@ public static partial class Create
...
+                         "First three should have the quantity force per unit length, last three should be moment per unit angle.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Constraints/Constraint6DOF.cs]: Same here

File: Structure_Engine/Create/Constraints/Constraint6DOF.cs [hunk 56]
```diff
@@ -106,6 +118,15 @@ public static Constraint6DOF FullReleaseConstraint6DOF(string name = "Release")
 
         /***************************************************/
 
+        [Description("Creates a Constraint6DOF from a set of booleans. True means fixed, false means free.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Constraints/Constraint6DOF.cs]: denotes free

I think we should keep consistent language with the LinkConstraint

File: Structure_Engine/Create/Constraints/Constraint6DOF.cs [hunk 57]
```diff
@@ -106,6 +118,15 @@ public static Constraint6DOF FullReleaseConstraint6DOF(string name = "Release")
...
+        [Input("x", "Translational fixity in x-direction. True means fixed, false means free.")]
+        [Input("y", "Translational fixity in y-direction. True means fixed, false means free.")]
+        [Input("z", "Translational fixity in z-direction. True means fixed, false means free.")]
+        [Input("xx", "Rotational fixity about the x-axis. True means fixed, false means free.")]
+        [Input("yy", "Rotational fixity about the y-axis. True means fixed, false means free.")]
+        [Input("zz", "Rotational fixity about the z-axis. True means fixed, false means free.")]
+        [Input("name", "Name of the Constraint6DOF. This is required for various structural packages to create the object.")]
+        [Output("release", "The created custom Constraint6DOF.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Constraints/Constraint6DOF.cs]: as above

File: Structure_Engine/Create/Constraints/LinkConstraint.cs [hunk 58]
```diff
@@ -32,6 +36,11 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+
+        [Description("Creates a LinkConstraint from a list of booleans. True denotes fixity.")]
+        [Input("name", "Name of the created LinkConstraint. This is required for various structural packages to create the object.")]
+        [Input("fixity", "List of booleans setting the fixities of the LinkConstraint. True denotes fixity. Should be a list of 12 booleans in the following order: XtoX, YtoY, ZtoZ, XtoYY, XtoZZ, YtoXX, YtoZZ, ZtoXX, ZtoYY, XXtoXX, YYtoYY, ZZtoZZ.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Constraints/LinkConstraint.cs]: remove "should be"

File: Structure_Engine/Create/Elements/Panel.cs [hunk 59]
```diff
@@ -39,55 +40,39 @@ public static partial class Create
...
-        {
-            if (!outline.IIsClosed()) return null;
-            List<Edge> externalEdges = outline.ISubParts().Select(x => new Edge { Curve = x }).ToList();
-
-            return Panel(externalEdges, openings, property, name);
-        }
-
-        /***************************************************/
-
+        [Description("Creates a structural Panel from a closed curve defining the outline, and any number of closed curves definig openings.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Elements/Panel.cs]: defining

File: Structure_Engine/Create/Framing/FramingElement.cs [hunk 60]
```diff
@@ -41,6 +41,7 @@ public static partial class Create
         [Description("Creates a physical IFramingElement from a bar. The framing element will be assigned a ConstantFramingProperty based on the sectionproeprty of the bar and have a type based on the structural usage.")]
         [Input("bar", "The bar to use as the base for the framing element.")]
         [Input("structuralUsage", "Used to determine which type of framing element that should be constructed.")]
+        [Output("framing", "The created phsyical FramignElement based on the Bar element provided.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Framing/FramingElement.cs]: FramingElement

File: Structure_Engine/Create/SectionProperties/ConcreteSection.cs [hunk 61]
```diff
@@ -98,8 +100,9 @@ public static ConcreteSection ConcreteFreeFormSection(List<ICurve> edges, Concre
 
         [Description("Generates a concrete section based on a Profile and a material. \n This is the main create method for concrete sections, responsible for calculating section constants etc. and is being called from all other create methods for concrete sections.")]
         [Input("profile", "The section profile the concrete section. All section constants are derived based on the dimensions of this.")]
-        [Input("material", "concrete material to be used on the section. If null a default material will be extracted from the database.")]
-        [Input("name", "Name of the concrete section. If null or empty the name of the profile will be used.")]
+        [Input("material", "concrete material to be applied to the section. If null a default material will be extracted from the database.")]
+        [Input("name", "Name of the concrete section. If null or empty the name of the profile will be used. This is required for most structural packages to create the section.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/SectionProperties/ConcreteSection.cs]: "If null or empty the name of the profile will be used." 

If this is true for all SectionProperty (SteelSection, ConcreteSection etc.) I think it should be included with "This is required for most structural packages..." in all name fields.

File: Structure_Engine/Modify/Flip.cs [hunk 62]
```diff
@@ -32,6 +36,9 @@ public static partial class Modify
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Flips the StartNode and EndNode of the Bar, i.e. the StartNode is set to the EndNode and vice versa. No modification is being made to releases, oriantation angle, offsets etc.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Modify/Flip.cs]: orientation

File: Structure_Engine/Modify/Flip.cs [hunk 63]
```diff
@@ -45,6 +52,9 @@ public static Bar Flip(this Bar bar)
 
         /***************************************************/
 
+        [Description("Flips the location curve of the Edge, i.e. the start becomes the end and vice versa.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Modify/Flip.cs]: StartNode becomes the EndNode

File: Structure_Engine/Modify/SetMaterial.cs [hunk 64]
```diff
@@ -33,6 +36,10 @@ public static partial class Modify
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Sets the material of a Bar by updating the material of its SectionProperty.")]
+        [Input("bar", "The Bar to set the material to, i.e. the Bar to get the Material of its SectionProeprty updated.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Modify/SetMaterial.cs]: SectionProperty

File: Structure_Engine/Modify/SetReinforcement.cs [hunk 65]
```diff
@@ -33,6 +37,10 @@ public static partial class Modify
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Sets Reinforcement to a ConcreteSection. Any previous Reinforcement will be overwritten.")]
+        [Input("section", "The concrete section to set Reinforcement to.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Modify/SetReinforcement.cs]: ConcreteSection

File: Structure_Engine/Modify/SetStructuralFragment.cs [hunk 66]
```diff
@@ -40,6 +40,7 @@ public static partial class Modify
         [Description("Assigns a material fragemnt to a material. First removes any previous instances of the IMaterialFragment from the list, then adds the new.")]
         [Input("material", "The physical material to add a structural fragment to.")]
         [Input("structuralFragment", "The structural fragment to be appended to the material. Will replace any previous instance.")]
+        [Output("material", "Physical Material with structural material fragment set.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Modify/SetStructuralFragment.cs]: MaterialFragment

File: Structure_Engine/Create/Offsets/Offset.cs (hunk 35 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Create/Offsets/Offset.cs]: yeah, get what you mean, will get rid of it then.

Have generally been separating the transnational and rotational in my head at least (as well I think in the desc in general), like, Load acting along local z - major, Asz - major, Fz - major, and the rotational such as Iy, Wply, My - all major etc. 

And as this referred to transitional things, I matched it up that way, but if it is more confusing than helpful, then happy to get rid of it.

File: Structure_Engine/Create/SectionProperties/SteelSection.cs (hunk 41 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Create/SectionProperties/SteelSection.cs]: No, think you are right. Will get rid of it

File: Structure_Engine/Create/SectionProperties/ConcreteSection.cs (hunk 61 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Create/SectionProperties/ConcreteSection.cs]: Should be on all sections creats that explicitly accepts a profile I think. For others, you will need to provide the name, as the profile is created by the method, without a name.

Was missing in one place (for the dispatcher method), have added it there!

File: Structure_Engine/Modify/Flip.cs (hunk 63 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Modify/Flip.cs]: This is relating to a general curve, not a bar, so nodes involved (and no explicit properties, as they vary with curve type). Think I will leave unchanged?

File: Structure_Engine/Compute/Integrate.cs [hunk 67]
```diff
@@ -37,6 +41,12 @@ public static partial class Compute
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("This method is largely replaced by the Compute.IntegrateSection() Method. \n" +
+                     "Calculates Section properties for a region on the XY-Plane. \n" +
```
Comment (peterjamesnugent) [inline Structure_Engine/Compute/Integrate.cs]: section properties

File: Structure_Engine/Compute/Integrate.cs [hunk 68]
```diff
@@ -95,6 +105,11 @@ public static partial class Compute
 
         /***************************************************/
 
+        [Description("Calculates all non-torsional section constants for a section profile based its edge curves and adjusts the profile curves to make them centred around the origin.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Compute/Integrate.cs]: Calculates all non-torsional section constants for a section profile based on its edge curves and translates the profile curves to be centred around the origin.

File: Structure_Engine/Compute/Integrate.cs [hunk 69]
```diff
@@ -95,6 +105,11 @@ public static partial class Compute
...
+        [Input("profile", "The profile to integrate.")]
+        [Input("tolerance", "The angleTolerance for dividing the section curves.")]
+        [MultiOutput(0, "profile", "The profile used in the integration, with section curves updated to be centred around the global origin.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Compute/Integrate.cs]: The profile used in the integration. The section curves are translated to be centred around the global origin.

File: Structure_Engine/Create/Constraints/BarRelease.cs [hunk 70]
```diff
@@ -60,16 +61,34 @@ public static BarRelease BarReleasePinPin(string name = "PinPin")
 
         /***************************************************/
 
+        [Description("Creates a BarRelease that is pinned at one end and axially released at the other. \n" +
+                     "This means that the start node will have all tranlational degrees fixed as well as the RX, to avoid instability, i.e. to prevent it from rotating about the local x-axis (the centreline axis). \n" +
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Constraints/BarRelease.cs]: rx given that we are referring to local rotations.

File: Structure_Engine/Create/Offsets/Offset.cs [hunk 71]
```diff
@@ -30,6 +34,14 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Creates a Offset defining offsets for Bar objects from its end Nodes to be applied in analysis packages.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Create/Offsets/Offset.cs]: an Offset

File: Structure_Engine/Modify/Flip.cs (hunk 63 above)
Comment (peterjamesnugent) [reply Structure_Engine/Modify/Flip.cs]: agreed

File: Structure_Engine/Modify/SetMaterial.cs [hunk 72]
```diff
@@ -33,6 +36,10 @@ public static partial class Modify
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Sets the material of a Bar by updating the material of its SectionProperty.")]
+        [Input("bar", "The Bar to set the material to, i.e. the Bar to have the Material of its SectionProperty updated.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Modify/SetMaterial.cs]: Material

File: Structure_Engine/Compute/Integrate.cs (hunk 67 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Compute/Integrate.cs]: changing to "section constants"

File: Structure_Engine/Modify/SetMaterial.cs (hunk 72 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Modify/SetMaterial.cs]: Changing to consistent lower-casing instead, as it is not referring to the physical Material class

File: Structure_Engine/Compute/Integrate.cs (hunk 67 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Compute/Integrate.cs]: changing to "section constants"

**Comment by IsakNaslundBh** [comment]
merging master into current due to complaints on CI from for Environments updates.
