### PR TITLE
Structure_Engine: Transform stopped from crashing for panels with nurbs edges

### LINKED ISSUE #2397: Structure_Engine: Transform crashes for panels with nurbs edges
#### Description:

As in the title: if the structural panel has an edge based on a nurbs curve, an attempt to transform it fails because of `Normal` query returning `null`.

To be tackled in this sprint to avoid weird behaviour once https://github.com/BHoM/Revit_Toolkit/issues/975 gets resolved.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #2397

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FStructure%5FEngine%2F%232398%2DPanelTransformBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### Changelog

- `Transform` stopped from crashing for panels with nurbs edges

### Additional comments

Component going red due to the underlaying error looks a bit weird, but at least the method works...

### CODE REVIEW

File: Geometry_Engine/Query/Normal.cs [hunk 1]
```diff
@@ -157,6 +157,13 @@ public static Vector Normal(this Polyline curve, double tolerance = Tolerance.Di
         [Output("normal", "Vector normal to the plane of a curve.")]
         public static Vector Normal(this PolyCurve curve, double tolerance = Tolerance.Distance)
         {
+            List<ICurve> crvs = new List<ICurve>(curve.ISubParts());
+            if (crvs.Any(x => !(x is Line || x is Arc)))
```
Comment (IsakNaslundBh) [inline Geometry_Engine/Query/Normal.cs:161]:
```suggestion
            if (crvs.Any(x => !(x is Line || x is Arc || x is Circle)))
```

**Review by IsakNaslundBh — COMMENTED** [review]
Think circle is required as well?

File: Geometry_Engine/Query/Normal.cs (hunk 1 above)
Comment (pawelbaran) [reply Geometry_Engine/Query/Normal.cs:161]: Agreed, makes sense

**Review by LMarkowski — APPROVED** [review]
Changes in code looks good and the code itself works as it should.

Regarding additional comments I've raised once an issue that might revisited one day. I think it'd be reasonable to be able to hide events that we are aware of and deal with in the higher level methods. #1306

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check serialisation

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge
