### PR TITLE
Geometry_Engine: issues 980, 1008: Join(iCurve) bug and Circles inside PolyCurves

### LINKED ISSUE #1008: Geometry_Engine: IJoin wraps PolyCurves into another PolyCurves
`IJoin(List<ICurve>)`

If input is `PolyCurve{Curves}` method wraps it into `PolyCurve{Curves = PolyCurve{Curves}}`.  It causes further errors as most of methods do not cover PolyCurves containing of PolyCurves.

### PR DESCRIPTION
**Pull request by LMarkowski**
### Issues addressed by this PR

closes #1008
addresses #980

Fixed `Join (List<ICurve>)` so now if there is PolyCurve as input it will stay unchanged and will not be wrapped into another PolyCurve.
Updated `SplitAtPoints`, `IsClockwise` and `IsCoplanar` `(PolyCurve)` so now when a Circle is a part of PolyCurve, these methods would return correct values. Also created `IsClockwise(Circle)`.

### Test files
Join - regular test [file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Modify/Join.gh?csf=1&e=Dt1zjb)
SplitAtPoints, IsClockwise and IsCoplanar - [issue specific test](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Geometry_Engine-issue980-CircleInPolycurveIssue/Geometry_Engine-issue980-CircleInPolycurveIssue.gh?csf=1&e=kgMlaN). As grasshopper immediately casts everything, there was a problem with providing input as Circle inside a PolyCurve. I've made additional 3 test methods which at the first step cast Circle to PolyCurve and then work exactly same as regular ones. They are all in this test file. **THEY NEED TO BE DELETED BEFORE MERGING.** 
I've updated some of regular test files to check if after updates all methods work as they did.
SplitAtPoints - [click](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Modify/SplitAtPoints.gh?csf=1&e=BmLIQd)
IsClockwise - [click](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Query/IsClockwise.gh?csf=1&e=fz56Xb)
IsCoplanar - [click](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Query/IsCoplanar.gh?csf=1&e=Z2mUaq)

### Changelog
Updated:
- `Join (List<ICurve>)`
- `SplitAtPoints(PolyCurve)`
- `IsClockwise<PolyCurve>)`
- `IsCoplanar(PolyCurve)`

Added:
- `IsClockwise(Circle)`

### Additional comments
As soon as this PR will be merged I will push another with Interfaces for Boolean operations on regions.
Edit: I just realized that I said so two PRs ago, but it was before we decided that Circular panels should also be included 😄

### CODE REVIEW

File: Geometry_Engine/Query/IsClockwise.cs [hunk 1]
```diff
@@ -75,8 +75,14 @@ public static bool IsClockwise(this PolyCurve curve, Vector normal, double toler
...
                 else if (c is Arc)
                 {
-                    cPts.Add(c.IPointAtParameter(0.5));
-                    cPts.Add(c.IEndPoint());
+                    cPts.Add((c as Arc).PointAtParameter(0.5));
+                    cPts.Add((c as Arc).EndPoint());
+                }
+                else if (c is Circle)
+                {
+                    cPts.Add((c as Circle).PointAtParameter(0.3));
```
Comment (pawelbaran) [inline Geometry_Engine/Query/IsClockwise.cs]: Maybe a detail, but why not use 1.0/3 and 2.0/3?

File: Geometry_Engine/Query/IsClockwise.cs [hunk 2]
```diff
@@ -115,16 +121,38 @@ public static bool IsClockwise(this Arc arc, Vector axis, double tolerance = Tol
             return ((normal.DotProduct(axis) < 0) != (arc.Angle() > Math.PI));       
         }
 
+        /***************************************************/
+
+        public static bool IsClockwise(this Circle curve, Vector axis, double tolerance = Tolerance.Distance)
```
Comment (pawelbaran) [inline Geometry_Engine/Query/IsClockwise.cs]: Why not base the IsClockwise between the sign of dot product of circle normal and reference vector?

File: Geometry_Engine/Query/IsClockwise.cs (hunk 1 above)
Comment (LMarkowski) [reply Geometry_Engine/Query/IsClockwise.cs]: Reducing number of calculations? I don't know, it can be changed but I don't think it will affect the results.

File: Geometry_Engine/Query/IsClockwise.cs (hunk 2 above)
Comment (LMarkowski) [reply Geometry_Engine/Query/IsClockwise.cs]: Good idea 👍

File: Geometry_Engine/Query/IsClockwise.cs (hunk 1 above)
Comment (pawelbaran) [reply Geometry_Engine/Query/IsClockwise.cs]: I think the extra calcs are nothing compared to the whole computation. Main reason for using fractions is readability.

**Comment by LMarkowski** [comment]
@IsakNaslundBh @FraserGreenroyd Do you want to do an extra review or may I delete test methods and ask to merge?

**Comment by FraserGreenroyd** [comment]
@LMarkowski if you and @pawelbaran are happy, I'm happy. Go for it.

**Comment by FraserGreenroyd** [comment]
It still has the `do-not-merge` status label - is that for good reason or an accident guys? @pawelbaran @LMarkowski

**Comment by LMarkowski** [comment]
Yeah, I forgot to remove it..
