### PR TITLE
Reflection_Engine: LoadAllAssemblies fixed to load assemblies with dot in name

### LINKED ISSUE #2712: Reflection_Engine: LoadAllAssemblies does not load assemblies with dot in name
#### Description:

...because of the file name being split and only the last part being passed downstream. https://github.com/BHoM/BHoM_Engine/blob/6cf19b04a34803fcdc904bdfaaab3245f5869514/Reflection_Engine/Compute/LoadAllAssemblies.cs#L78-L82

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #2712

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&isAscending=true&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine%2F%232713%2DLoadAssembliesWithDots&sortField=LinkFilename&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b).

### Additional comments

This bug should not affect the Beta release (it was found while working on https://github.com/BHoM/Revit_Toolkit/pull/1137), so I am not pushing it - up to the framework lead whether worth merging now or after the end of the milestone @FraserGreenroyd.

### CODE REVIEW

File: Reflection_Engine/Compute/LoadAllAssemblies.cs [hunk 1]
```diff
@@ -75,11 +75,12 @@ public static List<Assembly> LoadAllAssemblies(string folder = "", string regexF
                 SearchOption searchOption = parseSubfolders ? SearchOption.AllDirectories : SearchOption.TopDirectoryOnly;
                 foreach (string file in Directory.GetFiles(folder, "*.dll", searchOption))
                 {
-                    string[] parts = file.Split(new char[] { '.', '\\' });
+                    string[] parts = file.Split(new char[] { '\\' });
                     if (parts.Length < 2)
                         continue;
 
-                    string name = parts[parts.Length - 2];
+                    string name = parts[parts.Length - 1];
```
Comment (adecler) [inline Reflection_Engine/Compute/LoadAllAssemblies.cs:82]: The check on `parts.Length` was only necessary when the file extension was split into its own part. Now that this doesn't happen, the check should be removed. 

While you are at it, I also suggest to used `parts.Last()` instead of `parts[parts.Length - 1]` as it is cleaner.

**Review by adecler — CHANGES_REQUESTED** [review]
Minor fix needed otherwise looks good.

File: Reflection_Engine/Compute/LoadAllAssemblies.cs (hunk 1 above)
Comment (pawelbaran) [reply Reflection_Engine/Compute/LoadAllAssemblies.cs]: Yeah you are right - I cleaned it up properly this time by using string `Path.GetFileNameWithoutExtension()` method 👍

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Review by adecler — APPROVED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 4743358611

This was handled in a prior PR and will risk conflict to fix it here too.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge
