### PR TITLE
Geometry Engine: fix Offset(PolyCurve) Arcs bug

### LINKED ISSUE #1407: Geometry Engine: Offset(PolyCurve) fails on input consisting of Arcs joining into a circle
#### Description:

As in header.

#### Expected behaviour:

Should return proper offset.

#### Test file(s):

[Click](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssue1407%2DOffsetArcsIntoCircleBug)

### PR DESCRIPTION
**Pull request by LMarkowski**
### Issues addressed by this PR

Fixing a bug that occurred while offsetting a PolyCurve consisting of Arcs which were parts of one circle.

Closes #1407 

### Test files

[Same file](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssue1407%2DOffsetArcsIntoCircleBug) that was in the issue.

### Changelog

- `Modify.Offset()` method updated in the `Geometry_Engine` for `PolyCurve` class.
- `Modify.Fillet()` private method updated in the `Geometry_Engine`.

### CODE REVIEW

File: Geometry_Engine/Modify/Offset.cs [hunk 1]
```diff
@@ -587,6 +587,9 @@ private static PolyCurve Fillet(this ICurve curve1, ICurve curve2, bool tangentE
             if (!((curve1 is Line || curve1 is Arc) && (curve2 is Line || curve2 is Arc))) //for now works only with combinations of lines and arcs
                 throw new NotImplementedException();
 
+            if (Compute.IJoin(new List<ICurve> { curve1, curve2 }, tolerance).Count == 1)
+                return Compute.IJoin(new List<ICurve> { curve1, curve2 }, tolerance)[0];
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Offset.cs]: Overhead
