### PR TITLE
Lighting_Engine: Remove calls to GetShallowClone

### LINKED ISSUE #2560: Lighting_Engine: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone
#### Broken rules:
See https://github.com/BHoM/admin/issues/9

#### Suggestions to restore compliance:
https://github.com/BHoM/admin/issues/9#issuecomment-709032648

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #2560

### CODE REVIEW

**Review by adecler — DISMISSED** [review]

File: Lighting_Engine/Modify/Transform.cs [hunk 1]
```diff
@@ -47,7 +48,7 @@ public static Luminaire Transform(this Luminaire luminaire, TransformMatrix tran
                 return null;
             }
 
-            Luminaire result = luminaire.GetShallowClone() as Luminaire;
+            Luminaire result = luminaire.ShallowClone() as Luminaire;
```
Comment (FraserGreenroyd) [inline Lighting_Engine/Modify/Transform.cs:51]:
```suggestion
            Luminaire result = luminaire.ShallowClone();
```

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge
