### PR TITLE
Structure_Engine: Fixed bug where PanelToFEMesh returned an error 

### LINKED ISSUE #3360: Structure_Engine: PanelToFEMesh does not work when lines have differing directions
#### Description:

`PanelToFEMesh` does not give sufficient results when point ordering is not sorted along the curve.

#### Steps to reproduce:

Test file.

#### Expected behaviour:

`FEMesh` to be reproduced with correct geometry from `Panel`.

#### Test file(s):

https://burohappold.sharepoint.com/:u:/s/BHoM/EW7jAkBEjXJLkQms-JGmrF0BvlpHxA0_H-mVl_42zf0HtA?e=keCf04

### LINKED ISSUE #3365: Geometry_Engine: DiscontinuityPoints does not worked for open PolyCurves
#### Description:

`PolyCurve.DiscontinuityPoints()` does not work when `PolyCurve.IsClosed() == false`.

#### Steps to reproduce:

Test file

#### Expected behaviour:

Current method uses `EndPoint` which defaults to the fallback method, needs to use `IEndPoint`.

#### Test file(s):

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Geometry_Engine/%233365-DiscontinuityPointsForPolyCurve.gh?csf=1&web=1&e=g5pYK0

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #3360 
Closes #3365

### Test files

[PanelToFEMesh](https://burohappold.sharepoint.com/:u:/s/BHoM/EW7jAkBEjXJLkQms-JGmrF0BvlpHxA0_H-mVl_42zf0HtA?e=keCf04)
[DiscontinuityPoints](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Geometry_Engine/%233365-DiscontinuityPointsForPolyCurve.gh?csf=1&web=1&e=g5pYK0)

### Changelog

- Fixed by bug whereby one `Edge` existed in the opposite direction to the `Panel` would caush an error for `PanelToFEMesh`;
- Fixed bug whereby `DiscontinuityPoints()` did not work for `PolyCurve`;
- Updated unit tests for `DiscontinuityPoints()` to include open `PolyCurve`s;
- Replaced unit tests for `FEMeshToPanel` and `PanelToFEMesh` as the data was empty.

Got the branch name wrong 🤐

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Review by pawelbaran — COMMENTED** [review]
Code changes in `DiscontinuityPoints` make sense to me, as discussed with @peterjamesnugent - can't speak about structures though, therefore just a comment and not approval.

File: Structure_Engine/Convert/PanelToFEMesh.cs [hunk 1]
```diff
@@ -39,58 +38,54 @@ public static partial class Convert
...
+            else
+            {
+                Base.Compute.RecordError("Panel is not a planar quadilateral or triangular.");
+                return null;
+            }
+
+            PolyCurve outline = panel.OutlineCurve().Curves.IJoin()[0];
+            List<Point> points = outline.DiscontinuityPoints();
+            points = points.CullDuplicates(tolerance).ISortAlongCurve(outline);
+
```
Comment (IsakNaslundBh) [inline Structure_Engine/Convert/PanelToFEMesh.cs:82]: Could simply count the points instead of calling the IsQuad and IsTriangle above.

```suggestion
Face face = new Face();
            if (points.Count == 3)
            {
                face = Geometry.Create.Face(0, 1, 2, 3);
            }
            else if (points.Count == 4)
            {
                face = Geometry.Create.Face(0, 1, 2);
            }
            else
            {
                Base.Compute.RecordError("Panel is not a planar quadilateral or triangular.");
                return null;
            }
```

File: Structure_Engine/Convert/PanelToFEMesh.cs [hunk 2]
```diff
@@ -39,58 +38,54 @@ public static partial class Convert
...
             }
-            faces.Add(face);
-            Mesh mesh = Geometry.Create.Mesh(points.Distinct(), faces);
+            else
+            {
+                Base.Compute.RecordError("Panel is not a planar quadilateral or triangular.");
+                return null;
+            }
+
+            PolyCurve outline = panel.OutlineCurve().Curves.IJoin()[0];
```
Comment (IsakNaslundBh) [inline Structure_Engine/Convert/PanelToFEMesh.cs:79]: If not calling IsQuad and IsTriangle, should add in this check as well
```suggestion
            PolyCurve outline = panel.OutlineCurve().Curves.IJoin()[0];
            if(outline.SubParts().Any(x => !x.IsLinear())
            {
               Base.Compute.RecordError("Panel contains non-linear edges.");
                return null;
            }
```

File: Structure_Engine/Convert/PanelToFEMesh.cs [hunk 3]
```diff
@@ -39,58 +38,54 @@ public static partial class Convert
...
+            List<Point> points = outline.DiscontinuityPoints();
+            points = points.CullDuplicates(tolerance).ISortAlongCurve(outline);
+
+            List<Face> faces = new List<Face>() { face };
+
+            Mesh mesh = Geometry.Create.Mesh(points, faces);
             FEMesh feMesh = new FEMesh();
             feMesh = Create.FEMesh(mesh, null, null, panel.Name);
+
```
Comment (IsakNaslundBh) [inline Structure_Engine/Convert/PanelToFEMesh.cs:88]: Could just provide the panel property to the constructor here, if it is null or not. After all, it is null by default, so only setting it if it is not null makes no difference.

**Review by IsakNaslundBh — COMMENTED** [review]
Some comments on further simplifications below. Will leave as a comment rather than request change, as I am going on leave, and might not have time to approve after changes are made.

File: Structure_Engine/Convert/PanelToFEMesh.cs (hunk 1 above)
Comment (peterjamesnugent) [reply Structure_Engine/Convert/PanelToFEMesh.cs:82]: Added.

File: Structure_Engine/Convert/PanelToFEMesh.cs (hunk 2 above)
Comment (peterjamesnugent) [reply Structure_Engine/Convert/PanelToFEMesh.cs:79]: Added.

File: Structure_Engine/Convert/PanelToFEMesh.cs (hunk 3 above)
Comment (peterjamesnugent) [reply Structure_Engine/Convert/PanelToFEMesh.cs:88]: Added.

**Comment by peterjamesnugent** [comment]
Added @IsakNaslundBh's comments, I will leave the IsOutlineTriangular as it will likely be useful elsewhere.

**Review by jtrainor1 — APPROVED** [review]
I have tested the following PanelToFEMesh function and it works as expected. The pulled LUSAS panels were successfully converted to FEMesh and pushed to Midas.

**Review by jtrainor1 — DISMISSED** [review]
Changes have been reviewed.

**Comment by peterjamesnugent** [comment]
@BHoMBot check required
@BHoMBot check copyright-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests 
@BHoMBot check dataset-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check unit-tests

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
Dispensating the unit test check as this PR does not introduce any new failures compared to `develop` (e.g. [here](https://github.com/BHoM/BHoM_Engine/pull/3369/checks?check_run_id=27077776498)).

**Comment by pawelbaran** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 27563530976

**Review by pawelbaran — APPROVED** [review]
Re-approving on the basis of previous approval by @jtrainor1 - the code has only been rebased since then.

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge
