### PR TITLE
Security_Engine: Remove calls to GetShallowClone

### LINKED ISSUE #2561: Security_Engine: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone
#### Broken rules:
See https://github.com/BHoM/admin/issues/9

#### Suggestions to restore compliance:
https://github.com/BHoM/admin/issues/9#issuecomment-709032648

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #2561

### CODE REVIEW

**Review by adecler — DISMISSED** [review]

File: Security_Engine/Modify/Transform.cs [hunk 1]
```diff
@@ -50,7 +51,7 @@ public static CameraDevice Transform(this CameraDevice camera, TransformMatrix t
                 return null;
             }
 
-            CameraDevice result = camera.GetShallowClone() as CameraDevice;
+            CameraDevice result = camera.ShallowClone() as CameraDevice;
```
Comment (FraserGreenroyd) [inline Security_Engine/Modify/Transform.cs:54]:
```suggestion
            CameraDevice result = camera.ShallowClone();
```

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge
