### PR TITLE
Environment_Engine: Update to new oM

### LINKED ISSUE #849: Environment_Engine: Fix IsContaining for space and point
Follow on from #847 

The `IsContaining` method for a 3D space is not accurately providing a result for when a point is being contained or not. This needs to be fixed based on the algorithm discussed with @michaldengusiak

### LINKED ISSUE #899: Environment_Engine: IsContaining fail
Our Normal check and flip that is required for gbXML relying on understanding if point is inside space... due to bug it does not work for 100% but 99.98% I isolated now one of these special cases

image

image

files can be provided on request...
[Test Script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine?csf=1&e=sF9xpQ)

### LINKED ISSUE #913: Environment_Engine: Match new oM
Reorganise the Environment Engine to meet the new oM (https://github.com/BHoM/BHoM/issues/457) and tidy up the engine methods.

Focus on simpler methods with optional named parameters to aid the Grasshopper/Dynamo manual workflows/ease of finding elements.

Include reflection description attributes for all methods to aid use.

### LINKED ISSUE #914: Physical_Engine: Creation
Create a `Physical_Engine` to match the `Physical_oM` and allow for engine methods for Physical objects.

Start with the ability to create `Construction`, `Layer`, and `Material`.

### LINKED ISSUE #915: Analytical_Engine: Create engine
Create an `Analytical_Engine` to match the `Analytical_oM`. Similar to #914

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/458 - this is the Environment oM branch which this PR depends on
   
### Issues addressed by this PR
Fixes #849 
Fixes #899 
Fixes #913 
Fixes #914 
Fixes #915 

Updates the `Environment_Engine` to match the new `Environment_oM`
Also ensures that every method has the relevant `Description`, `Input` and `Output` attributes to aid use from the Visual Programming side of things.
Creates the Physical and Analytical engines as well with some methods in both engines ready.

### Test files
N/A - still developing up through the toolkits now

#### Changed
 - Changed all methods to meet the new Environment oM

#### Added
 - Added UI documentation assistance to all methods

### Additional comments
This PR should be reviewed alongside all the others, but is not to be merged until everything in the chain is ready.

Nomenclature has been updated - all `elements` are now referred to as `panels` in the code and in the documentation. Occasional variables use `element` but for the most part, particularly public-facing, it is `panels`. All nested collections of panels representing spaces are now referred to as `panelsAsSpace(s)` as appropriate to avoid confusion when plugging data in from Visual Programming.

### CODE REVIEW

File: Environment_Engine/Convert/ICurve.cs [hunk 1]
```diff
@@ -20,38 +20,40 @@
...
-        public static ICurve Curve(this Panel buildingElementPanel)
-        {
-            return buildingElementPanel.PanelCurve;
-        }
-
-        public static ICurve Curve(this BuildingElement buildingElement)
+        [Description("BH.Engine.Environment.Convert.ToEdges => Returns a collection of Environment Edges from a BHoM Geomtry Polyline")]
+        [Input("curve", "A BHoM Geometry ICurve to be split into Environment Edges")]
+        [Output("edges", "A collection of Environment Edges")]
+        public static List<Edge> ToEdges(this ICurve curve)
```
Comment (IsakNaslundBh) [inline Environment_Engine/Convert/ICurve.cs]: Think this has been discussed regarding multiple things and believe we need to find a better definition for it in general, but: I would see the action in here as a create method rather than a Convert. I would probably in general see taking a piece of geometry and returning an object as a create action rather than a convert in general. That is at least the way it is currently done in the Structure_Engine. To me this make more sense, but could be convinced otherwise, but think this is something we need to clarify.

@al-fisher @adecler @rwemay

File: Environment_Engine/Convert/Line.cs [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+    public static partial class Convert
+    {
+        /***************************************************/
+        /****          public Methods                   ****/
+        /***************************************************/
+
+        [Description("BH.Engine.Environment.Convert.ToLines => Returns a collection of Lines representing an Environment Edge")]
+        [Input("edge", "An Environment Edge object")]
+        [Output("lines", "A collection of BHoM Geometry Line")]
+        public static List<Line> ToLines(this Edge edge)
```
Comment (IsakNaslundBh) [inline Environment_Engine/Convert/Line.cs]: Similar to the `ToEdge()` method above, I would not see this as a convert but as a query.

Almost philosophical, but I see this as getting a piece of geometry out from an object, rather than turning an object into a piece of geometry.

File: Environment_Engine/Convert/Polyline.cs [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+    public static partial class Convert
+    {
+        /***************************************************/
+        /****          public Methods                   ****/
+        /***************************************************/
+
+        [Description("BH.Engine.Environment.Convert.ToPolyline => Returns a Polyline representation of an Environment Edge")]
+        [Input("edge", "An Environment Edge object")]
+        [Output("polyline", "BHoM Geometry Polyline")]
+        public static Polyline ToPolyline(this Edge edge)
```
Comment (IsakNaslundBh) [inline Environment_Engine/Convert/Polyline.cs]: As above

File: Environment_Engine/Compute/BooleanIntersect.cs [hunk 4]
```diff
@@ -27,21 +27,24 @@
...
 {
     public static partial class Compute
     {
         /***************************************************/
-        /****          public Methods - Lines           ****/
+        /****          public Methods                   ****/
         /***************************************************/
 
-        public static bool DoesBooleanIntersect(this BuildingElement element, BuildingElement elementToCompare)
+        [Description("BH.Engine.Environment.Compute.BooleanIntersect => Returns true if two Environment Panels boolean intersect")]
```
Comment (IsakNaslundBh) [inline Environment_Engine/Compute/BooleanIntersect.cs]: Do not agree with typing out the name of the method at the start of each description. If this is something we want in general, it should be handled in the reflection_Engine or BHoM_UI, as the name and namespace fo the method can be accessed with ease. This to me just add more maintenance and risk of spelling errors etc. Might also be made somewhat redundant with the "Source Code" option added by @epignatelli in GH if we can get that added to dynamo and excel as well.

File: Environment_Engine/Modify/SetOutlineElements1D.cs [hunk 5]
```diff
@@ -33,31 +36,26 @@ public static partial class Modify
...
 
+        [Description("BH.Engine.Environment.Modify.SetOutlineElements1D => Assign a new collection of external 1D boundaries to an Environment Opening")]
+        [Input("opening", "An Environment Opening to update")]
+        [Input("outlineElements1D", "A collection of outline 1D elements to assign to the opening")]
+        [Output("opening", "The updated Environment Opening")]
         public static Opening SetOutlineElements1D(this Opening opening, List<IElement1D> outlineElements1D)
         {
             Opening o = opening.GetShallowClone() as Opening;
-            o.OpeningCurve = new PolyCurve { Curves = outlineElements1D.Cast<ICurve>().ToList() };
+            o.Edges = outlineElements1D.Cast<ICurve>().ToList().ToEdges();
```
Comment (IsakNaslundBh) [inline Environment_Engine/Modify/SetOutlineElements1D.cs]: As long as the edge objects are returned straight away from the query method, you should be able to cast them to edges straight away here. Think all of this will get moved to Analytical_Engine in the long run anyway, but could be good to know.

File: Environment_Engine/Modify/SetOutlineElements1D.cs [hunk 6]
```diff
@@ -33,31 +36,26 @@ public static partial class Modify
...
-
+        [Description("BH.Engine.Environment.Modify.SetOutlineElements1D => Assign a new collection of external 1D boundaries to an Environment Opening")]
+        [Input("opening", "An Environment Opening to update")]
+        [Input("outlineElements1D", "A collection of outline 1D elements to assign to the opening")]
+        [Output("panel", "The updated Environment Opening")]
         public static Panel SetOutlineElements1D(this Panel panel, List<IElement1D> outlineElements1D)
         {
             Panel pp = panel.GetShallowClone() as Panel;
-            pp.PanelCurve = new PolyCurve { Curves = outlineElements1D.Cast<ICurve>().ToList() };
+            pp.ExternalEdges = outlineElements1D.Cast<ICurve>().ToList().ToEdges();
```
Comment (IsakNaslundBh) [inline Environment_Engine/Modify/SetOutlineElements1D.cs]: Same as above

File: Physical_Engine/Query/Thickness.cs [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+{
+    public static partial class Query
+    {
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+        [Description("BH.Engine.Physical.Query.Thickness => Returns the thickness of a generic construction")]
+        [Input("construction", "A generic Construction object")]
+        [Output("thickness", "The total thickness of the generic construction as a sum of all its layers")]
+        public static double Thickness(this IConstruction construction)
```
Comment (IsakNaslundBh) [inline Physical_Engine/Query/Thickness.cs]: This method should be called IThickness

Comment (FraserGreenroyd) [reply Physical_Engine/Query/Thickness.cs]: Done.

**Comment by michaldengusiak** [comment]
ok...I rebuild all again but this time BHoM is not loaded into Dynamo any more, I can see all correct folders in Packages 
All successful without any error when try to rebuild Dynamo only and as full BHoM ... ... I tested GH and works fine...  
image
image

**Comment by al-fisher** [comment]
> typing out the name of the method at the start of each description.
``` C# 
[Description("BH.Engine.Environment.Convert.ToPolyline => Returns a Polyline representation of an Environment Edge")]

```

I would agree with @IsakNaslundBh - can be something to be injected through Reflection_Engine if found useful. The text there as currently stands is duplication and something that would need to be maintained in parallel to the code which we need to avoid.

Thinking about this - I do like the idea of a **Verbose** mode for our UIs where full namespaces and/or additional context and info is provided for new or unfamiliar users! Similar to user settings in say GH where you can choose "Draw Full Names" or not:
image

**Comment by FraserGreenroyd** [comment]
@al-fisher done.
