### PR TITLE
Geometry_Engine: Methods now work for open polylines

### LINKED ISSUE #1207: Geometry_Engine: RemoveLeastSignificantVertices and RemoveShortSegments does not work for open polylines
#### Description:

The methods "RemoveLeastSignificantVertices" and "RemoveShortSegments" only works for closed polylines at the moment. Make them work for open polylines as well.

### PR DESCRIPTION
**Pull request by RasmusCanfjorden**
### Issues addressed by this PR

Closes #1207

### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Modify/RemoveLeastSignificantVertices_2019-10-14.gh?csf=1&e=qIGlV4
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Modify/RemoveShortSegments_2019-10-14.gh?csf=1&e=ohKfnB

### Changelog

* Enabled RemoveShortSegments to handle open polylines.
* Enabler RemoveLeastSignificantVertices to handle open polylines.

### CODE REVIEW

File: Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs [hunk 1]
```diff
@@ -41,43 +41,69 @@ public static partial class Modify
...
+                    else
+                        startIndex++; //Move onto the next point
+                }
+            }
+            else 
             {
-                Point first = pnts[startIndex];
-                Point second = pnts[(startIndex + 1) % pnts.Count];
-                Point third = pnts[(startIndex + 2) % pnts.Count];
+                while ((startIndex) < (pnts.Count - 1))
```
Comment (FraserGreenroyd) [inline Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs]: I do not believe that any of this `if` `else` is necessary - I believe the algorithm will work quite happily as it was for non-closed polylines as it did for closed polylines.

Alternatively, if the `if` `else` is necessary, then the `else` needs modifying to work with non-closed polylines, because currently that algorithm will loop to the beginning of the polyline unnecessarily (unnecessarily because the polyline is not closed so we don't need to loop to the beginning again).

File: Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs [hunk 2]
```diff
@@ -41,43 +41,69 @@ public static partial class Modify
...
+            if (!polyline.IsClosed())
+            {
+                if (pnts.Last() != originalPnts.Last())
+                {
+                    pnts.Remove(pnts.Last());
+                    pnts.Add(originalPnts.Last());
+                }
+            }
 
+            if (polyline.IsClosed()) //Only re-close if original polyline is closed
```
Comment (FraserGreenroyd) [inline Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs]: This can easily be an `else` rather than running a `IsClosed` check twice.

Comment (FraserGreenroyd) [inline Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs]: Use `else if(pnts.First() != pnts.Last())` to check the other bit in a single line.

File: Geometry_Engine/Modify/RemoveShortSegments.cs [hunk 3]
```diff
@@ -41,20 +41,16 @@ public static partial class Modify
...
-                BH.Engine.Reflection.Compute.RecordError("The RemoveShortSegments method is only for closed polylines and the input polyline is not closed.");
-                return polyline;
-            }
-
+        {            
             List<Point> pnts = polyline.DiscontinuityPoints();
+            List<Point> originalPnts = polyline.DiscontinuityPoints();
 
             if (pnts.Count < 3)
+            {
```
Comment (FraserGreenroyd) [inline Geometry_Engine/Modify/RemoveShortSegments.cs]: These brackets aren't needed, remove them

File: Geometry_Engine/Modify/RemoveShortSegments.cs [hunk 4]
```diff
@@ -67,17 +63,27 @@ public static Polyline RemoveShortSegments(this Polyline polyline, double minimu
...
+            if (!polyline.IsClosed())
+            {
+                if (pnts.Last() != originalPnts.Last())
+                {
+                    pnts.Remove(pnts.Last());
+                    pnts.Add(originalPnts.Last()); //Keep the original endpoint of the polyline                   
+                }
+            }
+
+            if (polyline.IsClosed())
```
Comment (FraserGreenroyd) [inline Geometry_Engine/Modify/RemoveShortSegments.cs]: See previous comment on the other method about using an `else` instead of two `IsClosed` checks

File: Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs [hunk 5]
```diff
@@ -41,20 +41,14 @@ public static partial class Modify
...
         public static Polyline RemoveLeastSignificantVertices(this Polyline polyline, double angleTolerance = Tolerance.Angle)
-        {
-            //This method is for closed polylines only at the moment
-            if (!polyline.IsClosed())
-            {
-                BH.Engine.Reflection.Compute.RecordError("The RemoveLeastSignificantVertices method is only for closed polylines and the input polyline is not closed.");
-                return polyline;
-            }
-
+        {
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs]: I think `distanceTolerance` should also be an argument of this method:
`public static Polyline RemoveLeastSignificantVertices(this Polyline polyline,, double distanceTolerance = Tolerance.Distance, double angleTolerance = Tolerance.Angle)`

File: Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs [hunk 6]
```diff
@@ -41,20 +41,14 @@ public static partial class Modify
...
-            //This method is for closed polylines only at the moment
-            if (!polyline.IsClosed())
-            {
-                BH.Engine.Reflection.Compute.RecordError("The RemoveLeastSignificantVertices method is only for closed polylines and the input polyline is not closed.");
-                return polyline;
-            }
-
+        {            
             List<Point> pnts = polyline.DiscontinuityPoints();
+            List<Point> originalPnts = polyline.DiscontinuityPoints();
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs]: The list is useless (plus duplicate of the above) - it could be `Point lastPoint = pnts.Last();`

File: Geometry_Engine/Modify/RemoveShortSegments.cs [hunk 7]
```diff
@@ -41,43 +41,44 @@ public static partial class Modify
...
         public static Polyline RemoveShortSegments(this Polyline polyline, double minimumSegmentLength = Tolerance.Distance)
-        {
-            //This method is for closed polylines only at the moment
-            if (!polyline.IsClosed())
-            {
-                BH.Engine.Reflection.Compute.RecordError("The RemoveShortSegments method is only for closed polylines and the input polyline is not closed.");
-                return polyline;
-            }
-
+        {
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/RemoveShortSegments.cs]: Same as above

File: Geometry_Engine/Modify/RemoveShortSegments.cs [hunk 8]
```diff
@@ -41,43 +41,44 @@ public static partial class Modify
...
-            //This method is for closed polylines only at the moment
-            if (!polyline.IsClosed())
-            {
-                BH.Engine.Reflection.Compute.RecordError("The RemoveShortSegments method is only for closed polylines and the input polyline is not closed.");
-                return polyline;
-            }
-
+        {            
             List<Point> pnts = polyline.DiscontinuityPoints();
+            List<Point> originalPnts = polyline.DiscontinuityPoints();
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/RemoveShortSegments.cs]: Same as above

File: Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs [hunk 9]
```diff
@@ -41,20 +41,14 @@ public static partial class Modify
...
-        {
-            //This method is for closed polylines only at the moment
-            if (!polyline.IsClosed())
-            {
-                BH.Engine.Reflection.Compute.RecordError("The RemoveLeastSignificantVertices method is only for closed polylines and the input polyline is not closed.");
-                return polyline;
-            }
-
+        {            
             List<Point> pnts = polyline.DiscontinuityPoints();
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs]: `DiscontinuityPoints` should pass both distance and angle tolerances

File: Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs [hunk 10]
```diff
@@ -67,8 +61,18 @@ public static Polyline RemoveLeastSignificantVertices(this Polyline polyline, do
                     startIndex++; //Move onto the next point
             }
 
-            if (pnts.First() != pnts.Last())
-                pnts.Add(pnts.First()); //Reclose polyline
+            if (!polyline.IsClosed())
+            {
+                if (pnts.Last() != originalPnts.Last())
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs]: This check is dangerous - the != operator does not take any tolerance into account, can imagine this being an issue. I would rather skip this line at all and replace the last point with the original last point `if (!polyline.IsClosed())`

File: Geometry_Engine/Modify/RemoveShortSegments.cs [hunk 11]
```diff
@@ -41,43 +41,44 @@ public static partial class Modify
...
                 if (first.Distance(second) <= minimumSegmentLength)
                     pnts.RemoveAt((startIndex + 1) % pnts.Count); //Delete the second point as it is too close to the first to produce any meaningful change...
                 else
                     startIndex++; //Move onto the next point
             }
 
-            if (pnts.First() != pnts.Last())
+            if (!polyline.IsClosed())
+            {
+                if (pnts.Last() != originalPnts.Last())
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/RemoveShortSegments.cs]: Same as above

File: Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs [hunk 12]
```diff
@@ -77,7 +81,8 @@ public static Polyline RemoveLeastSignificantVertices(this Polyline polyline, do
 
             return pLine;
         }
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs]: Please leave the blank line here

**Comment by FraserGreenroyd** [comment]
> I just realized: do these two methods not overlap with DiscontinuityPoints with tolerances set to values representing minimum angle and minimum segment length?

@pawelbaran we did discuss the subtle (and they are subtle) differences between this method and the `DiscontinuityPoints` when we first added `CleanPolyline` a few months ago - it was agreed this method gave us a cleaning ability that `DiscontinuityPoints` lacked so I think this point should be ok.

@RasmusCanfjorden please look into the other points @pawelbaran has raised though as, on reflection, I agree with a lot of them :smile:

**Comment by pawelbaran** [comment]
Happy to tick off one of the points then!
