### PR TITLE
Reflection_Engine: Record message when failing to load methods

### LINKED ISSUE #2001: Reflection_Engine: Show exception messages on failing to load methods
#### Description:

Error message should be recorded to give better insight into errors on loading methods

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2001 

Recording exception message when failing to load methods to give more detail of what is failing.

### CODE REVIEW

File: Reflection_Engine/Query/MethodList.cs [hunk 1]
```diff
@@ -124,9 +124,17 @@ private static void ExtractAllMethods()
...
                     }
                 }
-                catch (Exception)
+                catch (Exception e)
                 {
-                    Compute.RecordWarning("Cannot load types from assembly " + asm.GetName().Name);
+
+                    string message = "Cannot load types from assembly " + asm.GetName().Name + ". Exception message: " + e.Message;
+
+                    if (e.InnerException != null)
```
Comment (alelom) [inline Reflection_Engine/Query/MethodList.cs:132]: It feels safer if we do:
```suggestion
                    if (!string.IsNullOrEmpty(e.InnerException.Message))
```
because the exception message can be empty in some cases, where we would end up having a trailing `InnerException: ` text with nothing after it.

**Review by alelom — APPROVED** [review]
LGTM!

**Review by al-fisher — APPROVED** [review]
Agreed. Helpful already
LGTM.
