### PR TITLE
Spatial_Engine: Add Orient method for IElements

### LINKED ISSUE #2923: Spatial_Engine: Add Orient method to IElements
#### Description:

Requested in an offline chat by @ssiimmoonnee - should be as easy as chaining `GetGeometry`, `Orient` and `SetGeometry`?

### LINKED ISSUE #2925: Facade_Engine: Transform of FrameEdge not cloning FrameEdgeProperty properly
#### Description:

https://github.com/BHoM/BHoM_Engine/blob/4217ecc209564943abf36da932493268cf2eb284/Facade_Engine/Modify/Transform.cs#L58-L78

Does not clone the property, and is hence modifying the incoming object. Proper cloning to be done

#### Steps to reproduce:

Apply a transform that includes a rotational aspect to a FrameEdge object (or any other facade object, such as Panel/Opening). Continously applying the modifies the incoming object and hence causes weird and uncontrollable behaviour.

#### Expected behaviour:

For incoming object not to be changed, and outcoming object to get the proper transformation applied.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #2923
Closes #2925 

- Adds method for Orienting Elements.
- Fix cloning issue with facade FrameEdge

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/Eq_NayBBG7RNhDlbSgaQmD0BFSZdeP7w_QY68UITtETTnQ?e=QXSMRg

### Additional comments

Was debating with myself if providing null to from or to should default to world XY. That way it would be simpler to go from global to local, or vice versa. (not having to provide a global XY plane in one of the inputs). I opted out of it due to the Orient method in Geometry_Engine not behaving this way, but happy to change if we want to. @pawelbaran @al-fisher happy with comments on this.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

File: Spatial_Engine/Modify/Orient.cs [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+            {
+                Base.Compute.RecordError($"The {nameof(from)} coordinate system is null. Unable to orient the element.");
+                return null;
+            }
+
+            if (to == null)
+            {
+                Base.Compute.RecordError($"The {nameof(to)} coordinate system is null. Unable to orient the element.");
+                return null;
+
```
Comment (pawelbaran) [inline Spatial_Engine/Modify/Orient.cs:65]: one blank too much 😉

File: Spatial_Engine/Modify/Orient.cs [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+
+        [Description("Orients the element from one coordinate system to another.")]
+        [Input("element", "The element to orient.")]
+        [Input("from", "The cartesian coordinate system to orient from.")]
+        [Input("to", "The cartesian coordinate system to orient to.")]
+        [Output("element", "The reoriented element.")]
+        public static IElement Orient(this IElement element, Cartesian from, Cartesian to)
```
Comment (pawelbaran) [inline Spatial_Engine/Modify/Orient.cs:47]: I am thinking if it would not be worth defaulting both `to` and `from` to the global CS? Personally I would find it handy in some circumstances

Comment (pawelbaran) [reply Spatial_Engine/Modify/Orient.cs:47]: Just read the additional comments in PR description - great minds think alike! 😃

Comment (IsakNaslundBh) [reply Spatial_Engine/Modify/Orient.cs]: Done

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

File: Spatial_Engine/Modify/Orient.cs [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+
+        [Description("Orients the element from one coordinate system to another.")]
+        [Input("element", "The element to orient.")]
+        [Input("from", "The cartesian coordinate system to orient from. Deaults to global XY if nothing is provided.")]
+        [Input("to", "The cartesian coordinate system to orient to. Deaults to global XY if nothing is provided.")]
+        [Output("element", "The reoriented element.")]
+        public static IElement Orient(this IElement element, Cartesian from = null, Cartesian to = null)
```
Comment (pawelbaran) [inline Spatial_Engine/Modify/Orient.cs:47]: Personally I would consider adding a static `Cartesian.Global` or similar and defaulting `from` and `to` to that value. Now this method creates the risk of `null` being passed unnoticed, which is a no go for me I think.

Comment (IsakNaslundBh) [reply Spatial_Engine/Modify/Orient.cs:47]: there is not static one (otherwise I would have used it), can ofc switch to create one with standard axis though.

Also thought about the potential issue if the default values changed, but I have included all three null providing cases for coordinate system in the UT, so if it was ever changed, the UT would flag it.

If you still think that is to risky, can ofc update?

Comment (pawelbaran) [reply Spatial_Engine/Modify/Orient.cs:47]: I would create one, same as we have e.g. in `Basis.XY`. Not sure about the UT part, but I am thinking about a scenario where another method crashes and returns `null` and then it is picked by `Orient` and processed as if the input was valid - this is what I am afraid of.

Comment (IsakNaslundBh) [reply Spatial_Engine/Modify/Orient.cs:47]: Ah, I see. Not sure that is solvable from here though. Think the optional inputs need to be compile time constants, but will have a look.

Comment (pawelbaran) [reply Spatial_Engine/Modify/Orient.cs:47]: Ah, you are right, the coordinate system will not be constant compile time. In this case I am taking back my original suggestion - would rather be on the safe side than on the handy one.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by pawelbaran — APPROVED** [review]
Happy to approve following the review made and discussion successfully resolved 👍

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting a force check on: versioning

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check ready-to-merge
