### PR TITLE
Geometry_Engine: Adding descriptions to the Normal() methods

### LINKED ISSUE #2184: Geometry_Engine: Let Normal() calculate normals for open curves
#### Broken rules:

Inconsistent handling of checks in `Normal()` methods. (See #2180)

#### Suggestions to restore compliance:

Let `Normal()` calculate normals for open curves.

### PR DESCRIPTION
**Pull request by LMarkowski**
### Issues addressed by this PR

Closes #2184

Adding descriptions to all `Normal()` methods.

### Test files

Only the descriptions and arguments names are changed, however [here](https://burohappold.sharepoint.com/:f:/s/BHoM/Esd2eZj9Hc1Mkh5tar8m-NsBlIxJtyJ40zXatKwF4D3uOQ?e=2cGnWq) is the general tet file.

### Changelog

- Adding descriptions to all `Normal()` and `Normals()` methods in the `Geometry_Engine`.

### Additional comments

As this one concerns mostly descriptions, any suggestions from more experienced English speakers will be very welcomed 😉

### CODE REVIEW

File: Geometry_Engine/Query/Normal.cs [hunk 1]
```diff
@@ -35,6 +35,10 @@ public static partial class Query
         /**** Public Methods - Surfaces                 ****/
         /***************************************************/
 
+        [Description("Returns the normal vector to the specified face in the mesh.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Query/Normal.cs:38]:
```suggestion
        [Description("Returns a vector normal to a given face of the mesh.")]
```

File: Geometry_Engine/Query/Normal.cs [hunk 2]
```diff
@@ -35,6 +35,10 @@ public static partial class Query
...
+        [Input("face", "The Face to get the normal to.")]
+        [Input("mesh", "The Mesh containing the face to get the normal to.")]
+        [Output("normal", "The normal vector to the mesh's specified face.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Query/Normal.cs:41]:
```suggestion
        [Output("normal", "Vector normal to the given mesh face.")]
```

File: Geometry_Engine/Query/Normal.cs [hunk 3]
```diff
@@ -57,6 +61,9 @@ public static Vector Normal(this Face face, Mesh mesh)
 
         /***************************************************/
 
+        [Description("Returns the list of normal vectors to the mesh's faces.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Query/Normal.cs:64]:
```suggestion
        [Description("Returns the list of vectors normal to each face of the mesh.")]
```

File: Geometry_Engine/Query/Normal.cs [hunk 4]
```diff
@@ -57,6 +61,9 @@ public static Vector Normal(this Face face, Mesh mesh)
...
+        [Input("mesh", "The Mesh to get the normals to.")]
+        [Output("normals", "The List of normal vectors to the given mesh's faces.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Query/Normal.cs:66]:
```suggestion
        [Output("normals", "List of vectors normal to the faces of a given mesh.")]
```

File: Geometry_Engine/Query/Normal.cs [hunk 5]
```diff
@@ -87,6 +94,9 @@ public static List<Vector> Normals(this Mesh mesh)
 
         /***************************************************/
 
+        [Description("Returns the list of normal vectors to the mesh's faces.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Query/Normal.cs:97]:
```suggestion
        [Description("Returns the list of vectors normal to each face of the mesh.")]
```

File: Geometry_Engine/Query/Normal.cs [hunk 6]
```diff
@@ -87,6 +94,9 @@ public static List<Vector> Normals(this Mesh mesh)
...
+        [Input("mesh", "The Mesh3D to get the normals to.")]
+        [Output("normals", "The List of normal vectors to the given mesh's faces.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Query/Normal.cs:99]:
```suggestion
        [Output("normals", "List of vectors normal to the faces of a given mesh.")]
```

File: Geometry_Engine/Query/Normal.cs [hunk 7]
```diff
@@ -97,17 +107,20 @@ public static List<Vector> Normals(this Mesh3D mesh)
         /**** Public Methods - Curves                   ****/
         /***************************************************/
 
+        [Description("Returns the normal vector to the curve's plane, oriented according to the rigth hand rule. Works only for closed and planar curves.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Query/Normal.cs:110]: I would apply it here and to all other methods taking curves.
```suggestion
        [Description("Returns the normal vector to the plane of a given curve, oriented according to the right hand rule. Works only for closed, planar curves.")]
```

File: Geometry_Engine/Query/Normal.cs [hunk 8]
```diff
@@ -97,17 +107,20 @@ public static List<Vector> Normals(this Mesh3D mesh)
...
+        [Input("curve", "The Polyline to get the normal to.")]
+        [Input("tolerance", "Distance tolerance used in geometry processing, default set to BH.oM.Geometry.Tolerance.Distance.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Query/Normal.cs:112]: Not sure if we should refer to `BH.oM.Geometry.Tolerance.Distance` or to 1e-6? (refers to all methods that have `tolerance` parameter)

File: Geometry_Engine/Query/Normal.cs [hunk 9]
```diff
@@ -97,17 +107,20 @@ public static List<Vector> Normals(this Mesh3D mesh)
...
+        [Output("normal", "The normal vector to the curve's plane.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Query/Normal.cs:113]: Minor change, would sound cleared to me (applies to other methods too).
```suggestion
        [Output("normal", "The normal vector to the plane of a curve.")]
```

**Review by pawelbaran — COMMENTED** [review]
I am not a native speaker, but let myself do a quick check 🙊 Please see the code comments.

File: Geometry_Engine/Query/Normal.cs (hunk 8 above)
Comment (LMarkowski) [reply Geometry_Engine/Query/Normal.cs:112]: Had the same thought. It keeps as on the safe side, but isn't very useful for the end user.
It might a bit out of scope here but worth discussing anyway.
Having a permanent value in a string seems.. wrong. Maybe when we'll have the tolerance object we could somehow access it from the descriptions to set it dynamically?

Comment (pawelbaran) [reply Geometry_Engine/Query/Normal.cs:112]: Maybe we could consider `typeof(ToleranceAttribute)` that would extract the actual value when `BH.Engine.Reflection.Query.Description` gets called? @al-fisher @IsakNaslundBh

**Review by pawelbaran — COMMENTED** [review]
LGTM 👍  Although would be good to have an action plan regarding `tolerance` before this gets merged.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Needs an appropriate label before merge please.

File: Geometry_Engine/Query/Normal.cs (hunk 8 above)
Comment (FraserGreenroyd) [reply Geometry_Engine/Query/Normal.cs:112]: Convention is to use `BH.oM.Geometry.Tolerance.Distance` because that's what the actual default is set to. If we change the value of that tolerance in the oM, then we would have to go through and update all of the descriptions if we used the value `1e-6`.

Hovering over the input will also give the value (at least in Grasshopper, dunno about Dynamo/Excel) when it is an optional input.

**Review by FraserGreenroyd — APPROVED** [review]
All LGTM now on brief review.
