### PR TITLE
Geometry_Engine: Fix edgecase for Create PlanarSurface

### LINKED ISSUE #1841: Geometry_Engine: Create PlanarSurface issues
#### Description:

`Is NurbsCurve` does not catch a `NurbsCurve` in a `PolyCurve`.

and hence returns a error instead of a maybe good planarsurface when checking for selfIntersections

#### Test file(s):

https://burohappold.sharepoint.com/:u:/s/BHoM/EZJWg4ErMzRAo-geK8xMXvsBox24We9K-t0conW15dIDDg?e=ctmgh5

### PR DESCRIPTION
**Pull request by kThorsager**
### Issues addressed by this PR
Closes #1841 

The checks for creating a planarSurface don't work for PolyCurves based on Nurbs or Ellipses either.
This makes sure that they are ignored like the Nurbs and Ellipses, which means that they can be created.

### Test files

see issue

### CODE REVIEW

File: Geometry_Engine/Create/PlanarSurface.cs [hunk 1]
```diff
@@ -102,16 +102,16 @@ public static PlanarSurface PlanarSurface(ICurve externalBoundary, List<ICurve>
...
+                                .Concat(internalBoundaries.Where(x => x.ISubParts().All(y => !(y is NurbsCurve) && !(y is Ellipse))).BooleanUnion()).ToList();
 
             if (internalBoundaries.Count != count)
             {
                 Reflection.Compute.RecordWarning("At least one of the internalBoundaries was overlapping another one. BooleanUnion was used to resolve it.");
             }
 
             //--------------Unsupported-External-Boundary-------------------//
-            if (externalBoundary is NurbsCurve || externalBoundary is Ellipse)
+            if (externalBoundary.ISubParts().Any(x => x is NurbsCurve) || externalBoundary.ISubParts().Any(x => x is Ellipse))
```
Comment (pawelbaran) [inline Geometry_Engine/Create/PlanarSurface.cs:114]: It could be wrapped into a single `Any` query

File: Geometry_Engine/Create/PlanarSurface.cs [hunk 2]
```diff
@@ -123,7 +123,7 @@ public static PlanarSurface PlanarSurface(ICurve externalBoundary, List<ICurve>
             for (int i = 0; i < internalBoundaries.Count; i++)
             {
                 ICurve intCurve = internalBoundaries[i];
-                if (intCurve is NurbsCurve || intCurve is Ellipse)
+                if (intCurve.ISubParts().Any(x => x is NurbsCurve) || intCurve.ISubParts().Any(x => x is Ellipse))
```
Comment (pawelbaran) [inline Geometry_Engine/Create/PlanarSurface.cs:126]: It could be wrapped into a single `Any` query

File: Geometry_Engine/Create/PlanarSurface.cs [hunk 3]
```diff
@@ -139,7 +139,7 @@ public static PlanarSurface PlanarSurface(ICurve externalBoundary, List<ICurve>
             //---------------Contained-By-External-Boundary-----------------//
             count = internalBoundaries.Count;
 
-            internalBoundaries = internalBoundaries.Where(x => x is NurbsCurve || x is Ellipse || externalBoundary.IIsContaining(x)).ToList();
+            internalBoundaries = internalBoundaries.Where(x => x.ISubParts().Any(y => y is NurbsCurve )|| x.ISubParts().Any(y => y is Ellipse) || externalBoundary.IIsContaining(x)).ToList();
```
Comment (pawelbaran) [inline Geometry_Engine/Create/PlanarSurface.cs:142]: It could be wrapped into a single `Any` query
