### PR TITLE
Reflection_Engine: ExtensionMethodToCall isolated from RunExtensionMethod

### LINKED ISSUE #2328: Expose GetExtensionMethod as a separate method
#### Description:

While working on #2321, it turned out that in some cases it will be desirable to try to get the extension method before calling it (for example if  mentioned get fails, a private method could be called).

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #2328

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine%2F%232331%2DExtensionMethodToCall%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine) - it only proves that the mechanism used up to date still works - the benefits coming from this PR will be tested more explicitly in #2321.

### Changelog

- `ExtensionMethodToCall` method isolated from `RunExtensionMethod`

### Additional comments

What I do not like about the solution proposed in this PR is the fact that in case of execution failure the error message is missing the information about the method name. However, `Func<object[], object>` does not carry it any more, and StackOverflow says it would need to be wrapped into `Expression<T>`. Not sure if that is worth the extra complexity added to the code - happy to hear others' opinion on that.

### CODE REVIEW

**Comment by adecler** [comment]
> What I do not like about the solution proposed in this PR is the fact that in case of execution failure the error message is missing the information about the method name. However, `Func<object[], object>` does not carry it any more, and StackOverflow says it would need to be wrapped into `Expression<T>`. Not sure if that is worth the extra complexity added to the code - happy to hear others' opinion on that.

Why not having your `GetExtensionMethod` returning a MethodInfo instead ? It could just store a dictionary of `ConcurrentDictionary<Tuple<Type, string>, MethodInfo>`. And then, you have your `RunExtensionMethod` storing a `ConcurrentDictionary<MethodInfo, Func<object[], object>>` for those methods that have already been compiled. At this point, it could even be called just `RunMethod` as it has nothing to do with extensions methods anymore.

**Review by FraserGreenroyd — COMMENTED** [review]
PR title needs to specify which engine is being modified please :smile:

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Review by adecler — APPROVED** [review]
Looks good to me. Now it's just a question of making the bot happy 😄

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 1955310848

**Comment by adecler** [comment]
@FraserGreenroyd , `Query` methods should always start with a `this` on the first argument. I don't think we should ignore that.

File: Reflection_Engine/Query/ExtensionMethodToCall.cs [hunk 1]
```diff
@@ -0,0 +1,164 @@
...
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+        
+        [Description("Finds an extension method accepting a multiple argument based on a provided main object and method name.\n" +
+                     "The method is found via reflection at the first time it is queried, then it is stored for subsequent calls.")]
+        [Input("target", "First argument of the method to find.")]
+        [Input("methodName", "The name of the method to be sought.")]
+        [Output("method", "Most suitable extension method with requested target, name and parameters. If no method was found, null is returned.")]
+        public static MethodInfo ExtensionMethodToCall(object target, string methodName)
```
Comment (adecler) [inline Reflection_Engine/Query/ExtensionMethodToCall.cs:44]:
```suggestion
        public static MethodInfo ExtensionMethodToCall(this object target, string methodName)
```

File: Reflection_Engine/Query/ExtensionMethodToCall.cs [hunk 2]
```diff
@@ -0,0 +1,164 @@
...
+
+        /***************************************************/
+
+        [Description("Finds an extension method accepting a multiple argument based on a provided main object and method name and additional arguments.\n" +
+                     "The method is found via reflection at the first time it is queried, then it is stored for subsequent calls.")]
+        [Input("target", "First argument of the method to find.")]
+        [Input("methodName", "The name of the method to be sought.")]
+        [Input("parameters", "The additional arguments of the call to the method, skipping the first argument provided by 'target'.")]
+        [Output("method", "Most suitable extension method with requested target, name and parameters. If no method was found, null is returned.")]
+        public static MethodInfo ExtensionMethodToCall(object target, string methodName, object[] parameters)
```
Comment (adecler) [inline Reflection_Engine/Query/ExtensionMethodToCall.cs:57]:
```suggestion
        public static MethodInfo ExtensionMethodToCall(this object target, string methodName, object[] parameters)
```

**Review by adecler — CHANGES_REQUESTED** [review]
All good. Just need to make the `Query` methods compliant

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Review by adecler — APPROVED** [review]

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check installer
