### PR TITLE
Geometry_Engine - Fix SplitAtPoints() bugs and change output type

### LINKED ISSUE #1057: Geometry_Engine: SplitAtPoints(Circle) bug for empty point list
Also breaks when the input points do not lie on the circle. Maybe it would be good to change the return type from `List<Arc>` to `List<ICurve>` and return a circle when there is no splitting points?

### LINKED ISSUE #1058: Geometry_Engine: SplitAtPoints(Arc) bug when the angle of an arc == 360 deg.

### PR DESCRIPTION
**Pull request by LMarkowski**
Fixed the bug of splitting 360 degree arc and circle having no split points. Also changed `SplitAtPoints(Circle)` output type from `List<Arc>` to `Liast<ICurve.` to allow returning Arcs or Circles. It does not affect any other method

### Issues addressed by this PR

Closes #1057 
Closes #1058 

### Test files
[Here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%20%231057%20%231058%20%2D%20SplitAtPoints%28%29%20bugs) is the issue specific test and [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FModify) is regular test (nothing changed in a second one).

### Changelog
 - `Modify.SplitAtPoints()` Modify method updated in the `Geometry_Engine` for `Arc` class
 - `Modify.SplitAtPoints()` Modify method updated in the `Geometry_Engine` for `Circle` class

### CODE REVIEW

File: Geometry_Engine/Modify/SplitAtPoints.cs [hunk 1]
```diff
@@ -77,17 +80,16 @@ public static List<Arc> SplitAtPoints(this Arc arc, List<Point> points, double t
...
                 result.Add(arc.Clone());
-
             return result;
         }
 
         /***************************************************/
 
 
-        public static List<Arc> SplitAtPoints(this Circle circle, List<Point> points, double tolerance = Tolerance.Distance)
+        public static List<ICurve> SplitAtPoints(this Circle circle, List<Point> points, double tolerance = Tolerance.Distance)
```
Comment (FraserGreenroyd) [inline Geometry_Engine/Modify/SplitAtPoints.cs]: Can we double check if this needs deprecating rather than just updating? I know `Arc` is an `ICurve` so the scripts might tolerate it, but to be safe can you confirm scripts using the old component (returning a list of `Arc`) will still work with this change (to a list of `ICurve`)? If they don't then the original method will need deprecating.

**Comment by FraserGreenroyd** [comment]
FYI I have updated the PR title for the change log requirements :smile:

**Comment by pawelbaran** [comment]
@LMarkowski could you please reflect on the status of this PR, particularly with regard to method deprecation? Do you consider this one ready?

**Comment by LMarkowski** [comment]
@pawelbaran @FraserGreenroyd 
In Engine only `SplitAtPoints(PolyCurve)` uses `SplitAtPoints(Circle)`. It actually expects result as `List<Arc>` but only in case of existing split points, so when `SplitAtPoints(Circle)` in fact returns `List<Arc>`. It returns Circle only in case of no split points which is handled in `SplitAtPoints(PolyCurve)` in other way.
I checked all open source repos with code assistant and manually searched through ML_toolkit and everything looks fine. 
So, given that deprecating would be hard in this case, IMO it's ready to merge.

**Comment by LMarkowski** [comment]
@FraserGreenroyd do you want to add anything? 😃

**Comment by FraserGreenroyd** [comment]
If @pawelbaran  is happy then I'm happy and I'll remove my review now, sorry  for the delay :smile: @pawelbaran are you happy for this to be merged?

**Comment by FraserGreenroyd** [comment]
Discussed with @LMarkowski and am merging as @pawelbaran is absent for a few days :smile:
