### PR TITLE
Environment_Engine: Fix bug in MapToLevels

### LINKED ISSUE #1999: Environment_Engine: MapToLevels throws an error when a level is not found
And it's not a nice level. @rboulton-BH did not enjoy it.

Fix: Provide rooms which are not on a level as a separate output, with a warning that some rooms have not been mapped.

Fix: Spelling of documentation from incorrect (American) English to English (`Organize` => `Organise`).

Fix: MapToLevel should be working on spaces but does not.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #1999 

### Test files
[Download here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-%231999-MapToLevels/MapToLevel%20section.gh?csf=1&web=1&e=7jNoDW)

### Additional comments
Boom 2000th PR/Issue!

### CODE REVIEW

File: Environment_Engine/Compute/MapToLevel.cs [hunk 1]
```diff
@@ -41,16 +41,85 @@ namespace BH.Engine.Environment
...
-        [Input("rooms", "A collection of BHoM Rooms to be organized.")]
+        [Description("Organise the BHoM Space objects into a data structure based on the level of each space.")]
+        [Input("spaces", "A collection of BHoM Spaces to be organised.")]
         [Input("levels", "A collection of BHoM Levels.")]
         [Input("decimals", "Provide decimal location to define the degree of tolerance for data matching.")]
-        [MultiOutput(0, "roomsByLevel", "A collection of BHoM Rooms group by levels.")]
+        [MultiOutput(0, "spacesByLevel", "A collection of BHoM Spaces grouped by levels.")]
         [MultiOutput(1, "levelsInUse", "A sublist of the BHoM Levels that have Room.")]
-        public static Output<List<List<Room>>, List<oM.Geometry.SettingOut.Level>> MapToLevel(List<Room> rooms, List<oM.Geometry.SettingOut.Level> levels, int decimals = 6)
+        [MultiOutput(2, "spacesNotMapped", "A collection of BHoM Spaces which did not sit neatly on any of the provided levels")]
```
Comment (michaelhoehn) [inline Environment_Engine/Compute/MapToLevel.cs:50]: Could we also have a ```unusedLevels``` or ```levelsNotMapped``` output? Certainly could deduce this from the original list, but I think it helps explain what the method is doing.

File: Environment_Engine/Compute/MapToLevel.cs [hunk 2]
```diff
@@ -41,16 +41,85 @@ namespace BH.Engine.Environment
...
+            return output;
+        }
+
+        [Description("Organise the BHoM Room objects into a data structure based on the level of each room.")]
+        [Input("rooms", "A collection of BHoM Rooms to be organised.")]
+        [Input("levels", "A collection of BHoM Levels.")]
+        [Input("decimals", "Provide decimal location to define the degree of tolerance for data matching.")]
+        [MultiOutput(0, "roomsByLevel", "A collection of BHoM Rooms grouped by levels.")]
+        [MultiOutput(1, "levelsInUse", "A sublist of the BHoM Levels that have Room.")]
+        [MultiOutput(2, "roomsNotMapped", "A collection of BHoM Rooms which did not sit neatly on any of the provided levels")]
```
Comment (michaelhoehn) [inline Environment_Engine/Compute/MapToLevel.cs:117]: Same question as above.

**Review by michaelhoehn — APPROVED** [review]
Good stuff. Thanks @FraserGreenroyd!
