### PR TITLE
Facade_Engine: Added Facade GeneralMaterialTakeoff methods

### LINKED ISSUE #3091: Matter_Engine: IGeneralMaterialTakeoff does not return Area, Mass, etc
#### Description:
As it is currently set up, the IGeneralMaterialTakeoff method only returns the Volumetric Takeoff as it does not include:
`GeneralMaterialTakeoff(this Construction construction, double area)`
like the Physical Namespace GeneralMaterialTakeoff does.

Top error in the image below for Area=NaN for Element where Area method returns a valid value.
image

#### Steps to reproduce:
Try to get the GeneralMaterialTakeoff for any element not handled by the Physical method, and it will not return Takeoffs for things such as Area, even if the element input has a method for Area (eg any typical IElementM2d)

#### Expected behaviour:
All relevant material takeoffs returned, including things like Area for materials making up layers of a Facade Opening, for example.

#### Test file(s):
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Matter_Engine/%233091-GeneralMaterialTakeoff%20Volume%20Only?csf=1&web=1&e=cMNi3N

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #3091 

Added `GeneralMaterialTakeoff` methods for Facade namespace, so that takeoffs for these elements properly account for area and volumes.

### Test files
[Test File](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%233091-AreaTakeoffFix?csf=1&web=1&e=bPXCod)

To test, check the Panel, Opening, etc elements and confirm area takeoffs and LCA values work correctly for the Area EPD/material applied. 

### Additional comments
I have implemented this for Facade elements within Facade_Engine. Technically we could implement higher, but it seems to make sense with how @IsakNaslundBh has implemented this and others, allowing for specific approaches within namespaces as needed. It makes for a bit more redundant code, but allows for custom bits such as the implementation of opening area accounting for frame width required for Facade Openings.

### CODE REVIEW

File: Facade_Engine/Query/GeneralMaterialTakeoff.cs [hunk 1]
```diff
@@ -0,0 +1,177 @@
...
+
+            double openingAreas = 0;
+
+            List<GeneralMaterialTakeoff> takeoffs = new List<GeneralMaterialTakeoff>();
+
+            foreach (Opening opening in panel.Openings)
+            {
+                GeneralMaterialTakeoff openingTakeoff = opening.GeneralMaterialTakeoff();
+                if (openingTakeoff == null)
+                    return null;
```
Comment (FraserGreenroyd) [inline Facade_Engine/Query/GeneralMaterialTakeoff.cs:78]: Do you really want to return `null` for the whole panel if one opening returns a null material take off? Seems a bit unnecessary?

File: Facade_Engine/Query/GeneralMaterialTakeoff.cs [hunk 2]
```diff
@@ -0,0 +1,177 @@
...
+
+                takeoffs.Add(openingTakeoff);
+                openingAreas += opening.Area();
+
```
Comment (FraserGreenroyd) [inline Facade_Engine/Query/GeneralMaterialTakeoff.cs:82]:
```suggestion
```

File: Facade_Engine/Query/GeneralMaterialTakeoff.cs [hunk 3]
```diff
@@ -0,0 +1,177 @@
...
+            {
+                takeoffs.Add(GeneralMaterialTakeoff(edge));
+            }
+            takeoffs.Add(Physical.Query.IGeneralMaterialTakeoff(panel.Construction, panel.Area()));
+
+            return Matter.Compute.AggregateGeneralMaterialTakeoff(takeoffs);
+        }
+
+        /***************************************************/
+
```
Comment (FraserGreenroyd) [inline Facade_Engine/Query/GeneralMaterialTakeoff.cs:95]:
```suggestion
```

File: Facade_Engine/Query/GeneralMaterialTakeoff.cs [hunk 4]
```diff
@@ -0,0 +1,177 @@
...
+            {
+                takeoffs.Add(GeneralMaterialTakeoff(edge));
+            }
+            takeoffs.Add(Physical.Query.IGeneralMaterialTakeoff(opening.OpeningConstruction, opening.ComponentAreas().Item1));
+
+            return Matter.Compute.AggregateGeneralMaterialTakeoff(takeoffs);
+        }
+
+        /***************************************************/
+
```
Comment (FraserGreenroyd) [inline Facade_Engine/Query/GeneralMaterialTakeoff.cs:132]:
```suggestion
```

File: Facade_Engine/Query/GeneralMaterialTakeoff.cs [hunk 5]
```diff
@@ -0,0 +1,177 @@
...
+        /***************************************************/
+        /**** Public Methods - Interface                ****/
+        /***************************************************/
+
+        [Description("Gets the volumetric material takeoff from the IOpening.")]
+        [Input("opening", "The physical opening object to extract the volumetric material takeoff from.")]
+        [Output("genTakeoff", "The volumetric material takeoff for the opening, made of up the volume and materiality of the construction and surface area.")]
+        public static GeneralMaterialTakeoff IGeneralMaterialTakeoff(this IOpening opening)
+        {
+            return GeneralMaterialTakeoff(opening as dynamic);
```
Comment (FraserGreenroyd) [inline Facade_Engine/Query/GeneralMaterialTakeoff.cs:172]: You need a fall back method taking an `object` in case the cast fails to go to an existing method.

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Also please include engine being changed in the PR title 😉

**Review by adecler — COMMENTED** [review]
To the exception of the need for a fallback already mentioned by @FraserGreenroyd , the code looks sound. 

As for the functionality itself, it would be good to have someone that understand the inputs and outputs better to review this PR. For me, I stared at the text `Confirm Areas Exist for Layer Materials` with a big arrow pointing to a `NaN` wondering if that was normal 😋 (for those the mass was not null so was that enough?). 

image

**Comment by enarhi** [comment]
@adecler I'll have @vgreen-BH review for functionality, but yea, the NaN for the first material and value for the second is as expected since the first material corresponds to the frame edge which is not an area based element.

File: Facade_Engine/Query/GeneralMaterialTakeoff.cs (hunk 1 above)
Comment (enarhi) [reply Facade_Engine/Query/GeneralMaterialTakeoff.cs]: Fixed, replaced with continue

File: Facade_Engine/Query/GeneralMaterialTakeoff.cs (hunk 2 above)
Comment (enarhi) [reply Facade_Engine/Query/GeneralMaterialTakeoff.cs]: Removed.

File: Facade_Engine/Query/GeneralMaterialTakeoff.cs (hunk 4 above)
Comment (enarhi) [reply Facade_Engine/Query/GeneralMaterialTakeoff.cs:131]: Removed.

File: Facade_Engine/Query/GeneralMaterialTakeoff.cs (hunk 5 above)
Comment (enarhi) [reply Facade_Engine/Query/GeneralMaterialTakeoff.cs:170]: Fallback method added recording error with type and returning null.

File: Facade_Engine/Query/GeneralMaterialTakeoff.cs [hunk 6]
```diff
@@ -0,0 +1,189 @@
...
+                Engine.Base.Compute.RecordError($"The {nameof(GeneralMaterialTakeoff)} could not be queried as no {nameof(FrameEdgeProperty)} has been assigned to the {nameof(FrameEdge)}.");
+                return null;
+            }
+
+            VolumetricMaterialTakeoff volTakeoff = Matter.Create.VolumetricMaterialTakeoff(edge.MaterialComposition(), edge.SolidVolume());
+            
+            return Matter.Create.GeneralMaterialTakeoff(volTakeoff);
+        }
+
+
```
Comment (FraserGreenroyd) [inline Facade_Engine/Query/GeneralMaterialTakeoff.cs:160]:
```suggestion
```

File: Facade_Engine/Query/GeneralMaterialTakeoff.cs [hunk 7]
```diff
@@ -0,0 +1,189 @@
...
+        [Description("Gets the volumetric material takeoff from the IOpening.")]
+        [Input("opening", "The physical opening object to extract the general material takeoff from.")]
+        [Output("genTakeoff", "The general material takeoff for the opening, made of up the volume and materiality of the construction and surface area.")]
+        public static GeneralMaterialTakeoff IGeneralMaterialTakeoff(this IOpening opening)
+        {
+            return GeneralMaterialTakeoff(opening as dynamic);
+        }
+
+
```
Comment (FraserGreenroyd) [inline Facade_Engine/Query/GeneralMaterialTakeoff.cs:173]:
```suggestion
```

File: Facade_Engine/Query/GeneralMaterialTakeoff.cs [hunk 8]
```diff
@@ -0,0 +1,189 @@
...
+        /***************************************************/
+        /**** Private Methods - Fallbacks               ****/
+        /***************************************************/
+
+        [Description("Gets the volumetric material takeoff from the object.")]
+        [Input("obj", "The object to extract the material takeoff from.")]
+        [Output("genTakeoff", "The volumetric material takeoff for the opening, made of up the volume and materiality of the construction and surface area.")]
+        public static GeneralMaterialTakeoff GeneralMaterialTakeoff(this object obj)
```
Comment (FraserGreenroyd) [inline Facade_Engine/Query/GeneralMaterialTakeoff.cs:181]: This should be a `private` method per the comment and [convention](https://github.com/BHoM/BHoM_Engine/blob/develop/Geometry_Engine/Query/EndPoint.cs#L119).
```suggestion
        private static GeneralMaterialTakeoff GeneralMaterialTakeoff(this object obj)
```

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

File: Facade_Engine/Query/GeneralMaterialTakeoff.cs (hunk 8 above)
Comment (enarhi) [reply Facade_Engine/Query/GeneralMaterialTakeoff.cs]: Change made (oops)

**Review by FraserGreenroyd — APPROVED** [review]
On a code perspective, everything looks fine now, but will need functional review by @vgreen-BH before merging.

**Review by vgreen-BH — APPROVED** [review]
Tested using referenced test script and latest alpha. Script performs as expected.

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check required

**Comment by enarhi** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 14998198547

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge
