### PR TITLE
Geometry_Engine: Add full documentation to geometry engine

### LINKED ISSUE #3535: Geometry_Engine: Add full documentation to the Geometry_Engine
#### What is missing/incorrect?

The Geometry Engine is still missing a significant amount of descriptions for the methods. To get this remedied in relatively quick fashion, suggesting using cursor and claude to help find and fix the missing bits.

Getting the Geometry_Engine fully documented will help when developing it further, as no more documentation compliance issues should be flagged due to missing descriptions in a file you are modifying, that happens to have some older methods undocumented in it.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #3535

Using cursor and claud to help cover all the missing descriptions throughout the whole of the Geometry_Engine.

Ended up finding quite a massive amount of methods that was not yet documented, which all will be good to get handled.

Have not proof read every single line, but have glossed across all files to ensure the content is correct, and have not found any major issues. Had to revert a couple of small formatting failures made by claude, but a part from that it went really smoothly.

### Test files

Not required - this is only updating descriptions

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

File: Geometry_Engine/Compute/SkewLineProximity.cs [hunk 1]
```diff
@@ -34,6 +36,12 @@ public static partial class Compute
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Calculates the proximity parameters for two skew lines, returning the parameters along each line where they are closest.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Compute/SkewLineProximity.cs]:
```suggestion
        [Description("Calculates the proximity parameters for two skew lines, returning the parameters along each line where they are closest. Returns null in case of parallel lines.")]
```

File: Geometry_Engine/Create/Sphere.cs [hunk 2]
```diff
@@ -32,6 +35,10 @@ public static partial class Create
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Creates a Sphere with the specified center and radius.")]
+        [Input("centre", "The center point of the sphere.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Create/Sphere.cs]:
```suggestion
        [Description("Creates a Sphere with the specified centre and radius.")]
        [Input("centre", "The centre point of the sphere.")]
```

File: Geometry_Engine/Create/Torus.cs [hunk 3]
```diff
@@ -31,6 +34,13 @@ public static partial class Create
         /***************************************************/
         /**** Public Methods                            ****/
         /***************************************************/
+        
+        [Description("Creates a Torus with the specified center, axis, major radius, and minor radius.")]
+        [Input("centre", "The center point of the torus.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Create/Torus.cs]:
```suggestion
        [Description("Creates a Torus with the specified centre, axis, major radius, and minor radius.")]
        [Input("centre", "The centre point of the torus.")]
```

File: Geometry_Engine/Create/Torus.cs [hunk 4]
```diff
@@ -31,6 +34,13 @@ public static partial class Create
...
+        [Input("axis", "The axis vector defining the torus's orientation.")]
+        [Input("radiusMajor", "The major radius of the torus (distance from center to tube center).", typeof(Length))]
```
Comment (pawelbaran) [inline Geometry_Engine/Create/Torus.cs]:
```suggestion
        [Input("radiusMajor", "The major radius of the torus (distance from centre to tube centre).", typeof(Length))]
```

File: Geometry_Engine/Modify/CullDuplicate.cs [hunk 5]
```diff
@@ -38,9 +35,9 @@ public static partial class Modify
         /**** Public Methods                            ****/
         /***************************************************/
 
-        [Description("Removes duplicate lines from the collection")]
-        [Input("lines", "The nested collection of lines to cull duplicates from")]
-        [Output("lines", "A collection of lines with no duplicates")]
+        [Description("Removes duplicate lines from the collection.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/CullDuplicate.cs]:
```suggestion
        [Description("Removes duplicate lines from the collection. Lines are considered the same if both of their endpoints lie within tolerance distance from each other, regardless of line direction.")]
```

File: Geometry_Engine/Modify/CullDuplicate.cs [hunk 6]
```diff
@@ -38,9 +35,9 @@ public static partial class Modify
...
+        [Input("lines", "The nested collection of lines to cull duplicates from.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/CullDuplicate.cs:40]:
```suggestion
        [Input("lines", "The nested collection of lines to cull duplicates from.")]
        [Input("tolerance", "Maximum allowed distance between end points for the lines to be considered the same.", typeof(Length))]
```

File: Geometry_Engine/Modify/Extend.cs [hunk 7]
```diff
@@ -36,17 +37,17 @@ public static partial class Modify
...
-        [Input("curve", "Curve to extend")]
-        [Input("start", "Length of extension on the begining of a curve. Negative value will trim the curve")]
-        [Input("end", "Length of extension on the end of a curve. Negative value will trim the curve")]
-        [Input("tangentExtensions", "True - extends on tangent lines\nFalse - extends by curve's shape")]
-        [Output("curve", "Extended curve")]
+        [Description("Extends curve by given lengths.")]
+        [Input("curve", "Curve to extend.")]
+        [Input("start", "Length of extension on the begining of a curve. Negative value will trim the curve.", typeof(Length))]
+        [Input("end", "Length of extension on the end of a curve. Negative value will trim the curve.", typeof(Length))]
+        [Input("tangentExtensions", "True - extends on tangent lines\nFalse - extends by curve's shape.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Extend.cs:44]:
```suggestion
        [Input("tangentExtensions", "True - extends on tangent lines\nFalse - extends by curve's shape.")]
        [Input("tolerance", "Tolerance value used for geometry processing.", typeof(Length))]
```

File: Geometry_Engine/Modify/Extend.cs [hunk 8]
```diff
@@ -55,12 +56,12 @@ public static Line Extend(this Line curve, double start = 0.0, double end = 0.0,
...
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Extend.cs:64]:
```suggestion
        [Input("tangentExtensions", "True - extends on tangent lines\nFalse - extends by curve's shape.")]
        [Input("tolerance", "Tolerance value used for geometry processing.", typeof(Length))]
```

File: Geometry_Engine/Modify/Extend.cs [hunk 9]
```diff
@@ -101,12 +102,12 @@ public static ICurve Extend(this Arc curve, double start = 0.0, double end = 0.0
...
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Extend.cs:111]:
```suggestion
        [Input("tangentExtensions", "True - extends on tangent lines\nFalse - extends by curve's shape.")]
        [Input("tolerance", "Tolerance value used for geometry processing.", typeof(Length))]
```

File: Geometry_Engine/Modify/Extend.cs [hunk 10]
```diff
@@ -115,12 +116,12 @@ public static Circle Extend(this Circle curve, double start = 0.0, double end =
...
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Extend.cs:126]:
```suggestion
        [Input("tangentExtensions", "True - extends on tangent lines\nFalse - extends by curve's shape.")]
        [Input("tolerance", "Tolerance value used for geometry processing.", typeof(Length))]
```

File: Geometry_Engine/Modify/Extend.cs [hunk 11]
```diff
@@ -129,12 +130,12 @@ public static Ellipse Extend(this Ellipse curve, double start = 0.0, double end
...
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Extend.cs:141]:
```suggestion
        [Input("tangentExtensions", "True - extends on tangent lines\nFalse - extends by curve's shape.")]
        [Input("tolerance", "Tolerance value used for geometry processing.", typeof(Length))]
```

File: Geometry_Engine/Modify/Extend.cs [hunk 12]
```diff
@@ -196,12 +197,12 @@ public static Polyline Extend(this Polyline curve, double start = 0.0, double en
...
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Extend.cs:209]:
```suggestion
        [Input("tangentExtensions", "True - extends on tangent lines\nFalse - extends by curve's shape.")]
        [Input("tolerance", "Tolerance value used for geometry processing.", typeof(Length))]
```

File: Geometry_Engine/Modify/Extend.cs [hunk 13]
```diff
@@ -264,12 +265,12 @@ public static PolyCurve Extend(this PolyCurve curve, double start = 0.0, double
...
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Extend.cs:278]:
```suggestion
        [Input("tangentExtensions", "True - extends on tangent lines\nFalse - extends by curve's shape.")]
        [Input("tolerance", "Tolerance value used for geometry processing.", typeof(Length))]
```

File: Geometry_Engine/Modify/Invert.cs [hunk 14]
```diff
@@ -30,6 +32,9 @@ public static partial class Modify
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Returns the inverse of the given transformation matrix.")]
+        [Input("transform", "The transformation matrix to invert.")]
+        [Output("transform", "The inverted transformation matrix.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Invert.cs]:
```suggestion
        [Output("inverse", "The inverted transformation matrix.")]
```

File: Geometry_Engine/Modify/Inflate.cs [hunk 15]
```diff
@@ -30,6 +33,10 @@ public static partial class Modify
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Returns a new BoundingBox that is inflated by the specified amount in all directions.")]
+        [Input("box", "The bounding box to inflate.")]
+        [Input("amount", "The amount by which to inflate the bounding box in each direction.", typeof(Length))]
+        [Output("box", "A new BoundingBox with its minimum corner decreased and maximum corner increased by the specified amount along each axis.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Inflate.cs]:
```suggestion
        [Output("inflated", "A new BoundingBox with its minimum corner decreased and maximum corner increased by the specified amount along each axis.")]
```

File: Geometry_Engine/Modify/Normalise.cs [hunk 16]
```diff
@@ -32,6 +35,9 @@ public static partial class Modify
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Normalizes a Vector to unit length.")]
+        [Input("vector", "The Vector to normalize.")]
+        [Output("vector", "The normalized Vector with unit length.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Normalise.cs]:
```suggestion
        [Description("Normalises a Vector to unit length.")]
        [Input("vector", "The Vector to normalise.")]
        [Output("normalised", "The normalised Vector with unit length.")]
```

File: Geometry_Engine/Modify/Normalise.cs [hunk 17]
```diff
@@ -47,6 +53,9 @@ public static Vector Normalise(this Vector vector)
 
         /***************************************************/
 
+        [Description("Normalizes a Quaternion to unit length.")]
+        [Input("q", "The Quaternion to normalize.")]
+        [Output("quaternion", "The normalized Quaternion with unit length.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Normalise.cs]:
```suggestion
        [Description("Normalises a Quaternion to unit length.")]
        [Input("q", "The Quaternion to normalise.")]
        [Output("normalised", "The normalised Quaternion with unit length.")]
```

File: Geometry_Engine/Modify/Transpose.cs [hunk 18]
```diff
@@ -30,13 +33,19 @@ public static partial class Modify
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Calculates the transpose of a TransformMatrix.")]
+        [Input("transform", "The TransformMatrix to transpose.")]
+        [Output("matrix", "The transposed TransformMatrix.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Transpose.cs]:
```suggestion
        [Output("transposed", "The transposed TransformMatrix.")]
```

File: Geometry_Engine/Modify/Transpose.cs [hunk 19]
```diff
@@ -30,13 +33,19 @@ public static partial class Modify
...
         public static TransformMatrix Transpose(this TransformMatrix transform)
         {
             return new TransformMatrix { Matrix = transform.Matrix.Transpose() };
         }
 
         /***************************************************/
 
+        [Description("Calculates the transpose of a 2D matrix represented as a double array.")]
+        [Input("matrix", "The 2D matrix to transpose.")]
+        [Output("matrix", "The transposed matrix.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Transpose.cs]:
```suggestion
        [Output("transposed", "The transposed matrix.")]
```

File: Geometry_Engine/Query/Centre.cs [hunk 20]
```diff
@@ -32,6 +34,10 @@ public static partial class Query
         /**** Curves                                    ****/
         /***************************************************/
 
+        [Description("Gets the center Point of an Arc.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Query/Centre.cs]: Center vs centre everywhere

File: Geometry_Engine/Query/GetLineSegment.cs [hunk 21]
```diff
@@ -34,6 +36,10 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Gets the Line segment of a Polyline that contains the specified Point.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Query/GetLineSegment.cs]:
```suggestion
        [Description("Gets the Line segment of a Polyline that the specified Point lies on.")]
```

File: Geometry_Engine/Query/GetLineSegment.cs [hunk 22]
```diff
@@ -34,6 +36,10 @@ public static partial class Query
...
+        [Input("pline", "The Polyline to search for the containing segment.")]
+        [Input("pt", "The Point to find the containing segment for.")]
+        [Output("segment", "The Line segment that contains the Point, or an empty Line if no segment contains the Point.")]
         public static Line GetLineSegment(this Polyline pline, Point pt)
```
Comment (pawelbaran) [inline Geometry_Engine/Query/GetLineSegment.cs:43]: Out of scope of this PR, but shouldn't this method return `null` when the point does not lie on any segment? `new Line()` looks like a recipe for troubles imo.

File: Geometry_Engine/Query/MeshIntersections.cs [hunk 23]
```diff
@@ -33,14 +35,25 @@ public static partial class Query
...
 
+        [PreviousVersion("8.3", "BH.Engine.Geometry.Query.MeshIntersection(BH.oM.Geometry.Plane, BH.oM.Geometry.Mesh, System.Double)")]
+        [Description("Finds the intersection line between a Plane and a Mesh. Currently not implemented.")]
+        [Input("p", "The Plane to intersect with the Mesh.")]
+        [Input("mesh", "The Mesh to intersect with the Plane.")]
+        [Input("tolerance", "The tolerance for the intersection calculation.", typeof(Length))]
+        [Output("line", "The intersection Line between the Plane and Mesh.")]
         [NotImplemented]
-        public static Line MeshIntersection(this Plane p, Mesh mesh, double tolerance = Tolerance.Distance)
+        public static Line MeshIntersections(this Plane p, Mesh mesh, double tolerance = Tolerance.Distance)
```
Comment (pawelbaran) [inline Geometry_Engine/Query/MeshIntersections.cs:45]: Why `MeshIntersections` if there is only one line returned?

File: Geometry_Engine/Query/PointInRegion.cs [hunk 24]
```diff
@@ -33,6 +35,11 @@ public static partial class Query
         /**** Public Methods - Curves                   ****/
         /***************************************************/
 
+        [Description("Finds a Point that lies within the region defined by a closed curve.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Query/PointInRegion.cs]:
```suggestion
        [Description("Finds a semi-arbitrary Point that lies within the region defined by a closed curve.")]
```

File: Geometry_Engine/Query/PointInRegion.cs [hunk 25]
```diff
@@ -33,6 +35,11 @@ public static partial class Query
...
+        [Input("curve", "The closed ICurve defining the region.")]
+        [Input("acceptOnEdge", "Whether to accept points that lie on the edge of the region.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Query/PointInRegion.cs]:
```suggestion
        [Input("acceptOnEdge", "Whether a point that lies on the edge of the region is considered valid.")]
```

File: Geometry_Engine/Query/SamplePoints.cs [hunk 26]
```diff
@@ -32,6 +35,10 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Samples Points along a curve at regular distance intervals.")]
```
Comment (pawelbaran) [inline Geometry_Engine/Query/SamplePoints.cs]:
```suggestion
        [Description("Samples Points along a curve at regular distance intervals along the curve.")]
```

**Review by pawelbaran — COMMENTED** [review]
In general looks quite good, but I think there is still some space for improvement within the scope of this PR:
- output parameter names are often poor, in case of `Modify` methods they are usually the same as the input param name, while in `Query` it is often `result` - could probably be improved with another simple prompt to Cursor
- British vs American English - Cursor is enforcing US convention, at some point I gave up correcting these in my review
- maybe we could also try improving input parameter names, e.g. `q` => `quaternion`, `p` => `plane` etc.?
- we could also clean up the trailing blank lines, or at least not add more of them (saw this happening in a few files in this PR 😃)

I would actually try to give a shot to each of the above, in separate prompt/commit to have full visibility of what had changed - then should also be easy enough to review.

File: Geometry_Engine/Query/GetLineSegment.cs (hunk 22 above)
Comment (IsakNaslundBh) [reply Geometry_Engine/Query/GetLineSegment.cs:43]: Yes, it should. We should raise an Issue for that I guess

File: Geometry_Engine/Query/MeshIntersections.cs (hunk 23 above)
Comment (IsakNaslundBh) [reply Geometry_Engine/Query/MeshIntersections.cs:45]: well, method not implemented - should be list of lines/polylines for the general case. Could jsut delete it, but..

File: Geometry_Engine/Query/GetLineSegment.cs (hunk 22 above)
Comment (IsakNaslundBh) [reply Geometry_Engine/Query/GetLineSegment.cs:43]: Issue raised https://github.com/BHoM/BHoM_Engine/issues/3541

**Comment by IsakNaslundBh** [comment]
@pawelbaran thanks for the review!

I have committed all of your suggestions, and also run the additional prompts you suggested, except for the one regarding parameter names. As discussed offline, this has slightly more potential of breaking things, as the UI for some cases relies on the parameter names of lacing when it deserialises the components in for example grasshopper. This can be dealt with by the use of the PreviousInputName attribute, but feels like scope is growing a bit much, so rather do that separately if we are to do that.

Anyway, hope those last changes look ok, and we can get this in! :)

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Review by pawelbaran — COMMENTED** [review]
I would be OK with merging the PR as is, but looking at it, maybe we could give it one last push and ask Cursor to add missing input attributes too? So that we could cut down documentation compliance messages to zero?

Code compliance check failure I am not concerned about at all, would just dismiss it as irrelevant in the context of this PR.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check documentation-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required
@BHoMBot check compliance

**Review by pawelbaran — DISMISSED** [review]
Delighted to approve after bringing the documentation compliance message count to zero 💪

**Review by pawelbaran — APPROVED** [review]
Re-approving after usings got tweaked

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 48985447385

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge
