### PR TITLE
Fix descriptions for various 

### LINKED ISSUE #3527: BHoM_Engine: Fix descriptions and puncutation through all engines
#### Suggestions to restore compliance:

Fix any spelling or grammatical errors in the `Input`, `Output` and `Description` attributes.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #3527 

### Test files

By inspection.

### Changelog

- Updated descriptions for various projects across BHoM_Engine.

### CODE REVIEW

**Review by pawelbaran — DISMISSED** [review]
Changes make sense, happy to approve

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Review by pawelbaran — DISMISSED** [review]
Changes make sense, happy to approve

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

File: Analytical_Engine/Modify/SetOutlineElements1D.cs [hunk 1]
```diff
@@ -42,14 +41,12 @@ public static partial class Modify
 
         [Description("Sets the Outline Element1Ds of an opening, i.e. the Edges of an Opening. Method required for all IElement2Ds.")]
         [Input("opening", "The Opening to update the Edges of.")]
-        [Input("edges", "A list of IElement1Ds which all should be of a type of Edge accepted by the Opening or Geometrical ICurve. \n" +
-                "ICurve will default the outlines properties.")]
+        [Input("edges", "A list of IElement1Ds which all should be of a type of Edge accepted by the Opening or Geometrical ICurve. \n" + "ICurve will default the outlines properties.")]
```
Comment (pawelbaran) [inline Analytical_Engine/Modify/SetOutlineElements1D.cs]: I can see that multiline comments got squashed into a single line as a part of this PR, which to me feels a bit less readable. Is there a chance we could enforce the BHoM convention (i.e. how multiline descriptions look on `develop`) to the LLM?

File: Analytical_Engine/Modify/SetOutlineElements1D.cs [hunk 2]
```diff
@@ -58,57 +55,51 @@ public static IOpening<TEdge> SetOutlineElements1D<TEdge>(this IOpening<TEdge> o
...
                 if (!joinedCurves.First().IIsClosed())
                     Engine.Base.Compute.RecordWarning("The outline elements assigned to the region do not form a closed loop.");
-
                 r.Perimeter = joinedCurves.First();
             }
             else
             {
                 Engine.Base.Compute.RecordWarning("The outline elements assigned to the region are disjointed.");
-                r.Perimeter = new PolyCurve { Curves = outlineElements.Cast<ICurve>().ToList() };
+                r.Perimeter = new PolyCurve{Curves = outlineElements.Cast<ICurve>().ToList()};
```
Comment (pawelbaran) [inline Analytical_Engine/Modify/SetOutlineElements1D.cs]: I noticed that spaces get squashed in constructors with property assignment, which is against the usual convention (as well as VS settings). Is there a chance we could formalise it in LLM formatting rules and rerun the refactor?

File: Analytical_Engine/Query/Geometry.cs [hunk 3]
```diff
@@ -117,15 +112,11 @@ public static IGeometry Geometry(this BH.oM.Analytical.Elements.ISurface surface
         [Input("mesh", "Analytical IMesh to get the mesh geometry from.")]
         [Output("mesh", "The geometry of the IMesh as a geometrical Mesh.")]
         public static Mesh Geometry<TNode, TFace>(this IMesh<TNode, TFace> mesh)
-            where TNode : INode
-            where TFace : IFace
+            where TNode : INode where TFace : IFace
```
Comment (pawelbaran) [inline Analytical_Engine/Query/Geometry.cs]: This also feels a bit less readable to me

File: Data_Engine/Create/Node.cs [hunk 4]
```diff
@@ -34,86 +34,71 @@ namespace BH.Engine.Data
...
+            where TNode : INode<T>
         {
             treeDegree = Math.Max(treeDegree, 2);
-
-            Func<IEnumerable<TNode>, IEnumerable<IEnumerable<TNode>>> partitionMethod =
-                (data) =>
+            Func<IEnumerable<TNode>, IEnumerable<IEnumerable<TNode>>> partitionMethod = (data) =>
+            {
+                List<List<TNode>> subLists = new List<List<TNode>>()
+                {data.ToList()};
```
Comment (pawelbaran) [inline Data_Engine/Create/Node.cs]: These 2 lines look a bit awkward

File: Geometry_Engine/Create/Plane.cs [hunk 5]
```diff
@@ -75,26 +71,14 @@ public static Plane RandomPlane(int seed = -1, BoundingBox box = null)
...
         [Input("box", "Optional containing box. The origin created will be limited to the bounding box. If no box is provided, values between 0 and 1 will be used when generating properties for the geometry.")]
         [Output("plane", "The generated random Plane.")]
         public static Plane RandomPlane(Random rnd, BoundingBox box = null)
         {
-            return new Plane
-            {
-                Origin = RandomPoint(rnd, box),
-                Normal = RandomVector(rnd).Normalise()
-            };
+            return new Plane{Origin = RandomPoint(rnd, box), Normal = RandomVector(rnd).Normalise()};
```
Comment (pawelbaran) [inline Geometry_Engine/Create/Plane.cs]: nooooo

**Review by pawelbaran — COMMENTED** [review]
The changes are great in general, really happy to see how this improves the quality of descriptions. However, it looks like the LLM follows a few weird formatting rules, the most horrible one being squashing spaces in property assignment:

From:
```C#
var obj1 = new MyClass { A = a, B = b, C = c };
var obj2 = new MyClass
{
    A = a,
    B = b,
    C = c
};
```

To:
```C#
var obj1 = new MyClass{A = a, B = b, C = c};
var obj2 = new MyClass{A = a, B = b, C = c};
```

...I would argue we should rather pick one of the two originally used convention, the new one looks really untidy (the only worse thing that comes to my mind is js formatting 😃)

But ofc this is all personal preference, so happy to be outvoted

File: Geometry_Engine/Create/Plane.cs (hunk 5 above)
Comment (jamesramsden-bh) [reply Geometry_Engine/Create/Plane.cs]: I agree, the multiline variant is much more readable

File: Analytical_Engine/Modify/SetOutlineElements1D.cs (hunk 1 above)
Comment (peterjamesnugent) [reply Analytical_Engine/Modify/SetOutlineElements1D.cs]: Agreed, we can can generate those.

File: Analytical_Engine/Modify/SetOutlineElements1D.cs (hunk 2 above)
Comment (peterjamesnugent) [reply Analytical_Engine/Modify/SetOutlineElements1D.cs]: Agree the spaced out version looks better, this has been remedied.

File: Analytical_Engine/Query/Geometry.cs (hunk 3 above)
Comment (peterjamesnugent) [reply Analytical_Engine/Query/Geometry.cs]: Agree, split by line.

File: Data_Engine/Create/Node.cs (hunk 4 above)
Comment (peterjamesnugent) [reply Data_Engine/Create/Node.cs]: Treated this the same as the constructors as above.

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
> The changes are great in general, really happy to see how this improves the quality of descriptions. However, it looks like the LLM follows a few weird formatting rules, the most horrible one being squashing spaces in property assignment:
> 
> From:
> 
> ```cs
> var obj1 = new MyClass { A = a, B = b, C = c };
> var obj2 = new MyClass
> {
>     A = a,
>     B = b,
>     C = c
> };
> ```
> 
> To:
> 
> ```cs
> var obj1 = new MyClass{A = a, B = b, C = c};
> var obj2 = new MyClass{A = a, B = b, C = c};
> ```
> 
> ...I would argue we should rather pick one of the two originally used convention, the new one looks really untidy (the only worse thing that comes to my mind is js formatting 😃)
> 
> But ofc this is all personal preference, so happy to be outvoted

For this, I actually dont think the issue is the LLMs, but rather the "add punctuation" action by the bot. See this commit:
https://github.com/BHoM/BHoM_Engine/pull/3528/commits/1215f8c5fcd10170ffef34276fa2b3e4936ba2de

We should probably just turn that action off.

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Review by IsakNaslundBh — APPROVED** [review]
Happy with all description updates in this PR, and also happy that there are no unintended code formatting changes from the bot action.

**Comment by IsakNaslundBh** [comment]
I resolved all conversations as all issues seemed to come from the "fix punctuation" action, and all gone after commits reverted.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge
