### PR TITLE
BHoM_Engine: Exclude SpecialName methods from BhoMMethodList

### LINKED ISSUE #3461: Remove event adders as well as property getters and setters from the BHoM method list
#### Description:

The BHoMMethodList currently contains a few methods relating to event adders and removers as well as static proeprty getters and setters. They should nto be part of the BHoMMethodList, but filtered out on extraction.

using the `method.IsSpecialName;` proeprty should help with this. Essentially, methods should only be added if this property is false.

#### Steps to reproduce:

Check the BHoMMethodList for any inclusion of adders and removers like:

Void remove_EventRecorded(System.EventHandler`1[BH.oM.Base.Debugging.Event])
Void add_EventRecorded(System.EventHandler`1[BH.oM.Base.Debugging.Event])

#### Expected behaviour:

For only "real" methods to be part of the BHoM Method list

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #3461 

Explude `IsSpecialName` from being added to the BHoMMethodList. This excludes Proeprty get and sets, from Properties in the engine. Also excludes Add and Remove methods for events.

This relates to these PRs:
https://github.com/BHoM/Versioning_Toolkit/pull/276
https://github.com/BHoM/Versioning_Toolkit/pull/281

### Test files

Run the testscript on develop, internalise the results, then re-run on branch and check that the items removed make sense. @pawelbaran quite a few Revit types flagged, so good to make sure you are happy with the removal of them, and that they are not required to be in the BHoMMethod list for anything revit-related (assume not, but want to double check)

[Test script on sharepoint](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/BHoM_Engine/%233464-RemoveEventAndPropertyMethodsFromBHomMethodList?csf=1&web=1&e=DGvj7o)

### CODE REVIEW

File: BHoM_Engine/Compute/ExtractAssembly.cs [hunk 1]
```diff
@@ -164,7 +164,7 @@ private static void ExtractMethods(Assembly asm)
                         // Get only the BHoM methods
                         if (!type.IsInterface && type.IsAbstract)
                         {
-                            foreach (MethodInfo info in type.GetMethods(bindingBHoM).Where(x => x.IsLegal()))
+                            foreach (MethodInfo info in type.GetMethods(bindingBHoM).Where(x => x.IsLegal() && !x.IsSpecialName))
```
Comment (pawelbaran) [inline BHoM_Engine/Compute/ExtractAssembly.cs:167]: Thinking about it, shouldn't the check against `IsSpecialName` be a part of `IsLegal`?

Comment (IsakNaslundBh) [reply BHoM_Engine/Compute/ExtractAssembly.cs:167]: Thought about that as well, but had a look at the IsLegal method, and seems that was a method added by myself a long time ago to protect against a complete crash. Not sure if I want to involve the IsSpecialName in that half mess, as ideally, the IsLegal should not even be there/required.

Might be able to be convinced otherwise, but that was my thought process at least.

Comment (pawelbaran) [reply BHoM_Engine/Compute/ExtractAssembly.cs:167]: Following the conversation with @adecler and @IsakNaslundBh, let's keep the code as is now 👍

**Review by pawelbaran — APPROVED** [review]
Changes make sense, happy to approve
