### PR TITLE
Structure_Engine: Add descriptions to query methods

### LINKED ISSUE #1182: Structure_Engine: Query methods documentation
#### Describe the documentation issue:
- [ ] Various methods are not documented

#### What is missing/incorrect?
Code attributes are missing from methods in the Query folder of the Structure_Engine.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #1182 

More or less all Query methods have added Descriptions and quantities (where applicable).

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@FraserGreenroyd @awakeman is the input name checker getting confused by my quantity attributes? Think the three now failing are correct.

File: Structure_Engine/Query/DistributedPoints.cs [hunk 1]
```diff
@@ -33,20 +37,32 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
-        public static List<Point> DistributedPoints(Bar bar, int divisions, double startLength = 0, double endLength = 0)
+        [Description("Gets a list of evenly distributed points along a bar from a given number of dividsions")]
+        [Input("bar", "The bar to get division points for")]
+        [Input("divisions", "Number of segments to divide the bar into. The number of points returned will be divisions +1.")]
+        [Input("startLength", "Optional offset from bar start node to start of divisions.", typeof(Length))]
+        [Input("startLength", "Optional offset from bar end node to start of divisions.", typeof(Length))]
```
Comment (FraserGreenroyd) [inline Structure_Engine/Query/DistributedPoints.cs]: I feel like this one is meant to be `endLength`?

Comment (IsakNaslundBh) [reply Structure_Engine/Query/DistributedPoints.cs]: you feel correctly!

Comment (IsakNaslundBh) [reply Structure_Engine/Query/DistributedPoints.cs]: another one to check? That we do not have two inputs with the same name?

Comment (FraserGreenroyd) [reply Structure_Engine/Query/DistributedPoints.cs]: Could add it to the list, are you ok raising an issue for it @IsakNaslundBh on Test_TK? :smile:

**Comment by FraserGreenroyd** [comment]
@IsakNaslundBh compliance checks have been updated to fix the issues you found during this PR, so any future check compliance failures should now be investigated again. It's passing as of this comment, depending on your next commits :smile:

File: Structure_Engine/Query/Elements0D.cs [hunk 2]
```diff
@@ -32,6 +36,9 @@ public static partial class Query
         /****            IElement1D            ****/
         /******************************************/
 
+        [Description("Gets the Element0Ds of a Bar, which for the case of a Bar means getting the start and the end Node. Method necessary for IElement pattern.")]
+        [Input("bar", "The bar to extract IElement0ds from")]
+        [Output("element0Ds","The list of element0ds of the bar, basically the start and end nodes.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Elements0D.cs]: Element0ds 
i.e. instead of basically

File: Structure_Engine/Query/EmbodiedCarbon.cs [hunk 3]
```diff
@@ -30,13 +34,19 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Calculates the total amount of embodied carbon of a Bar by taken the mass of the bar (as section area*length*density) times the EmbodiedCarbon value of the material")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/EmbodiedCarbon.cs]: Calculates the total amount of embodied carbon of a Bar by getting the mass of the bar (as section area*length*density) multiplied by the EmbodiedCarbon value of the material

File: Structure_Engine/Query/EmbodiedCarbon.cs [hunk 4]
```diff
@@ -30,13 +34,19 @@ public static partial class Query
...
+        [Input("bar", "The Bar to get the total embodied carbon from")]
+        [Output("emobodiedCarbon","The total embodied carbon of the bar", typeof(Mass))]
         public static double EmbodiedCarbon(this Bar bar)
         {
             return bar.Mass() * bar.SectionProperty.Material.EmbodiedCarbon;
         }
 
         /***************************************************/
 
+        [Description("Calculates the total amount of embodied carbon of a Panel by taken the mass of the panel (as area*thickness*density) times the EmbodiedCarbon value of the material")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/EmbodiedCarbon.cs]: Calculates the total amount of embodied carbon of a Panel by getting the mass of the Panel (as area*thickness*density) multiplied by the EmbodiedCarbon value of the material

File: Structure_Engine/Query/EmbodiedCarbon.cs [hunk 5]
```diff
@@ -30,13 +34,19 @@ public static partial class Query
...
+        [Input("panel", "The Panel to get the total embodied carbon from")]
+        [Output("emobodiedCarbon", "The total embodied carbon of the panel", typeof(Mass))]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/EmbodiedCarbon.cs]: embodiedCarbon

File: Structure_Engine/Query/Extrude.cs [hunk 6]
```diff
@@ -38,6 +42,10 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Generates a extrusion of the section along the bar centreline.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Extrude.cs]: Computes
an
Bar

File: Structure_Engine/Query/Extrude.cs [hunk 7]
```diff
@@ -38,6 +42,10 @@ public static partial class Query
...
+        [Input("bar", "The bar to get an extruded shape from. This required the proeprty of the bar do be of a type with a section profile.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Extrude.cs]: The Bar to get an extruded shape from. This requires the property of the Bar to be of a type with a section profile.

File: Structure_Engine/Query/Geometry.cs [hunk 8]
```diff
@@ -37,34 +39,49 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Gets the geometry of a Node as a point. Method required for automatic display in UI packages.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Geometry.cs]: Point

File: Structure_Engine/Query/Geometry.cs [hunk 9]
```diff
@@ -37,34 +39,49 @@ public static partial class Query
...
+        [Input("node", "Node to get the point geometry from")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Geometry.cs]: Node to get the Point from

File: Structure_Engine/Query/Geometry.cs [hunk 10]
```diff
@@ -37,34 +39,49 @@ public static partial class Query
...
+        [Output("point", "The geometry of the node as its position")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Geometry.cs]: The geometry of the Node

File: Structure_Engine/Query/Geometry.cs [hunk 11]
```diff
@@ -37,34 +39,49 @@ public static partial class Query
...
+        [Input("edge", "Edge to get the curve geometry from")]
+        [Output("curve", "The geometry of the Edge as its Curve")]
         public static ICurve Geometry(this Edge edge)
         {
             return edge.Curve;
         }
 
         /***************************************************/
 
+        [Description("Gets the geometry of a Structural surface as its geometrical 'centre plane' location surface. Method required for automatic display in UI packages.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Geometry.cs]: Gets the geometry of a structural Surface at it's centre. Method required for automatic display in UI packages.

File: Structure_Engine/Query/Geometry.cs [hunk 12]
```diff
@@ -37,34 +39,49 @@ public static partial class Query
...
+        [Input("surface", "Structural surface to get the geometrical surface geometry from")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Geometry.cs]: Surface
Surface

File: Structure_Engine/Query/Geometry.cs [hunk 13]
```diff
@@ -37,34 +39,49 @@ public static partial class Query
...
+        [Output("surface", "The geometry of the structural Surface as its 'centre plane' geometrical surface")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Geometry.cs]: The geomtry of the structural Sufarce at it's centre.

File: Structure_Engine/Query/Geometry.cs [hunk 14]
```diff
@@ -37,34 +39,49 @@ public static partial class Query
...
         public static IGeometry Geometry(this Surface surface)
         {
             return surface.Extents;
         }
 
         /***************************************************/
 
+        [Description("Gets the geometry of a Panel as a geometrical 'centre plane' planar surface. Method required for automatic display in UI packages.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Geometry.cs]: as above

File: Structure_Engine/Query/Geometry.cs [hunk 15]
```diff
@@ -37,34 +39,49 @@ public static partial class Query
...
+        [Input("panel", "Panel to get the planar surface geometry from")]
+        [Output("surface", "The geometry of the Panel as its 'centre plane' geometrical surface")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Geometry.cs]: as above

File: Structure_Engine/Query/Geometry.cs [hunk 16]
```diff
@@ -97,20 +117,26 @@ public static IGeometry Geometry(this SteelSection section)
 
         /***************************************************/
 
+        [Description("Gets the geometry of a GeometricalSEction as its profile outlines the global XY plane. Method required for automatic display in UI packages.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Geometry.cs]: GeometricalSection

File: Structure_Engine/Query/Geometry.cs [hunk 17]
```diff
@@ -163,6 +192,9 @@ public static Mesh Geometry(this FEMesh feMesh)
         /**** Public Methods - Interface                ****/
         /***************************************************/
 
+        [Description("Gets the geometry of a SectionProeprty, generally as its profile outlines the global XY plane. Method required for automatic display in UI packages.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Geometry.cs]: SectionProperty

File: Structure_Engine/Query/HasModifiers.cs [hunk 18]
```diff
@@ -0,0 +1,76 @@
...
+            foreach (double modifier in modifiers)
+            {
+                if (modifier != 1) return true;
+            }
+            return false;
+        }
+
+        /***************************************************/
+
+        [Description("Checks if a section property has any modifiers by first checking if any modifiers has been assigned, and if any of them are set to a value different than 1")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/HasModifiers.cs]: SectionProperty

File: Structure_Engine/Query/HasModifiers.cs [hunk 19]
```diff
@@ -0,0 +1,76 @@
...
+
+namespace BH.Engine.Structure
+{
+    public static partial class Query
+    {
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+
+        [Description("Checks if a surface property has any modifiers by first checking if any modifiers has been assigned, and if any of them are set to a value different than 1")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/HasModifiers.cs]: SurfaceProperty

File: Structure_Engine/Query/InternalElements2D.cs [hunk 20]
```diff
@@ -32,16 +35,24 @@ public static partial class Query
...
+        [Description("Gets inner IElement2Ds from an Opening. Method required for all IElement2Ds. \n" + 
+                     "As an opening does not contain any internal elements, this will always return an empty list.")]
+        [Input("opening","The Opening to get internal IElement2Ds from.")]
+        [Output("elements", "Inner elements. This will always be an empty list for openings.")]
         public static List<IElement2D> InternalElements2D(this Opening opening)
         {
             return new List<IElement2D>();
         }
 
         /***************************************************/
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/InternalElements2D.cs]: What's the point of this method if it is just returning a new `List<IElement2D>()`?

File: Structure_Engine/Query/IsConstrained.cs [hunk 21]
```diff
@@ -30,6 +33,9 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Method checks if a Node as a support assigned")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/IsConstrained.cs]: has a

File: Structure_Engine/Query/IsConstrained.cs [hunk 22]
```diff
@@ -30,6 +33,9 @@ public static partial class Query
...
+        [Input("node","The Node to check")]
+        [Output("isConstrained", "Returns true if the support of the Node is not null.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/IsConstrained.cs]: Returns true is the Node has a support assigned

File: Structure_Engine/Query/IsValidStructural.cs [hunk 23]
```diff
@@ -36,7 +36,9 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
-        [Description("Checks if a material contains a structural material fragment")]
+        [Description("Checks if a physical material contains exactly one structural material fragment, i.e. checks if the material contains structural data.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/IsValidStructural.cs]: Material Material Material

File: Structure_Engine/Query/IsValidStructural.cs [hunk 24]
```diff
@@ -36,7 +36,9 @@ public static partial class Query
...
+        [Input("material", "The physical material to check")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/IsValidStructural.cs]: Material

File: Structure_Engine/Query/IsVertical.cs [hunk 25]
```diff
@@ -35,6 +35,10 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Checks if a bar is vertical. A bar is vertical if its projected length to the horizontal plane is less than 0.0001, i.e. a tolerance of 0.1mm on verticality. \n" +
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/IsVertical.cs]: Bar Bar

File: Structure_Engine/Query/IsVertical.cs [hunk 26]
```diff
@@ -35,6 +35,10 @@ public static partial class Query
...
+                     "For general structural conventions please see  https://github.com/BHoM/documentation/wiki/BHoM-Structural-Conventions.")]
+        [Input("bar", "The bar to check for verticality.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/IsVertical.cs]: Bar

File: Structure_Engine/Query/IsVertical.cs [hunk 27]
```diff
@@ -35,6 +35,10 @@ public static partial class Query
...
+        [Output("result", "Returns true if the bar is vertical.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/IsVertical.cs]: Bar

File: Structure_Engine/Query/Mass.cs [hunk 28]
```diff
@@ -30,13 +33,19 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Calculates the mass of a Bar as its length times mass per metre. The mass per metre is generally takes as section area times density. No offsets or similar ar taken into acount.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Mass.cs]: Calculates the mass of a Bar as its length times mass per metre. The mass per metre is calculated as section area multiplied by the density. No offsets or similar ar taken into acount.

File: Structure_Engine/Query/Mass.cs [hunk 29]
```diff
@@ -30,13 +33,19 @@ public static partial class Query
...
+        [Input("bar", "The Bar to calculate the mass for.")]
+        [Output("mass", "The mass of the Bar.", typeof(Mass))]
         public static double Mass(this Bar bar)
         {
             return bar.Length() * bar.SectionProperty.IMassPerMetre();
         }
 
         /***************************************************/
 
+        [Description("Calculates the mass of a Panel as its area times mass per area. The mass per area is for a constant thickness takes as thickness times density.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Mass.cs]: as above

File: Structure_Engine/Query/MassPerArea.cs [hunk 30]
```diff
@@ -32,6 +34,9 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Calculates the mass per area for the property as its thickness times density.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/MassPerArea.cs]: mulitplied by

File: Structure_Engine/Query/MassPerMetre.cs [hunk 31]
```diff
@@ -31,13 +34,19 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Calculates the mass per length for the section as its area times density.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/MassPerMetre.cs]: mulitplied by

File: Structure_Engine/Query/MassPerMetre.cs [hunk 32]
```diff
@@ -31,13 +34,19 @@ public static partial class Query
...
+        [Input("section", "The SectionProperty to calculate the mass per area for.")]
+        [Output("massPerLength", "The mass per length for the section.", typeof(MassPerUnitLength))]
         public static double MassPerMetre(this ISectionProperty section)
         {
             return section.Area * section.Material.Density;
         }
 
         /***************************************************/
 
+        [Description("Calculates the mass per length for the section as its area times density. Does not take any reinforcement into acount")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/MassPerMetre.cs]: multiplied by

File: Structure_Engine/Query/MassPerMetre.cs [hunk 33]
```diff
@@ -54,6 +66,9 @@ public static double MassPerMetre(this CompositeSection section)
 
         /***************************************************/
 
+        [Description("Calculates the mass per length for the section as its area times density.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/MassPerMetre.cs]: multiplied by

File: Structure_Engine/Query/MaterialType.cs [hunk 34]
```diff
@@ -36,41 +34,59 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Gets the material type from the material fragment. This will for a Steel material always return type Steel.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/MaterialType.cs]: Material
I think the second sentence should be e.g.

File: Structure_Engine/Query/MaterialType.cs [hunk 35]
```diff
@@ -36,41 +34,59 @@ public static partial class Query
...
+        [Input("materialFragment", "The structural material fragment to get the type from")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/MaterialType.cs]: Material

File: Structure_Engine/Query/MaterialType.cs [hunk 36]
```diff
@@ -36,41 +34,59 @@ public static partial class Query
...
+        [Output("type", "The material type of the provided material.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/MaterialType.cs]: Material

File: Structure_Engine/Query/MaterialType.cs [hunk 37]
```diff
@@ -36,41 +34,59 @@ public static partial class Query
...
         public static MaterialType MaterialType(this GenericIsotropicMaterial materialFragment)
         {
             return oM.Structure.MaterialFragments.MaterialType.Undefined;
         }
 
         /***************************************************/
 
+        [Description("Gets the material type from the material fragment. This will for a GenericOrthotropicMaterial material always return type Undefined.")]
+        [Input("materialFragment", "The structural material fragment to get the type from")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/MaterialType.cs]: Material required is various places
As above, example should be e.g.

File: Structure_Engine/Query/MaterialType.cs [hunk 38]
```diff
@@ -80,6 +96,9 @@ public static MaterialType MaterialType(this GenericOrthotropicMaterial material
         /**** Public Methods - Interface                ****/
         /***************************************************/
 
+        [Description("Gets the material type from the material fragment.")]
+        [Input("materialFragment", "The structural material fragment to get the type from")]
+        [Output("type", "The material type of the provided material.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/MaterialType.cs]: Material

File: Structure_Engine/Query/Normal.cs [hunk 39]
```diff
@@ -36,16 +36,22 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
-        [Description("Returns the bars local Z-axis")]
+        [Description("Returns the bars local z-axis, generally the major axis direction of the section of the Bar. \n" +
+                     "For non - vertical members the local z is aligned with the global z and rotated with the orientation angle around the local x. \n" +
+                     "For vertical members the local y is aligned with the global y and rotated with the orientation angle around the local x. For this case the normal will be the vector orthogonal to the local y and local x")]
         [Input("bar", "The Bar to evaluate the normal of")]
-        [Output("normal", "Vector representing the bars local Z-axis")]
+        [Output("normal", "Vector representing the local z-axis of the Bar")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Normal.cs]: Z should be capital for global
z should be lowercase for local

File: Structure_Engine/Query/OppositeNode.cs [hunk 40]
```diff
@@ -30,12 +33,21 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("If the provided node belongs to the Bar, this method returns the Node on the end of the Bar. The node if checked if it belongs to the bar by comparing its Guid. If the provided node is neither start or end node, null is returned.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/OppositeNode.cs]: If the provided node belongs to the Bar, this method returns the Node on the opposite end of the Bar. The Node is checked if it belongs to the Bar by comparing its Guid. If the provided Nodeis neither StartNode or EndNode, null is returned."

File: Structure_Engine/Query/OppositeNode.cs [hunk 41]
```diff
@@ -30,12 +33,21 @@ public static partial class Query
...
+        [Input("bar", "The bar to get the oposite node from")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/OppositeNode.cs]: Bar Node

File: Structure_Engine/Query/OppositeNode.cs [hunk 42]
```diff
@@ -30,12 +33,21 @@ public static partial class Query
...
+        [Input("node", "The node used to check for the oposite. This should be either the start or the end node of the Bar for the method to return anything.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/OppositeNode.cs]: Node StartNode EndNode

File: Structure_Engine/Query/OppositeNode.cs [hunk 43]
```diff
@@ -30,12 +33,21 @@ public static partial class Query
...
+        [Output("node", "The oposite node of the bar in relation to the one provided.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/OppositeNode.cs]: Node Bar

File: Structure_Engine/Query/OppositeNode.cs [hunk 44]
```diff
@@ -30,12 +33,21 @@ public static partial class Query
...
         public static Node OppositeNode(this Bar bar, Node node)
         {
             if (bar.EndNode.BHoM_Guid == node.BHoM_Guid)
                 return bar.StartNode;
-            else
+            else if (bar.StartNode.BHoM_Guid == node.BHoM_Guid)
                 return bar.EndNode;
+            else
+            {
+                Reflection.Compute.RecordError("The bar does not contain the provided node.");
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/OppositeNode.cs]: Bar Node

File: Structure_Engine/Query/PointGrid.cs [hunk 45]
```diff
@@ -37,6 +41,9 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Generates a rectangular grid of points on the Panel, scaled depending on panel size. Used for load visualisation.")]
+        [Input("panel","The Panel to generate a grid on.")]
+        [Output("grid", "The generated rectangular grid of points on the Panel.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/PointGrid.cs]: Rectangular grid of points on the Panel

File: Structure_Engine/Query/SelectCase.cs [hunk 46]
```diff
@@ -36,22 +39,30 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
-        public static List<T> SelectCase<T>(this List<T> results, object loadCase) where T : IResult
+        [Description("Filters out results from a specific case given a identifier, Loadcase or LoadCombination. For Loadcase and LoadCombination the number property will be used as identifier for filtering.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/SelectCase.cs]: an identifier

File: Structure_Engine/Query/SelectCase.cs [hunk 47]
```diff
@@ -36,22 +39,30 @@ public static partial class Query
...
+        [Input("results","The list of results to filter.")]
+        [Input("loadcase", "The case or combination to filter by. Should either be a string/int as identifier of the case or a BHoM Loadcase/LoadCombination where the number will be used as the identifier. If identifier can be extracted, all results are returned.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/SelectCase.cs]: remove BHoM

File: Structure_Engine/Query/SelectCase.cs [hunk 48]
```diff
@@ -36,22 +39,30 @@ public static partial class Query
...
+                else if (loadcase is int || loadcase is double)
+                    loadCaseId = loadcase.ToString();
 
                 if (!string.IsNullOrWhiteSpace(loadCaseId))
                     return results.Where(x => x.ResultCase.ToString() == loadCaseId).ToList();
+                else
+                    Reflection.Compute.RecordWarning("Could not extract filter identifier from the provided loadcase filter. All results are returned.");
             }
+            else
+                Reflection.Compute.RecordWarning("loadCase filter is null. No filtering is applied. All results are returned.");
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/SelectCase.cs]: Loadcase

File: Structure_Engine/Query/ShearArea.cs [hunk 49]
```diff
@@ -32,6 +36,13 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("This method is mainly replaced by the Compute.ShearAreaPolyline() Method. \n" +
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/ShearArea.cs]: largely instead of mainly

File: Structure_Engine/Query/ShearModulus.cs [hunk 50]
```diff
@@ -37,8 +38,9 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
-        [Description("Shear modulus of the isotropic material fragment. Evaluated based on Youngs modulus and Poissons ratio")]
-        [Output("G", "Shear modulus of the material fragment")]
+        [Description("Shear modulus of the isotropic material fragment. Evaluated based on Youngs modulus and Poissons ratio as G = E/2(1+ν)")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/ShearModulus.cs]: YoungsModulus PoissonsRatio

File: Structure_Engine/Query/StructuralMaterialFragment.cs [hunk 51]
```diff
@@ -36,7 +36,9 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
-        [Description("Gets a structural material fragment from a material class")]
+        [Description("Gets a structural material fragment, containing all relevant structural material data, from a physical Material class.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/StructuralMaterialFragment.cs]: Material

File: Structure_Engine/Query/StructuralMaterialFragment.cs [hunk 52]
```diff
@@ -36,7 +36,9 @@ public static partial class Query
...
+        [Input("material", "The physical Material to extract a structural material fragment from.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/StructuralMaterialFragment.cs]: Material

File: Structure_Engine/Query/StructuralMaterialFragment.cs [hunk 53]
```diff
@@ -36,7 +36,9 @@ public static partial class Query
...
+        [Output("strMat", "The structural material fragment.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/StructuralMaterialFragment.cs]: Material

File: Structure_Engine/Query/Tangent.cs [hunk 54]
```diff
@@ -32,9 +35,13 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Gets the tangent vector of a bar as the direction vector from start to end node. No offsets or similar are taken into account.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Tangent.cs]: "Gets the tangent Vector of a Bar as the direction Vector from StartNode to EndNode. No offsets or similar are taken into account.

File: Structure_Engine/Query/Tangent.cs [hunk 55]
```diff
@@ -32,9 +35,13 @@ public static partial class Query
...
+        [Input("bar", "The Bar to get the tangent from.")]
+        [Input("normalise", "If true, the tangent vector returned will be a unit vector, that is, a vector with length 1.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Tangent.cs]: Vector Vector

File: Structure_Engine/Query/Tangent.cs [hunk 56]
```diff
@@ -32,9 +35,13 @@ public static partial class Query
...
+        [Output("tan", "The tangent vector of the bar.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Tangent.cs]: Vector Bar

File: Structure_Engine/Query/TieDiameter.cs [hunk 57]
```diff
@@ -31,6 +34,9 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Extracts the the diameter of the first tie reinforecment of a concrete section. If no tie reinforcement is found, 0 will be returned.")]
+        [Input("property", "The concrete section to get tie reinforcement diameter from.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/TieDiameter.cs]: ConcreteSection TieReinforcement

File: Structure_Engine/Query/TieDiameter.cs [hunk 58]
```diff
@@ -31,6 +34,9 @@ public static partial class Query
...
+        [Output("dia", "The diameter of the first tie reinforcement of the concrete section", typeof(Length))]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/TieDiameter.cs]: TieReinforcement ConcreteSection

File: Structure_Engine/Query/TorsionalConstant.cs [hunk 59]
```diff
@@ -65,29 +68,31 @@ public static partial class Query
...
-        
-        public static double TorsionalConstant(this IProfile profile) 
-        {
-            return 0; //Return 0 for not specifically implemented ones
-        }
-
         /***************************************************/
 
+        [Description("Calcualtes the Torsinal constant for the profile. Note that this is not the polar moment of inertia")]
+        [Input("profile", "The shape profile to calculate the torsional constant for.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/TorsionalConstant.cs]: ShapeProfile 

same for the rest of the descriptions

File: Structure_Engine/Query/AnalyticalBars.cs [hunk 60]
```diff
@@ -45,9 +46,10 @@ public static partial class Query
```
[the remark this answers is not in the document]
Comment (IsakNaslundBh) [reply Structure_Engine/Query/AnalyticalBars.cs]: Depends how you look at it I think. The Mass is not a property of the bar either, but still available through a query method. Could, and have been, arguing that this would be an more extreme case of that. "Get the analytical bars from the physical framing". At the other end we have a Create method for framingElement that accepts a bar. 

But, I do get your point.

File: Structure_Engine/Query/InternalElements2D.cs (hunk 20 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Query/InternalElements2D.cs]: Required method for all IElement2Ds. Both Panel and Opening are of this type.

File: Structure_Engine/Query/Normal.cs (hunk 39 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Query/Normal.cs]: I think I changed it to local here? Or am I missing something?

Comment (peterjamesnugent) [reply Structure_Engine/Query/Normal.cs]: In the Description there's instances of global z, also I think we should be saying local z-axis rather than local z, local y.

Comment (IsakNaslundBh) [reply Structure_Engine/Query/Normal.cs]: You are right ofc, missed that. Just looked on the output row where I already had changed from capital to lowercase just as you requested and got confused.

File: Structure_Engine/Query/DistributedPoints.cs [hunk 61]
```diff
@@ -33,20 +37,32 @@ public static partial class Query
...
+        [Input("bar", "The bar to get division points for")]
+        [Input("divisions", "Number of segments to divide the bar into. The number of points returned will be divisions +1.")]
+        [Input("startLength", "Optional offset from bar start node to start of divisions.", typeof(Length))]
+        [Input("endLength", "Optional offset from bar end node to start of divisions.", typeof(Length))]
+        [Output("points", "List of evenly distibuted points along the bar.")]
+        public static List<Point> DistributedPoints(this Bar bar, int divisions, double startLength = 0, double endLength = 0)
         {
+            if (divisions < 1)
+            {
+                Reflection.Compute.RecordWarning("Cant handle 0 or negative divisions. Divisions has been set to 1!");
```
[the remark this answers is not in the document]
Comment (IsakNaslundBh) [reply Structure_Engine/Query/DistributedPoints.cs]: not sure? as the method is fixing something for you and telling what it has done, I would almost see it as a warning?

File: Structure_Engine/Query/InternalElements2D.cs (hunk 20 above)
Comment (peterjamesnugent) [reply Structure_Engine/Query/InternalElements2D.cs]: I think the description is enough.

File: Structure_Engine/Query/MaterialType.cs (hunk 34 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Query/MaterialType.cs]: Not sure we should capitalise the material here. This refers to the structures oM where we do not have any class named Material

File: Structure_Engine/Query/StructuralMaterialFragment.cs (hunk 51 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Query/StructuralMaterialFragment.cs]: Not sure we should capitalise the material here, except where it is already capitalised. The rest refers to the structures oM where we do not have any class named Material

File: Structure_Engine/Query/Normal.cs [hunk 62]
```diff
@@ -36,16 +36,22 @@ public static partial class Query
...
+        [Output("normal", "Vector representing the local z-axis of the Bar.")]
         public static Vector Normal(this Bar bar)
         {
             return bar.Centreline().ElementNormal(bar.OrientationAngle);
         }
 
         /***************************************************/
 
+        [Deprecated("3.1", "Deprecated by method targeting IElement2D.")]
+        [Description("Returns the Panels local z-axis, a vector orthogonal to the plane of the panel. This is found by fitting a plane through all the edge curves and taking the Normal from this plane.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Normal.cs]: Panel 
should Normal be normal

File: Structure_Engine/Query/Normal.cs [hunk 63]
```diff
@@ -55,12 +61,25 @@ public static Vector Normal(this Panel panel)
...
             return Normal(areaElement as dynamic);
         }
 
         /***************************************************/
+        /**** Private Methods - fall back               ****/
+        /***************************************************/
+
+        private static Vector Normal(this IAreaElement areaElement)
+        {
+            Reflection.Compute.RecordWarning("Can not get normal for element of type " + areaElement.GetType().Name);
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Normal.cs]: Cannot get normal for element of type

File: Structure_Engine/Query/OppositeNode.cs [hunk 64]
```diff
@@ -30,12 +33,21 @@ public static partial class Query
...
         public static Node OppositeNode(this Bar bar, Node node)
         {
             if (bar.EndNode.BHoM_Guid == node.BHoM_Guid)
                 return bar.StartNode;
-            else
+            else if (bar.StartNode.BHoM_Guid == node.BHoM_Guid)
                 return bar.EndNode;
+            else
+            {
+                Reflection.Compute.RecordError("The Bar does not contain the provided node.");
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/OppositeNode.cs]: Node

File: Structure_Engine/Query/OutlineElements1D.cs [hunk 65]
```diff
@@ -32,16 +35,24 @@ public static partial class Query
         /****               Public Methods              ****/
         /***************************************************/
 
+        [Description("Gets the elements from an Opening defining the boundary of the element. Method required for all IElement2Ds. \n" +
+             "For an opening this will return a list of its edges.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/OutlineElements1D.cs]: Edges

File: Structure_Engine/Query/PointGrid.cs [hunk 66]
```diff
@@ -37,6 +41,9 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Generates a rectangular grid of points on the Panel, scaled depending on panel size. Used for load visualisation.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/PointGrid.cs]: Panel

File: Structure_Engine/Query/CoordinateSystem.cs [hunk 67]
```diff
@@ -38,15 +38,19 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
-        [Description("Get a carteseian coordinate system descibring the position and orientation of the node in the Global XY system")]
+        [Description("Get a carteseian coordinate system descibring the position and orientation of the node in the Global XY system.")]
```
[the remark this answers is not in the document]
Comment (IsakNaslundBh) [reply Structure_Engine/Query/CoordinateSystem.cs]: are you sure? Agree that the current wording could be improved, but think the description needs to refer to global XYZ space (might be a better wording?) and not plane. global XY plane I would read as it never have any z-coordinate.

File: Structure_Engine/Query/DeformedShape.cs [hunk 68]
```diff
@@ -144,7 +162,7 @@ private static List<Loft> DeformedShapeSection(Bar bar, List<BarDisplacement> de
                 Loft loft = new Loft();
                 foreach (BarDisplacement defo in deformations)
                 {
-                    //ICurve curve = sectionCurve.IRotate(bar.StartNode.Position(), tan, defo.RX * scaleFactor);
+                    //ICurve curve = sectionCurve.IRotate(bar.StartNode.Position, tan, defo.RX * scaleFactor);
```
[the remark this answers is not in the document]
Comment (IsakNaslundBh) [reply Structure_Engine/Query/DeformedShape.cs]: in general, yes, but opted to keep those lines for further reference for this case

File: Structure_Engine/Query/DeformedShape.cs [hunk 69]
```diff
@@ -144,7 +162,7 @@ private static List<Loft> DeformedShapeSection(Bar bar, List<BarDisplacement> de
...
                     //Vector disp = unitTan * defo.UX * scaleFactor + yAxis * defo.UY * scaleFactor + normal * defo.UZ * scaleFactor;
```
[the remark this answers is not in the document]
Comment (IsakNaslundBh) [reply Structure_Engine/Query/DeformedShape.cs]: as above

File: Structure_Engine/Query/Geometry.cs [hunk 70]
```diff
@@ -37,34 +39,49 @@ public static partial class Query
...
+        [Output("point", "The geometry of the Node")]
         public static Point Geometry(this Node node)
         {
-            return node.Position();
+            return node.Position;
         }
 
         /***************************************************/
 
+        [Description("Gets the geometry of a Bar as its CentreLine. Method required for automatic display in UI packages.")]
```
[the remark this answers is not in the document]
Comment (IsakNaslundBh) [reply Structure_Engine/Query/Geometry.cs]: hmm, could use this. I choose the wording I did as the geometry of the bar could be many things, extrusions etc, but that this method is returning the centreline representation, if that makes sense?

File: Structure_Engine/Query/IsVertical.cs [hunk 71]
```diff
@@ -35,22 +35,26 @@ public static partial class Query
...
             return Engine.Geometry.Query.IsVertical(line);
         }
 
         /***************************************************/
 
-        [Deprecated("2.3", "Methods replaced with methods targeting BH.oM.Physical.Elements.IFramingElement")]
+        [Deprecated("2.3", "Methods replaced with methods targeting BH.oM.Physical.Elements.IFramingElement.")]
         public static bool IsVertical(this FramingElement element)
         {
             return Engine.Geometry.Query.IsVertical(new Line() { Start = element.LocationCurve.IStartPoint(), End = element.LocationCurve.IEndPoint() } ); //TODO: is this correct? what is the framing element is curved?
```
[the remark this answers is not in the document]
Comment (IsakNaslundBh) [reply Structure_Engine/Query/IsVertical.cs]: think we should wait until next milestone, to keep it one year.

[the remark this answers is not in the document]
Comment (peterjamesnugent) [reply Structure_Engine/Query/IsVertical.cs]: I thought it was 6 months, I may be misremembering though.

File: Structure_Engine/Query/Geometry.cs (hunk 70 above)
[the remark this answers is not in the document]
Comment (peterjamesnugent) [reply Structure_Engine/Query/Geometry.cs]: Yeah, that does make sense.

File: Structure_Engine/Query/CoordinateSystem.cs (hunk 67 above)
[the remark this answers is not in the document]
Comment (peterjamesnugent) [reply Structure_Engine/Query/CoordinateSystem.cs]: I have rewritten it below, also updated the description for Bar inputs.

        [Description("Get the carteseian coordinate system descibring the position and orientation of the node in the Global system")]
        public static Cartesian CoordinateSystem(this Node node)
        {
            return Engine.Geometry.Create.CartesianCoordinateSystem(node.Position, node.Orientation.X, node.Orientation.Y);
        }

        /***************************************************/

        [Description("Get the carteseian coordinate system descibring the position and orientation of the Bar in the Global system where the Bar tangent is the local x-axis and the normal is the local z-axis")]
        public static Cartesian CoordinateSystem(this Bar bar)
        {
            Vector tan = bar.Tangent(true);
            Vector ax = bar.Normal().CrossProduct(tan);
            return Engine.Geometry.Create.CartesianCoordinateSystem(bar.StartNode.Position, tan, ax);
        }

        /***************************************************/

File: Structure_Engine/Query/CoordinateSystem.cs [hunk 72]
```diff
@@ -38,15 +38,19 @@ public static partial class Query
...
+        [Output("CoordinateSystem","The local cartesian coordinate system of the Node.")]
         public static Cartesian CoordinateSystem(this Node node)
         {
             return Engine.Geometry.Create.CartesianCoordinateSystem(node.Position, node.Orientation.X, node.Orientation.Y);
         }
 
         /***************************************************/
 
-        [Description("Get a carteseian coordinate system descibring the position and orientation of the bar in the Global XY system where the bars tangent is the local X-axis and the Normal is the local Z-axis")]
+        [Description("Get a carteseian coordinate system descibring the position and orientation of the Bar in the Global XY system where the bars tangent is the local X-axis and the Normal is the local Z-axis.")]
```
[the remark this answers is not in the document]
Comment (peterjamesnugent) [reply Structure_Engine/Query/CoordinateSystem.cs]: Ignore, this is taken care of above.

File: Structure_Engine/Query/Geometry.cs [hunk 73]
```diff
@@ -37,34 +39,49 @@ public static partial class Query
...
         public static Line Geometry(this Bar bar)
         {
             return bar.Centreline();
         }
 
         /***************************************************/
 
+        [Description("Gets the geometry of a Edge as its curve. Method required for automatic display in UI packages.")]
+        [Input("edge", "Edge to get the curve geometry from.")]
+        [Output("curve", "The geometry of the Edge as its Curve.")]
```
[the remark this answers is not in the document]
Comment (IsakNaslundBh) [reply Structure_Engine/Query/Geometry.cs]: Propertyi s CUrve with capital c , so think reference should be capitalised.

[the remark this answers is not in the document]
Comment (peterjamesnugent) [reply Structure_Engine/Query/Geometry.cs]: Agree with this.

File: Structure_Engine/Query/IsVertical.cs (hunk 71 above)
[the remark this answers is not in the document]
Comment (IsakNaslundBh) [reply Structure_Engine/Query/IsVertical.cs]: Ok, keeping for now!

File: Structure_Engine/Query/Area.cs [hunk 74]
```diff
@@ -44,6 +50,9 @@ public static double Area(this Panel panel)
 
         /***************************************************/
 
+        [Description("Calculates the area of an opening as the area of its edges.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Area.cs]: Opening

File: Structure_Engine/Query/Area.cs [hunk 75]
```diff
@@ -53,6 +62,9 @@ public static double Area(this Opening opening)
 
         /***************************************************/
 
+        [Description("Calculates the area of a FEMesh as the sum of the area of all faces. Quad faces will be triangulated to preform the area calculation.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Area.cs]: perform

File: Structure_Engine/Query/CoordinateSystem.cs [hunk 76]
```diff
@@ -38,15 +38,19 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
-        [Description("Get a carteseian coordinate system descibring the position and orientation of the node in the Global XY system")]
+        [Description("Get the carteseian coordinate system descibring the position and orientation of the node in the Global system")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/CoordinateSystem.cs]: I wonder if this should be Global coordinate system

File: Structure_Engine/Query/Extrude.cs [hunk 77]
```diff
@@ -38,6 +42,10 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Computes an extrusion of the section along the Bar centreline.")]
+        [Input("bar", "The Bar to get an extruded shape from. This requires the property of the Bar to be of a type with a section profile.")]
+        [Input("simple", "If false, a full extrusion of the section curves along the Bar will be returned. If true, a box mesh enclosing the extruded section will be returned.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Extrude.cs]: What is the box mesh in this case? Is it a bounding box? Can this be confused with Mesh, FEMesh etc.

File: Structure_Engine/Query/Geometry.cs [hunk 78]
```diff
@@ -89,47 +109,56 @@ public static CompositeGeometry Geometry(this ConcreteSection section)
 
         /***************************************************/
 
-        [Deprecated("3.1", "Replaced with method for base interface IGeometricalSection", typeof(Query), "Geometry(this IGeometricalSection section)")]
+        [Deprecated("3.1", "Replaced with method for base interface IGeometricalSection.", typeof(Query), "Geometry(this IGeometricalSection section).")]
         public static IGeometry Geometry(this SteelSection section)
         {
             return new CompositeGeometry { Elements = section.SectionProfile.Edges.ToList<IGeometry>() };
         }
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Geometry.cs]: Move deprecated methods to the end under the header:

```
/***************************************************/
/ Public Methods - Deprecated /
/***************************************************/
```

File: Structure_Engine/Query/Geometry.cs [hunk 79]
```diff
@@ -89,47 +109,56 @@ public static CompositeGeometry Geometry(this ConcreteSection section)
...
 
         /***************************************************/
 
-        [Deprecated("2.3", "Methods replaced with methods targeting BH.oM.Physical.Elements.IFramingElement")]
+        [Deprecated("2.3", "Methods replaced with methods targeting BH.oM.Physical.Elements.IFramingElement.")]
         public static ICurve Geometry(this FramingElement element)
         {
             return element.LocationCurve;
         }
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Geometry.cs]: As above

File: Structure_Engine/Query/Geometry.cs [hunk 80]
```diff
@@ -89,47 +109,56 @@ public static CompositeGeometry Geometry(this ConcreteSection section)
...
 
         /***************************************************/
 
+        [Description("Gets the geometry of a FEMesh as a geometrical Mesh. A geometrical mesh only support 3 and 4 nodes faces, while a FEMesh does not have this limitation. For FEMeshFaces with more than 4 nodes or less than 3 this operation is therefore not possible. Method required for automatic display in UI packages.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Geometry.cs]: supports

File: Structure_Engine/Query/Normal.cs [hunk 81]
```diff
@@ -36,16 +36,22 @@ public static partial class Query
...
         {
             return bar.Centreline().ElementNormal(bar.OrientationAngle);
         }
 
         /***************************************************/
 
+        [Deprecated("3.1", "Deprecated by method targeting IElement2D.")]
+        [Description("Returns the Panels local z-axis, a vector orthogonal to the plane of the Panel. This is found by fitting a plane through all the edge curves and taking the Normal from this plane.")]
+        [Input("panel", "The Panel to evaluate the normal of.")]
+        [Output("normal", "Vector representing the local z-axis Panel.")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/Normal.cs]: Move deprecated methods to the end of the file

File: Structure_Engine/Query/Extrude.cs (hunk 77 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Query/Extrude.cs]: will be as a bounding box in local coordinates

File: Structure_Engine/Query/CoordinateSystem.cs [hunk 82]
```diff
@@ -38,15 +38,19 @@ public static partial class Query
         /**** Public Methods                            ****/
         /***************************************************/
 
-        [Description("Get a carteseian coordinate system descibring the position and orientation of the node in the Global XY system")]
+        [Description("Get the carteseian coordinate system descibring the position and local orientation of the node in the Global coordinate system")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/CoordinateSystem.cs]: global

File: Structure_Engine/Query/CoordinateSystem.cs [hunk 83]
```diff
@@ -38,15 +38,19 @@ public static partial class Query
...
+        [Output("CoordinateSystem","The local cartesian coordinate system of the Node.")]
         public static Cartesian CoordinateSystem(this Node node)
         {
             return Engine.Geometry.Create.CartesianCoordinateSystem(node.Position, node.Orientation.X, node.Orientation.Y);
         }
 
         /***************************************************/
 
-        [Description("Get a carteseian coordinate system descibring the position and orientation of the bar in the Global XY system where the bars tangent is the local X-axis and the Normal is the local Z-axis")]
+        [Description("Get the carteseian coordinate system descibring the position and local orientation of the Bar in the Global coordinate system where the Bar tangent is the local x-axis and the normal is the local z-axis")]
```
Comment (peterjamesnugent) [inline Structure_Engine/Query/CoordinateSystem.cs]: global
