### PR TITLE
Facade_Engine: Added ExternalEdges, GetEdgeType, and corresponding Create Methods

### LINKED ISSUE #2424: Facade_Engine: Modify Engine Methods to work with Line or Polyline defined outlines
#### Description:
When elements have a frameEdge applied that is made up of a polyline, UniqueAdjacencies fails due to IsAdjacent returning a not implemented warning for polylines. To extend functionality, the adjacency methods should account for polylines by breaking them down to their constituent parts.

#### Steps to reproduce:
Run UniqueAdjacencies on elements that include panels created using a single curve outline applied to a frame edge.

#### Expected behaviour:
Working method with all elements, whether defined via lines or polylines.

#### Test file(s):
Any file with panels creating using a frame edge created with a polyline.

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #2424 

This PR adds features for use friendly Facade Create methods leveraging new query methods for ExternalEdges and GetEdgeType as well as added functionality to previous adjacency methods. 

### Test files
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%232424-AdjacencyAndEdgeTypeFeatureAdd?csf=1&web=1&e=avaE7L

The test script accounts for the GetEdgeType Query method as well as checks for the Create methods that use it and the adjacency methods that have been added / changed.

### CODE REVIEW

**Comment by enarhi** [comment]
check installer

**Comment by enarhi** [comment]
BHoMBot  check compliance

**Comment by enarhi** [comment]
@BHoMBot check compliance

File: Facade_Engine/Compute/AdjacentElements.cs [hunk 1]
```diff
@@ -64,12 +64,13 @@ public static List<IElement2D> AdjacentElements(this IElement2D elem, List<IElem
...
         /***************************************************/
 
-        [Description("Returns elements adjacent to a provided Element1D from a collection of elements")]
-        [Input("elem", "Element to find adjacencies at")]
-        [Input("refElems", "Elements to use to find element adjacencies")]
-        [Output("adjElems", "Adjacents elements to the provided element")]
+        [Description("Returns elements adjacent to a provided Element1D from a collection of elements.")]
+        [Input("elem", "Element to find adjacencies at.")]
+        [Input("refElems", "Elements to use to find element adjacencies.")]
+        [Output("adjElems", "Adjacents elements to the provided element.")]
```
Comment (FraserGreenroyd) [inline Facade_Engine/Compute/AdjacentElements.cs:73]:
```suggestion
        [Input("element", "Element to find adjacencies at.")]
        [Input("referenceElements", "Elements to use to find element adjacencies.")]
        [Output("adjacentElements", "Adjacents elements to the provided element.")]
```

I don't see that we need to short-hand the descriptions/input variables really? Would be clearer to non-English-as-a-first-language coders if we didn't

File: Facade_Engine/Compute/AdjacentElements.cs [hunk 2]
```diff
@@ -87,6 +88,30 @@ public static List<IElement2D> AdjacentElements(this IElement1D elem, List<IElem
...
+            foreach (IElement1D refElem in refElems)
+            {
+                if (Query.IIsAdjacent(refElem, elem))
+                {
+                    adjElems.Add(refElem);
+                }
+            }
+
+            // Return the adjacencies
+            return adjElems;
```
Comment (FraserGreenroyd) [inline Facade_Engine/Compute/AdjacentElements.cs:113]: How about:
```suggestion
            return refElems.Where(x => Query.IIsAdjacent(x, elem)).ToList();
```

If `IIsAdjacent` is an extension method (it should be) then you could do:

```suggestion
            return refElems.Where(x => x.IIsAdjacent(elem)).ToList();
```

File: Facade_Engine/Compute/EdgeAdjacencies.cs [hunk 3]
```diff
@@ -47,8 +47,8 @@ public static partial class Compute
         [Input("edge", "Edge to find adjacencies at.")]
         [Input("elems", "2D elements to use to find edge adjacencies (These should be panels and/or openings).")]
         [Input("tolerance", "Tolerance is the minimum overlap amount required to consider adjacent.")]
-        [MultiOutput(0, "adjEdges", "Adjacent edges")]
-        [MultiOutput(1, "adjElems", "Adjacent Elements per adjacent edge")]
+        [MultiOutput(0, "adjEdges", "Adjacent edges.")]
+        [MultiOutput(1, "adjElems", "Adjacent Elements per adjacent edge.")]
```
Comment (FraserGreenroyd) [inline Facade_Engine/Compute/EdgeAdjacencies.cs:51]: Same comment here regarding variable names

File: Facade_Engine/Create/Elements/CurtainWall.cs [hunk 4]
```diff
@@ -0,0 +1,170 @@
...
+        [Input("jambProperty", "A FrameEdgeProperty to apply to the jamb edge(s) of the openings.")]
+        [Input("sillProperty", "A FrameEdgeProperty to apply to the sill edge(s) of the openings.")]
+        [Input("externalHeadProperty", "A FrameEdgeProperty to apply to the head edge(s) of openings at the edge of the CurtainWall.")]
+        [Input("externalJambProperty", "A FrameEdgeProperty to apply to the jamb edge(s) of openings at the edge of the CurtainWall.")]
+        [Input("externalSillProperty", "A FrameEdgeProperty to apply to the sill edge(s) of openings at the edge of the CurtainWall.")]
+        [Input("name", "Name of the CurtainWall to be created.")]
+        [Output("curtainWall", "Created CurtainWall.")]
+        public static CurtainWall CurtainWall(IEnumerable<ICurve> outlines, IEnumerable<IConstruction> constructions = null, FrameEdgeProperty headProperty = null, FrameEdgeProperty jambProperty = null, FrameEdgeProperty sillProperty = null,
+                                              FrameEdgeProperty externalHeadProperty = null, FrameEdgeProperty externalJambProperty = null, FrameEdgeProperty externalSillProperty = null, string name = "")
+        {
```
Comment (FraserGreenroyd) [inline Facade_Engine/Create/Elements/CurtainWall.cs:58]: This should either be one input per line, or all inputs on one line. The latter is my preference.

File: Facade_Engine/Create/Elements/CurtainWall.cs [hunk 5]
```diff
@@ -0,0 +1,170 @@
...
+            if(outlines == null)
+            {
+                BH.Engine.Reflection.Compute.RecordError("Cannot create a CurtainWall from a null collection of outlines.");
+                return null;
+            }
+
+            bool useConstructions = true;
+            if (outlines.Count() != constructions.Count() )
```
Comment (FraserGreenroyd) [inline Facade_Engine/Create/Elements/CurtainWall.cs:66]:
```suggestion
            if (outlines.Count() != constructions.Count())
```

File: Facade_Engine/Create/Elements/CurtainWall.cs [hunk 6]
```diff
@@ -0,0 +1,170 @@
...
+
+            externalHeadProperty = externalHeadProperty ?? headProperty;
+            externalJambProperty = externalJambProperty ?? jambProperty;
+            externalSillProperty = externalSillProperty ?? sillProperty;
+
+            List<Opening> openings = new List<Opening>();
+            for (int i = 0; i < outlines.Count(); i++)
+            {
+                ICurve outline = outlines.ElementAt(i);
+                if (outline.IIsClosed() != true)
```
Comment (FraserGreenroyd) [inline Facade_Engine/Create/Elements/CurtainWall.cs:80]:
```suggestion
                if (!outline.IIsClosed())
```

File: Facade_Engine/Create/Elements/CurtainWall.cs [hunk 7]
```diff
@@ -0,0 +1,170 @@
...
+                {
+                    BH.Engine.Reflection.Compute.RecordError("Outline at index " + i + " was not closed and was excluded from the created CurtainWall. This method only works with closed outlineswhich each represent one opening in the CurtainWall.");
```
Comment (FraserGreenroyd) [inline Facade_Engine/Create/Elements/CurtainWall.cs:82]:
```suggestion
                    BH.Engine.Reflection.Compute.RecordError("Outline at index " + i + " was not closed and was excluded from the created CurtainWall. This method only works with closed outlines which each represent one opening in the CurtainWall.");
```

File: Facade_Engine/Create/Elements/CurtainWall.cs [hunk 8]
```diff
@@ -0,0 +1,170 @@
...
+                                break;
+                        }
+                    }
+                }
+            }
+
+            List<FrameEdge> extFrameEdges = externalEdges.OfType<ICurve>().Select(x => new FrameEdge { Curve = x }).ToList();
+            CurtainWall curtainWall = new CurtainWall { ExternalEdges = extFrameEdges, Openings = openings, Name = name };
+
+            return curtainWall;
```
Comment (FraserGreenroyd) [inline Facade_Engine/Create/Elements/CurtainWall.cs:122]:
```suggestion
            return new CurtainWall { ExternalEdges = extFrameEdges, Openings = openings, Name = name };
```

File: Facade_Engine/Create/Elements/CurtainWall.cs [hunk 9]
```diff
@@ -0,0 +1,170 @@
...
+                return null;
+            }
+
+            List<Opening> openings = new List<Opening>();
+            for (int i = 0; i < outlines.Count(); i++)
+            {
+                ICurve outline = outlines.ElementAt(i);
+                if (outline.IIsClosed() != true)
+                {
+                    BH.Engine.Reflection.Compute.RecordError("Outline at index " + i + " was not closed and was excluded from the created CurtainWall. This method only works with closed outlineswhich each represent one opening in the CurtainWall.");
```
Comment (FraserGreenroyd) [inline Facade_Engine/Create/Elements/CurtainWall.cs:148]:
```suggestion
                    BH.Engine.Reflection.Compute.RecordError("Outline at index " + i + " was not closed and was excluded from the created CurtainWall. This method only works with closed outlines which each represent one opening in the CurtainWall.");
```

File: Facade_Engine/Create/Elements/CurtainWall.cs [hunk 10]
```diff
@@ -0,0 +1,170 @@
...
+                    openings.Add(opening);
+                }
+            }
+
+            List<IElement1D> externalEdges = Query.ExternalEdges(openings);
+            List<FrameEdge> extFrameEdges = externalEdges.OfType<ICurve>().Select(x => new FrameEdge { Curve = x }).ToList();
+
+            CurtainWall curtainWall = new CurtainWall { ExternalEdges = extFrameEdges, Openings = openings, Name = name };
+
+            return curtainWall;
```
Comment (FraserGreenroyd) [inline Facade_Engine/Create/Elements/CurtainWall.cs:162]:
```suggestion
            return new CurtainWall { ExternalEdges = extFrameEdges, Openings = openings, Name = name };
```

File: Facade_Engine/Create/Elements/Opening.cs [hunk 11]
```diff
@@ -85,6 +85,75 @@ public static Opening Opening(IEnumerable<ICurve> edges, IConstruction construct
...
+            {
+                BH.Engine.Reflection.Compute.RecordError("Cannot create an opening from a null collection of edges.");
+                return null;
+            }
+
+            List<ICurve> externalEdges = new List<ICurve>();
+            foreach (ICurve edge in edges)
+            {
+                externalEdges.AddRange(edge.ISubParts());
+            }
```
Comment (FraserGreenroyd) [inline Facade_Engine/Create/Elements/Opening.cs:109]:
```suggestion
            List<ICurve> externalEdges = edges.SelectMany(x => x.ISubParts()).ToList();
```

File: Facade_Engine/Create/Elements/Opening.cs [hunk 12]
```diff
@@ -85,6 +85,75 @@ public static Opening Opening(IEnumerable<ICurve> edges, IConstruction construct
...
+
+            List<PolyCurve> joined = Geometry.Compute.IJoin(edges.ToList());
+
+            if (joined.Count == 0)
+            {
+                Reflection.Compute.RecordError("Could not join Curves. Opening not Created.");
```
Comment (FraserGreenroyd) [inline Facade_Engine/Create/Elements/Opening.cs:115]:
```suggestion
                Reflection.Compute.RecordError("Could not join Curves. Opening not created.");
```

File: Facade_Engine/Modify/SetOffsetFromFacetoFaceDist.cs [hunk 13]
```diff
@@ -48,12 +48,14 @@ public static partial class Modify
...
         [Input("useroffset", "A user defined offset (exterior face of panel to exterior face of glazing).")]
         [Output("opening", "The opening with the specified offset applied as a fragment.")]
-        public static Opening SetOffsetFromFacetoFaceDist(this Opening opening, Panel panel, double useroffset)
+        public static void SetOffsetFromFacetoFaceDist(this Opening opening, Panel panel, double useroffset)
         {
-            //TODO:
             //Check for null case
-            if (panel == null || opening == null || useroffset == null)
-                return null;
+            if (panel == null || opening == null || useroffset == double.NaN)
```
Comment (FraserGreenroyd) [inline Facade_Engine/Modify/SetOffsetFromFacetoFaceDist.cs:54]: Is a negative offset allowed? If so, that's fine, just double checking

File: Facade_Engine/Query/ExternalEdges.cs [hunk 14]
```diff
@@ -0,0 +1,76 @@
...
+{
+    public static partial class Query
+    {
+        /***************************************************/
+        /****              Public methods               ****/
+        /***************************************************/
+
+        [Description("Returns external edges from a collection of 2D elements.")]
+        [Input("elems", "Elements to get external edges from.")]
+        [Output("extEdges", "External edges of elements.")]
```
Comment (FraserGreenroyd) [inline Facade_Engine/Query/ExternalEdges.cs:49]: See previous comments on this

File: Facade_Engine/Query/ExternalEdges.cs [hunk 15]
```diff
@@ -0,0 +1,76 @@
...
+        {
+            if (elems == null)
+                return null;
+
+            List<IElement1D> allEdges = new List<IElement1D>();
+            List<IElement1D> result = new List<IElement1D>();
+            foreach (IElement2D elem in elems)
+            {
+                allEdges.AddRange(elem.ExternalElementCurves());
+            }
```
Comment (FraserGreenroyd) [inline Facade_Engine/Query/ExternalEdges.cs:60]:
```suggestion
            List<IElement1D> allEdges = elems.SelectMany(x => x.ExternalElementCurves()).ToList();
            List<IElement1D> result = new List<IElement1D>();
```

File: Facade_Engine/Query/FrameEdgeType.cs [hunk 16]
```diff
@@ -0,0 +1,72 @@
...
+
+        [Description("Returns edge type (Sill, Head, or Jamb) from a FrameEdge and the Opening it belongs to.")]
+        [Input("frameEdge", "FrameEdge to get edge type from.")]
+        [Input("opening", "Opening the FrameEdge belongs to.")]
+        [Output("type", "FrameEdge type (Sill, Head, or Jamb).")]
+        public static string FrameEdgeType(this FrameEdge frameEdge, Opening opening)
+        {
+            if (frameEdge == null || opening == null || frameEdge.Curve == null)
+                return null;
+
```
Comment (FraserGreenroyd) [inline Facade_Engine/Query/FrameEdgeType.cs:55]:
```suggestion
```

File: Facade_Engine/Query/FrameEdgeType.cs [hunk 17]
```diff
@@ -0,0 +1,72 @@
...
+            else
+            {
+                ICurve crv = frameEdge.Curve;
+                double zVal = Math.Abs(crv.IEndDir().Z);
+                if (zVal > 0.7071)  //Check if curve is more than 45 degrees from horizontal plane
```
Comment (FraserGreenroyd) [inline Facade_Engine/Query/FrameEdgeType.cs:60]: Not a fan of hardcoded numbers like this - can this be a user specified tolerance? Alternatively, would need/want a Facade Engineer to confirm on this PR that this is acceptable.

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

File: Facade_Engine/Query/ExternalEdges.cs (hunk 15 above)
Comment (enarhi) [reply Facade_Engine/Query/ExternalEdges.cs]: Left similar to previous to keep the casting logic of allEdges as List<IElement1D> since elems.SelectMany... returns List<ICurve>. ALl ears if theres abetter way to do that.

**Comment by enarhi** [comment]
@FraserGreenroyd changes made per your request with the exception of the one change I noted that I left as is to avoid an awkward cast. Please re-review when you're able, and thanks for taking a look and the helpful edits!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

File: Facade_Engine/Query/FrameEdgeType.cs [hunk 18]
```diff
@@ -0,0 +1,72 @@
...
+    public static partial class Query
+    {
+        /***************************************************/
+        /****              Public methods               ****/
+        /***************************************************/
+
+        [Description("Returns edge type (Sill, Head, or Jamb) from a FrameEdge and the Opening it belongs to.")]
+        [Input("frameEdge", "FrameEdge to get edge type from.")]
+        [Input("opening", "Opening the FrameEdge belongs to.")]
+        [Input("jambMinAngle", "Minimum angle from horizontal (in radians) at which edges are considered jambs.")]
```
Comment (FraserGreenroyd) [inline Facade_Engine/Query/FrameEdgeType.cs:50]:
```suggestion
        [Input("jambMinimumAngle", "Minimum angle from horizontal (in radians) at which edges are considered jambs.")]
```

**Review by FraserGreenroyd — DISMISSED** [review]

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check installer

**Comment by enarhi** [comment]
@BHoMBot check versioning

**Comment by enarhi** [comment]
@BHoMBot check core

**Comment by enarhi** [comment]
@BHoMBot check serialisation

**Review by michaelhoehn — APPROVED** [review]
Approved based on functionality tests and code LGTM. 
Some feedback for future optimisation for `CurtainWall()`: 
- 100 panel solve time ~3.5s
- 200 panel solve time ~12.1s

So not quite scaling as expected, and could get quite heavy if used on more than one surface at a time. But happy to approve this anyway, just making a note here for future work! Some really helpful methods made here 😄

**Comment by enarhi** [comment]
Thanks @michaelhoehn, optimizations will follow for the create method and the query and compute methods on the back of some benchmarking with project use cases. Appreciate the elapsed time checks, very useful!

File: Facade_Engine/Create/Elements/CurtainWall.cs [hunk 19]
```diff
@@ -0,0 +1,165 @@
...
+        public static CurtainWall CurtainWall(IEnumerable<ICurve> outlines, IEnumerable<IConstruction> constructions = null, FrameEdgeProperty headProperty = null, FrameEdgeProperty jambProperty = null, FrameEdgeProperty sillProperty = null, FrameEdgeProperty externalHeadProperty = null, FrameEdgeProperty externalJambProperty = null, FrameEdgeProperty externalSillProperty = null, string name = "")
+        {
+            if(outlines == null)
+            {
+                BH.Engine.Reflection.Compute.RecordError("Cannot create a CurtainWall from a null collection of outlines.");
+                return null;
+            }
+
+            bool useConstructions = true;
+            if (outlines.Count() != constructions.Count())
```
Comment (FraserGreenroyd) [inline Facade_Engine/Create/Elements/CurtainWall.cs:65]: If `constructions` are `null` then this method call will fail.

File: Facade_Engine/Compute/AdjacentElements.cs [hunk 20]
```diff
@@ -43,49 +43,63 @@ public static partial class Compute
...
+        [Input("element", "Element to find adjacencies at.")]
+        [Input("referenceElements", "Elements to use to find element adjacencies.")]
+        [Output("adjacentElements", "Adjacents elements to the provided element.")]
+        public static List<IElement2D> AdjacentElements(this IElement2D element, List<IElement2D> referenceElements)
         {
-            List<IElement2D> adjElems = new List<IElement2D>();
+            List<IElement2D> adjacentElements = new List<IElement2D>();
 
-            PolyCurve outline = elem.OutlineCurve();
+            PolyCurve outline = element.OutlineCurve();
```
Comment (FraserGreenroyd) [inline Facade_Engine/Compute/AdjacentElements.cs:53]: What if `element` is null?

File: Facade_Engine/Compute/AdjacentElements.cs [hunk 21]
```diff
@@ -43,49 +43,63 @@ public static partial class Compute
...
+        [Input("element", "Element to find adjacencies at.")]
+        [Input("referenceElements", "Elements to use to find element adjacencies.")]
+        [Output("adjacentElements", "Adjacents elements to the provided element.")]
+        public static List<IElement2D> AdjacentElements(this IElement1D element, List<IElement2D> referenceElements)
         {
-            List<IElement2D> adjElems = new List<IElement2D>();
+            List<IElement2D> adjacentElements = new List<IElement2D>();
 
-            PolyCurve outline = elem.ElementCurves().IJoin()[0];
+            PolyCurve outline = element.ElementCurves().IJoin()[0];
```
Comment (FraserGreenroyd) [inline Facade_Engine/Compute/AdjacentElements.cs:78]: Same here

File: Facade_Engine/Compute/AdjacentElements.cs [hunk 22]
```diff
@@ -43,49 +43,63 @@ public static partial class Compute
...
+        /***************************************************/
+
+        [Description("Returns elements adjacent to a provided Element1D from a collection of elements.")]
+        [Input("element", "Element to find adjacencies at.")]
+        [Input("referenceElements", "Elements to use to find element adjacencies.")]
+        [Output("adjacentElements", "Adjacent elements to the provided element.")]
+        public static List<IElement1D> AdjacentElements(this IElement1D element, List<IElement1D> referenceElements)
+
+        {
+            return referenceElements.Where(x => x.IIsAdjacent(element)).ToList();
```
Comment (FraserGreenroyd) [inline Facade_Engine/Compute/AdjacentElements.cs:102]: What if `element` is null? Or `referenceElements`?

File: Facade_Engine/Create/Elements/CurtainWall.cs [hunk 23]
```diff
@@ -0,0 +1,165 @@
...
+            {
+                BH.Engine.Reflection.Compute.RecordWarning("Outline and Construction list lengths do not match. CurtainWall will be created with no Opening Constructions applied.");
+                useConstructions = false;
+            }
+
+            externalHeadProperty = externalHeadProperty ?? headProperty;
+            externalJambProperty = externalJambProperty ?? jambProperty;
+            externalSillProperty = externalSillProperty ?? sillProperty;
```
Comment (FraserGreenroyd) [inline Facade_Engine/Create/Elements/CurtainWall.cs:73]: What if the head, jamb, or sill properties are also `null`?

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

**Comment by enarhi** [comment]
@BHoMBot check null handling

**Review by FraserGreenroyd — APPROVED** [review]
LGTM following latest discussion and review with @enarhi
