### PR TITLE
Environmental_Engine: Removed AddOpening method

### LINKED ISSUE #3116: Environments_Engine Add Opening method removal
#### What is missing/incorrect?

Is the AddOpening still in use? It seems like AddOpenings covers its functionality. Deleting the method would make the UX a bit better.

image

### PR DESCRIPTION
**Pull request by albinber**
### Issues addressed by this PR

Closes #3116

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

File: Environment_Engine/Modify/AddOpening.cs [hunk 1]
```diff
@@ -38,36 +38,13 @@ public static partial class Modify
...
-        [Input("centroidTolerance", "Set the tolerance for obtaining the centroid of openings, default is set to BH.oM.Geometry.Tolerance.Distance")]
-        [Input("containingTolerance", "Set the tolerance for determining geometric association of openings to panels, default is set to BH.oM.Geometry.Tolerance.Distance")]
-        [Output("panels", "A collection of modified Environment Panels with the provided openings added")]
+        [Input("panels", "A collection of Environment Panels to add the opening to.")]
+        [Input("openings", "A collection of Environment Openings to add to the panels.")]
+        [Input("centroidTolerance", "Set the tolerance for obtaining the centroid of openings, default is set to BH.oM.Geometry.Tolerance.Distance.")]
+        [Input("containingTolerance", "Set the tolerance for determining geometric association of openings to panels, default is set to BH.oM.Geometry.Tolerance.Distance.")]
+        [Output("panels", "A collection of modified Environment Panels with the provided openings added.")]
+        [PreviousVersion("6.3", "BH.Engine.Environment.Compute.AddOpening(BH.oM.Environment.Elements.Panel, BH.oM.Environment.Elements.Opening).")]
```
Comment (FraserGreenroyd) [inline Environment_Engine/Modify/AddOpening.cs:47]:
```suggestion
        [PreviousVersion("6.3", "BH.Engine.Environment.Modify.AddOpening(BH.oM.Environment.Elements.Panel, BH.oM.Environment.Elements.Opening).")]
```

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

File: Environment_Engine/Modify/AddOpening.cs [hunk 2]
```diff
@@ -38,36 +38,13 @@ public static partial class Modify
...
-        [Input("centroidTolerance", "Set the tolerance for obtaining the centroid of openings, default is set to BH.oM.Geometry.Tolerance.Distance")]
-        [Input("containingTolerance", "Set the tolerance for determining geometric association of openings to panels, default is set to BH.oM.Geometry.Tolerance.Distance")]
-        [Output("panels", "A collection of modified Environment Panels with the provided openings added")]
+        [Input("panels", "A collection of Environment Panels to add the opening to.")]
+        [Input("openings", "A collection of Environment Openings to add to the panels.")]
+        [Input("centroidTolerance", "Set the tolerance for obtaining the centroid of openings, default is set to BH.oM.Geometry.Tolerance.Distance.")]
+        [Input("containingTolerance", "Set the tolerance for determining geometric association of openings to panels, default is set to BH.oM.Geometry.Tolerance.Distance.")]
+        [Output("panels", "A collection of modified Environment Panels with the provided openings added.")]
+        [PreviousVersion("6.3", "BH.Engine.Environment.Modify.AddOpening(BH.oM.Environment.Elements.Panel, BH.oM.Environment.Elements.Opening).")]
```
Comment (FraserGreenroyd) [inline Environment_Engine/Modify/AddOpening.cs:47]:
```suggestion
        [PreviousVersion("6.3", "BH.Engine.Environment.Modify.AddOpening(BH.oM.Environment.Elements.Panel, BH.oM.Environment.Elements.Opening)")]
```

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge
