### PR TITLE
BHoM_Engine: Fix SetProperty of numbers represented as strings

### LINKED ISSUE #2918: SetProperty doesn't work if a number is provided as a string
#### Description:
Numbers represented as strings are not converted. This is relevant for both Excel and numbers in panels in Grasshopper.

#### Steps to reproduce:
image

#### Expected behaviour:
The string should be automatically converted

#### Test file(s):
See image above

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #2918

Numbers represented as strings are not converted. This is relevant for both Excel and numbers in panels in Grasshopper.
The string should be automatically converted.

### Test files
image

### CODE REVIEW

File: BHoM_Engine/Modify/SetPropertyValue.cs [hunk 1]
```diff
@@ -87,24 +87,48 @@ public static object SetPropertyValue(this object obj, string propName, object v
...
+                        int result = 0;
+                        int.TryParse(value as string, out result);
+                        value = result;
+                    }
+                    else if (propType == typeof(bool))
+                    {
+                        bool result = false;
+                        bool.TryParse(value as string, out result);
+                        value = result;
+                    }
```
Comment (adecler) [inline BHoM_Engine/Modify/SetPropertyValue.cs:131]: This is the only real code change. The rest is just existing code all moved under a single check for string vale for simplicity.

**Review by FraserGreenroyd — APPROVED** [review]
Approving based on code review, roll out via alpha for wider testing support.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge
