### PR TITLE
Structure_Engine: Off-centre section issues

### LINKED ISSUE #1657: Structure_Engine: Off-centre section issues
#### Description:

https://github.com/BHoM/BHoM_Engine/blob/9ea9155f8dcd6ed0fdb020e1ae99e2f2f39790eb/Structure_Engine/Compute/IntegrateSection.cs#L97
This creates a singular `BoundingBox` at Origo, which will then be a part of the total `BoundingBox` for the section. This means that the placement of the section curves in the XY-plane affects the section properties. This shouldn't happen as the section after this has it's position adjusted, with no corresponding change in values.

IMG: four identical section edges with different section property values
image

FYI @IsakNaslundBh 

Would suggest adding a metod in Geometry_Engine which gets the total bounding box from a collection of `BoundingBoxes` to reduce the amount of people who make this mistake
#### Steps to reproduce:

Create a freefrom section away from the origo on the XY plane

#### Expected behaviour:

the edges on the section should have the same property values as the section

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/EpXcV7sd78dOksKEPpfFg3oB4AgrgAKGQ18kYHcORuzmsA?e=5hG7pm

### LINKED ISSUE #1658: Geometry_Engine: Add Bounds(List<BoundingBox> boxes)
#### Description:
A method which gets the combined `BoundingBox` for a collection of boxes

would reduce incidents like these: #1657

### PR DESCRIPTION
**Pull request by kThorsager**
### Issues addressed by this PR
Closes #1657 
Closes #1658 

### Test files
https://burohappold.sharepoint.com/:f:/s/BHoM/EsCnlfKi1CVKl2RxG-SXCEUBuXEWwwikU8m6BwmSjoqaVQ?e=7tKiR3

### Changelog
- Adds Geometry.Query.Bounds(List<BoundingBox> boxes)

### CODE REVIEW

File: Structure_Engine/Compute/Integrate.cs [hunk 1]
```diff
@@ -51,12 +51,7 @@ public static partial class Compute
         {
             Dictionary<string, object> results = new Dictionary<string, object>();
 
-            BoundingBox box = new BoundingBox();
-
-            for (int i = 0; i < curves.Count; i++)
-            {
-                box += curves[i].IBounds();
-            }
+            BoundingBox box = Geometry.Query.Bounds(curves.Select(x => x.IBounds()).ToList());
```
Comment (epignatelli) [inline Structure_Engine/Compute/Integrate.cs:54]: Have you tried using `curvers.Sum(x => x.IBounds())`? I think it should do the same thing and can avoid adding a new method?

File: Structure_Engine/Compute/IntegrateSection.cs [hunk 2]
```diff
@@ -94,9 +94,7 @@ public static partial class Compute
                 area += Math.Abs(areaTemp) * depth[i];
             }
 
-            BoundingBox box = new BoundingBox();
-            for (int i = 0; i < curvesZ.Count; i++)
-                box += curvesZ[i].IBounds();
+            BoundingBox box = Geometry.Query.Bounds(curvesZ.Select(x => x.IBounds()).ToList());
```
Comment (epignatelli) [inline Structure_Engine/Compute/IntegrateSection.cs:97]: Ditto

File: Geometry_Engine/Query/Bounds.cs [hunk 3]
```diff
@@ -386,6 +387,27 @@ public static BoundingBox Bounds(this List<Point> pts)
 
         /***************************************************/
 
+        public static BoundingBox Bounds(this List<BoundingBox> boxes)
```
Comment (epignatelli) [inline Geometry_Engine/Query/Bounds.cs:390]: If we want to keep this, we can just use the operator `+` between `BoundingBox`es maybe?

File: Structure_Engine/Compute/Integrate.cs (hunk 1 above)
Comment (kThorsager) [reply Structure_Engine/Compute/Integrate.cs:54]: Yes, `Sum` only returns numbers, so no dice

File: Geometry_Engine/Query/Bounds.cs (hunk 3 above)
Comment (kThorsager) [reply Geometry_Engine/Query/Bounds.cs:390]: If you'd like, I just went straight for the definition, (mostly for the aesthetics of avoiding assigning the first value and then looping over the rest of them, but maybe silly)

File: Structure_Engine/Compute/Integrate.cs (hunk 1 above)
Comment (kThorsager) [reply Structure_Engine/Compute/Integrate.cs:54]: I did however now find this way:
`            return boxes.Aggregate((x, y) => x + y);
`
which ofc would work, but adding the method was also to avoid the mistake in #1657 by having a method for it, (and we have one for `List<Point>` which can also be solved in the same way, (know that two wrongs don't make it right, but still))

**Comment by epignatelli** [comment]
@BHoM/bhom_engine can merge for me if checks succeed!

**Comment by FraserGreenroyd** [comment]
I'd want to see a review from @IsakNaslundBh as there is also structure engine changes just to be double-safe :smile:
