### PR TITLE
Environment engine Bug Fixes and Enhancements

### LINKED ISSUE #1139: Environment_Engine: Panel check
#### Description:

Add set of checks for Panels before we export to gbXML to verify model

- [ ] nr of adj space for panel
- [ ] check if we need 2, that are different space
- [ ] check if area > panelArea
- [ ] check if edge > panelEdgeLength
- [ ] check if polyline closed
- [ ] check if polyline intersect

### LINKED ISSUE #1141: Environment_Engine: FloorGeometry return wrong polyline
#### Description:
currently if we have complex space like this it returns what we see as green and should ne as yellow
image

#### How to replicate:

run attached script

#### Test file(s):

[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-Issue-1141%20FloorGeometry?csf=1&e=HRZ9og)

### LINKED ISSUE #1144: Environment_Engine: MergePanelsByGeometry
#### Description:
Allow merging panels by geometry if share same properties
image

### LINKED ISSUE #1149: Environment_Engine: ToSpace fix
#### Description:

1. Add warning is Space was not found,
2. Add warning if Space is made of less then 5 panels
Add new method that will work on List of Space Names to review if all spaces can be built from the list of panels

image

### LINKED ISSUE #1151: Geometry_Engine: Add MergeLine
#### Description:

Add MergeLine
Allow merging two Lines, iCurves with tolerance input

image
image

### LINKED ISSUE #1165: Environment_Engine: Tilt bug
#### Description:

When we have wall with tilt 90deg due to our tolerance could like that 
image

this is causing wrong element selection
 
image

#### How to replicate:

run test file

#### Test file(s):

[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-Issue-1165%20TiltBug?csf=1&e=95kqiS)

### LINKED ISSUE #1166: Environment_Engine: Query Roof, Floor, Wall Panels
#### Description:

Add method to pull from PanelAsSpaces appropriate panels and assign types to allow GH workflow before generating valid gbXML
- [ ] FloorPanels
- [ ] RoofPanels
- [ ] WallPanels
- [ ] ShadePanels

### PR DESCRIPTION
**Pull request by michaldengusiak**
### Issues addressed by this PR

Fixes #1139 
Fixes #1141 
Fixes #1144 
Fixes #1149 
Fixes #1151
Fixes #1165 
Fixes #1166 

### Test files

[test file
](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-Issue-1141%20FloorGeometry?csf=1&e=HRZ9og)
### Changelog

- Added `InvalidPanels`
- Added Fix for a `FloorGeometry`
- Added warning to `ToSpace`
- Added new `ToSpace` to support list
- Added Query for Wall, Floor, Roof, Shade
- Fix Tilt and improve point selection for plane

### CODE REVIEW

File: Geometry_Engine/Modify/CleanPolyline.cs [hunk 1]
```diff
@@ -36,11 +36,12 @@ public static partial class Modify
...
         [Input("polyline", "The polyline you wish to clean by removing unnecessary points")]
-        [Input("tolerance", "The tolerance of the angle that defines a straight line. Default is set to the value defined by BH.oM.Geometry.Tolerance.Angle")]
+        [Input("angleTolerance", "The tolerance of the angle that defines a straight line. Default is set to the value defined by BH.oM.Geometry.Tolerance.Angle")]
+        [Input("distanceTolerance", "The distance between two point that should be removed. Default is set to the value 0.02")]
         [Output("polyline", "The cleaned polyline")]
-        public static Polyline CleanPolyline(this Polyline polyline, double angleTolerance = Tolerance.Angle, double distanceTolerance = Tolerance.Distance)
+        public static Polyline CleanPolyline(this Polyline polyline, double angleTolerance = Tolerance.Angle, double distanceTolerance = 0.02)
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/CleanPolyline.cs]: I believe this should stay as before, `double distanceTolerance = Tolerance.Distance` too keep consistence across the whole repo. The default value can then be changed locally in further, discipline-specific methods.

Comment (michaldengusiak) [reply Geometry_Engine/Modify/CleanPolyline.cs]: modified as discussed, this is not tolerance

File: Environment_Engine/Query/FloorGeometry.cs [hunk 2]
```diff
@@ -63,7 +63,14 @@ public static Polyline FloorGeometry(this List<Panel> panelsAsSpace, double tole
 
             if (floorGeometry.Count < 1) return null;
 
-            return floorGeometry[0];
+                Polyline max = floorGeometry[0];
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/FloorGeometry.cs]: Use a `LINQ` query rather than this `for` loop. If a `for` loop is necessary can it be properly formatted.

Comment (FraserGreenroyd) [inline Environment_Engine/Query/FloorGeometry.cs]: If a `LINQ` query is not possible, can we name this variable better.

File: Environment_Engine/Query/InvalidPanels.cs [hunk 3]
```diff
@@ -0,0 +1,144 @@
...
+
+namespace BH.Engine.Environment
+{
+    public static partial class Query
+    {
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+
+        [Description("Return a collection of panels which we identified Invalid data 1-external adj space, 2-shade check, 3-internal adj space, 4-internal two diff spaces, 5-area to small, 6-segment to short, 7-polyline closed, 8-poltyline interesect")]
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/InvalidPanels.cs]: This description needs tidying up and making more legible. I don't understand from reading this description what this method is actually going to do.
Descriptions should be clear, concise, and not use informal language.

File: Environment_Engine/Query/InvalidPanels.cs [hunk 4]
```diff
@@ -0,0 +1,144 @@
...
+        [Input("panels", "A collection of environment panels")]
+        [Input("panelArea", "A min panel area to return warning")]
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/InvalidPanels.cs]: Include what the default is on any inputs which have default inputs.

File: Environment_Engine/Query/InvalidPanels.cs [hunk 5]
```diff
@@ -0,0 +1,144 @@
...
+        [Input("panelEdgeLength", "A min panelEdgeLength to return warning")]
+        [Output("invalidPanels", "A collection of panels which are invalid group in sublist for each of 8 checks that we perform, see description")]
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/InvalidPanels.cs]: Same as description, this output description needs to be readable, and not in informal language.

File: Environment_Engine/Query/InvalidPanels.cs [hunk 6]
```diff
@@ -0,0 +1,144 @@
...
+        public static List<List<Panel>> InvalidPanels(this List<Panel> panels, double panelArea = 0.15, double panelEdgeLength = 0.15)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/InvalidPanels.cs]: These tolerances should be related to the Geometry Tolerance again. There is no immediate basis for these tolerances so we should stick with the defaults from Geometry oM.

File: Environment_Engine/Query/InvalidPanels.cs [hunk 7]
```diff
@@ -0,0 +1,144 @@
...
+        {
+            List<List<Panel>> rtn = new List<List<Panel>>();
+
+            for (int i = 0; i < 8; i++)
+                rtn.Add(new List<Panel>());
+            foreach (Panel p in panels)
+
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/InvalidPanels.cs]: This file needs tidying up entirely to fix poor formatting.

File: Environment_Engine/Query/InvalidPanels.cs [hunk 8]
```diff
@@ -0,0 +1,144 @@
...
+            {
+                //check for external
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/InvalidPanels.cs]: What does this comment serve to do? Comments in code should serve to explain what the code is doing that isn't obvious from other documentation around. This particular comment does not meet that standard. Either remove it, or make it more useful for describing what's going on.

File: Environment_Engine/Query/InvalidPanels.cs [hunk 9]
```diff
@@ -0,0 +1,144 @@
...
+                if ((p.Type == PanelType.Roof || p.Type == PanelType.WallExternal || p.Type == PanelType.FloorExposed || p.Type == PanelType.FloorRaised || p.Type == PanelType.SlabOnGrade || p.Type == PanelType.UndergroundSlab || p.Type == PanelType.UndergroundWall) && p.ConnectedSpaces.Count != 1)
+                {
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/InvalidPanels.cs]: Remove these brackets is everything is just a single line `Add` to the list.

File: Environment_Engine/Query/InvalidPanels.cs [hunk 10]
```diff
@@ -0,0 +1,144 @@
...
+        [Input("panelArea", "A min panel area to return warning")]
+        [Input("panelEdgeLength", "A min panelEdgeLength to return warning")]
+        [Output("invalidPanels", "A collection of panels which are invalid group in sublist for each of 8 checks that we perform, see description")]
+        public static List<List<Panel>> InvalidPanels(this List<Panel> panels, double panelArea = 0.15, double panelEdgeLength = 0.15)
+        {
+            List<List<Panel>> rtn = new List<List<Panel>>();
+
+            for (int i = 0; i < 8; i++)
+                rtn.Add(new List<Panel>());
+            foreach (Panel p in panels)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/InvalidPanels.cs]: Add a blank line above this `for` loop.

File: Environment_Engine/Query/InvalidPanels.cs [hunk 11]
```diff
@@ -0,0 +1,144 @@
...
+
+                }
+
+                //check if geometry area is too small
+                if (p.Area() < panelArea)
+                {
+
+                    rtn[4].Add(p);
+                }
+                else
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/InvalidPanels.cs]: Why is this else statement here? Why are we only checking edge length if the area is bigger than tolerance? Why can't we check this as well?

File: Environment_Engine/Query/InvalidPanels.cs [hunk 12]
```diff
@@ -0,0 +1,144 @@
...
+
+                            rtn[5].Add(p);
+                            break;
+                        }
+                    }
+                }
+
+
+                //check if panel polyline is closed
+                if (Geometry.Query.IsClosed(p.Polyline()) == false)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/InvalidPanels.cs]: Use the `!` operator for `false` operations rather than `== false`

File: Environment_Engine/Query/InvalidPanels.cs [hunk 13]
```diff
@@ -0,0 +1,144 @@
...
+                {
+
+                    rtn[6].Add(p);
+                }
+
+                //check if self intersect
+                if (Geometry.Query.IsClosed(p.Polyline()) == false)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/InvalidPanels.cs]: This check is irrelevant as it's the same as the one above it... remove it

File: Environment_Engine/Query/InvalidPanels.cs [hunk 14]
```diff
@@ -0,0 +1,144 @@
...
+                {
+
+                    rtn[7].Add(p);
+                }
+            }
+
+            if (rtn[0].Count > 0)
+                    BH.Engine.Reflection.Compute.RecordWarning("external panels must have 1 adj space");
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/InvalidPanels.cs]: These warnings need to be properly formatted and useful to the users.

File: Environment_Engine/Query/InvalidPanels.cs [hunk 15]
```diff
@@ -0,0 +1,144 @@
...
+        /***************************************************/
+
+        [Description("Return a collection of panels which we identified Invalid data 1-external adj space, 2-shade check, 3-internal adj space, 4-internal two diff spaces, 5-area to small, 6-segment to short, 7-polyline closed, 8-poltyline interesect")]
+        [Input("panels", "A collection of environment panels")]
+        [Input("panelArea", "A min panel area to return warning")]
+        [Input("panelEdgeLength", "A min panelEdgeLength to return warning")]
+        [Output("invalidPanels", "A collection of panels which are invalid group in sublist for each of 8 checks that we perform, see description")]
+        public static List<List<Panel>> InvalidPanels(this List<Panel> panels, double panelArea = 0.15, double panelEdgeLength = 0.15)
+        {
+            List<List<Panel>> rtn = new List<List<Panel>>();
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/InvalidPanels.cs]: Can we name this variable something better please.

File: Environment_Engine/Query/Space.cs [hunk 16]
```diff
@@ -44,7 +44,30 @@ public static partial class Query
         [Output("panelsAsSpace", "A collection of Environment Panels which have the given space name as a connected space")]
         public static List<Panel> ToSpace(this List<Panel> panels, string spaceName)
         {
-            return panels.Where(x => x.ConnectedSpaces.Contains(spaceName)).ToList();
+            List<Panel> result= panels.Where(x => x.ConnectedSpaces.Contains(spaceName)).ToList();
+            if(result.Count==0)
+                BH.Engine.Reflection.Compute.RecordWarning("Could not find following space: " + spaceName);
+            if(result.Count > 0 && result.Count<5)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Space.cs]: Delete this, there is no issue raised for this use case and it does not aid anything to the user.

File: Environment_Engine/Query/Space.cs [hunk 17]
```diff
@@ -44,7 +44,30 @@ public static partial class Query
         [Output("panelsAsSpace", "A collection of Environment Panels which have the given space name as a connected space")]
         public static List<Panel> ToSpace(this List<Panel> panels, string spaceName)
         {
-            return panels.Where(x => x.ConnectedSpaces.Contains(spaceName)).ToList();
+            List<Panel> result= panels.Where(x => x.ConnectedSpaces.Contains(spaceName)).ToList();
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Space.cs]: Fix the formatting on this method.

File: Environment_Engine/Query/Space.cs [hunk 18]
```diff
@@ -44,7 +44,30 @@ public static partial class Query
...
+
+            return result;
+
+        }
+
+        [Description("Returns a collection of Environment Panels which are connected to the list of space names provided")]
+        [Input("panels", "A collection of Environment Panels")]
+        [Input("spaceNames", " list of space names the panels should enclose")]
+        [Output("panelsAsSpace", "A collection of Environment Panels which have the given space name as a connected space")]
+        public static List<List<Panel>> ToSpace(this List<Panel> panels, List<string> spaceNames)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Space.cs]: Remove this method, there is no issue raised listed in this PR or elsewhere which describes the requirement for this method.

This method adds nothing that cannot be handled by the methods already existing within this file.

File: Geometry_Engine/Modify/CleanPolyline.cs [hunk 19]
```diff
@@ -36,14 +36,19 @@ public static partial class Modify
         /**** Public Methods                            ****/
         /***************************************************/
 
-        [Description("Returns a polyline defined by the points which result in deviations from a straight line only. For example, if a polyline has 3 points in a straight line, the middle point is removed as part of this cleaning process. This is designed for closed polylines only")]
+        [Description("Returns a polyline defined by the points which result in deviations from a straight line only. For example, if a polyline has 3 points in a straight line, the middle point is removed as part of this cleaning process if distance betwen point is less than distanceTolerance. This is designed for closed polylines only")]
```
Comment (FraserGreenroyd) [inline Geometry_Engine/Modify/CleanPolyline.cs]: The change to this description is fundamentally incorrect. The middle point is always removed in a straight line, regardless of the `distanceTolerance`

File: Geometry_Engine/Modify/CleanPolyline.cs [hunk 20]
```diff
@@ -36,14 +36,19 @@ public static partial class Modify
...
         [Input("polyline", "The polyline you wish to clean by removing unnecessary points")]
-        [Input("tolerance", "The tolerance of the angle that defines a straight line. Default is set to the value defined by BH.oM.Geometry.Tolerance.Angle")]
+        [Input("angleTolerance", "The tolerance of the angle that defines a straight line. Default is set to the value defined by BH.oM.Geometry.Tolerance.Angle")]
+        [Input("distanceTolerance", "The distance between two point that should be removed. Default is set to the value 0.02")]
```
Comment (FraserGreenroyd) [inline Geometry_Engine/Modify/CleanPolyline.cs]: Correct the default on this input description

File: Geometry_Engine/Modify/CleanPolyline.cs [hunk 21]
```diff
@@ -36,14 +36,19 @@ public static partial class Modify
...
         [Output("polyline", "The cleaned polyline")]
         public static Polyline CleanPolyline(this Polyline polyline, double angleTolerance = Tolerance.Angle, double distanceTolerance = Tolerance.Distance)
+
+        // I recommend we replace name from distanceTolerance to minimumSegmentLength as below ,I will keep right now as we need to fix aslo XML Toolkit
```
Comment (FraserGreenroyd) [inline Geometry_Engine/Modify/CleanPolyline.cs]: Remove this comment, it is not suitable for this platform.

File: Environment_Engine/Compute/MergeBuildingElements.cs [hunk 22]
```diff
@@ -57,5 +60,60 @@ public static Panel MergePanels(this Panel panel1, Panel panel2)
             
             return rtnPanel;
         }
+
+        [Description("merges the properties two Environment Panels together and returns panel with boolean geometry")]
```
[the remark this answers is not in the document]
Comment (michaldengusiak) [reply Environment_Engine/Compute/MergeBuildingElements.cs]: done

File: Environment_Engine/Compute/MergeBuildingElements.cs [hunk 23]
```diff
@@ -57,5 +60,60 @@ public static Panel MergePanels(this Panel panel1, Panel panel2)
...
+        [Input("panel1", "An Environment Panel to merge from")]
+        [Input("panel2", "A second Environment Panel to merge from")]
+        [Output("mergedPanel", "The Environment Panel with the smallest area of the two provided but with the combined properties of both")]
```
[the remark this answers is not in the document]
Comment (michaldengusiak) [reply Environment_Engine/Compute/MergeBuildingElements.cs]: done

File: Environment_Engine/Compute/MergeBuildingElements.cs [hunk 24]
```diff
@@ -57,5 +60,60 @@ public static Panel MergePanels(this Panel panel1, Panel panel2)
...
+        public static Panel MergePanelsByGeometryOnly(this Panel panel1, Panel panel2, double tolerance = 0.00001)
```
[the remark this answers is not in the document]
Comment (michaldengusiak) [reply Environment_Engine/Compute/MergeBuildingElements.cs]: done

[the remark this answers is not in the document]
Comment (michaldengusiak) [reply Environment_Engine/Compute/MergeBuildingElements.cs]: done

File: Environment_Engine/Compute/MergeBuildingElements.cs [hunk 25]
```diff
@@ -57,5 +60,60 @@ public static Panel MergePanels(this Panel panel1, Panel panel2)
...
+        {
+            Panel rtnPanel = null;
+
+            if (panel1.Area() > panel2.Area())
```
[the remark this answers is not in the document]
Comment (michaldengusiak) [reply Environment_Engine/Compute/MergeBuildingElements.cs]: it is, this method is to fix small unnecessary panels and merge them with large panels adj to panel. Therefore we need to keep the properties of a large panel.

File: Environment_Engine/Compute/MergeBuildingElements.cs [hunk 26]
```diff
@@ -57,5 +60,60 @@ public static Panel MergePanels(this Panel panel1, Panel panel2)
...
+                panels.Add(panel2);
+
+                //List<Polyline> pLines = new List<Polyline>();
+                //pLines.Add(panel1.Polyline());
+                //pLines.Add(panel2.Polyline());
+
+                List<Polyline> pLines = panels.Select(x => x.Polyline()).ToList();
+                List<Polyline> newGeometry = pLines.BooleanUnion(tolerance);
+
+                if (newGeometry.Count < 1) return null;
```
[the remark this answers is not in the document]
Comment (michaldengusiak) [reply Environment_Engine/Compute/MergeBuildingElements.cs]: done

File: Environment_Engine/Compute/MergeBuildingElements.cs [hunk 27]
```diff
@@ -57,5 +60,60 @@ public static Panel MergePanels(this Panel panel1, Panel panel2)
...
+                        max = pl;
+                }
+
+                rtnPanel = rtnPanel.SetGeometry(max);
+
+                return rtnPanel;
+
+            }
+
+            return null;
```
[the remark this answers is not in the document]
Comment (michaldengusiak) [reply Environment_Engine/Compute/MergeBuildingElements.cs]: done

File: Environment_Engine/Compute/MergeBuildingElements.cs [hunk 28]
```diff
@@ -57,5 +60,60 @@ public static Panel MergePanels(this Panel panel1, Panel panel2)
...
+
+
```
[the remark this answers is not in the document]
Comment (michaldengusiak) [reply Environment_Engine/Compute/MergeBuildingElements.cs]: done

File: Environment_Engine/Query/FloorGeometry.cs (hunk 2 above)
Comment (michaldengusiak) [reply Environment_Engine/Query/FloorGeometry.cs]: fix formatting, need advice on LINQ

File: Environment_Engine/Compute/MergeBuildingElements.cs [hunk 29]
```diff
@@ -57,5 +60,63 @@ public static Panel MergePanels(this Panel panel1, Panel panel2)
...
+            if (result)
+            {
+                rtnPanel.ConnectedSpaces = new List<string>(connectedSpaces);
+
+                List<Panel> panels = new List<Panel>();
+                panels.Add(panel1);
+                panels.Add(panel2);
+
+                //List<Polyline> pLines = new List<Polyline>();
```
Comment (FraserGreenroyd) [inline Environment_Engine/Compute/MergeBuildingElements.cs]: Can we delete this commented out code if it's not needed

File: Environment_Engine/Compute/MergeBuildingElements.cs [hunk 30]
```diff
@@ -57,5 +60,63 @@ public static Panel MergePanels(this Panel panel1, Panel panel2)
...
+                    if (pl.Area() > max.Area())
+                        max = pl;
+                }
+
+                rtnPanel = rtnPanel.SetGeometry(max);
+
+                return rtnPanel;
+
+            }
+            Reflection.Compute.RecordError("Panels have different ConnectedSpaces will not merge");
```
Comment (FraserGreenroyd) [inline Environment_Engine/Compute/MergeBuildingElements.cs]: Can we change this error message to something a little more human friendly such as "These panels do not belong to the same space(s) and cannot be merged together"?

File: Environment_Engine/Query/CheckAdjSpaces.cs [hunk 31]
```diff
@@ -0,0 +1,55 @@
+/*
```
[the remark this answers is not in the document]
Comment (FraserGreenroyd) [reply Environment_Engine/Query/CheckAdjSpaces.cs]: This file has still not been deleted

File: Environment_Engine/Query/FloorGeometry.cs [hunk 32]
```diff
@@ -63,7 +63,14 @@ public static Polyline FloorGeometry(this List<Panel> panelsAsSpace, double tole
 
             if (floorGeometry.Count < 1) return null;
 
-            return floorGeometry[0];
+                Polyline maxFloorGeometry = floorGeometry[0];
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/FloorGeometry.cs]: Fix the indenting on this, this block is indented one too far.

File: Environment_Engine/Query/Panels.cs [hunk 33]
```diff
@@ -290,5 +290,121 @@ public static List<Panel> PanelsFromPhysical(this List<BH.oM.Physical.Elements.I
...
             return panels;
         }
+
+        [Description("Returns the floor panels of a space represented by Environment Panels")]
+        [Input("panelsAsSpace", "A collection of Environment Panels that represent a closed space")]
+        [Output("floorPanels", "BHoM Environment panel representing the floor of the space")]
+        public static List<Panel> FloorPanels(this List<Panel> panelsAsSpace)
+        {
+            //Find the panel(s) that are at the lowest point of the space...
+
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Panels.cs]: Remove this blank line

File: Environment_Engine/Query/Panels.cs [hunk 34]
```diff
@@ -290,5 +290,121 @@ public static List<Panel> PanelsFromPhysical(this List<BH.oM.Physical.Elements.I
...
+            List<Panel> floorPanels = panelsAsSpace.Where(x => x.MinimumLevel() == minZ && x.MaximumLevel() == minZ).ToList();
+
+            foreach (Panel panel in floorPanels)
+            {
+                if (panel.ConnectedSpaces.Where(x => x != "-1").ToList().Count == 1)
+                    panel.Type = PanelType.SlabOnGrade;
+                else if (panel.ConnectedSpaces.Where(x => x != "-1").ToList().Count == 2)
+                    panel.Type = PanelType.FloorInternal;
+
+                if (floorPanels.Count == 0)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Panels.cs]: There is a failure in the logic here - this `if` statement will never execute because it is within the `for` loop. This `if` statement needs to be brought out of the `for` loop.

File: Environment_Engine/Query/Panels.cs [hunk 35]
```diff
@@ -290,5 +290,121 @@ public static List<Panel> PanelsFromPhysical(this List<BH.oM.Physical.Elements.I
...
+                {
+                    BH.Engine.Reflection.Compute.RecordWarning("Could not find roof panel");
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Panels.cs]: This should say `floor` panels right, not `roof`? Can we change the message to "Could not find any floor panels"

File: Environment_Engine/Query/Panels.cs [hunk 36]
```diff
@@ -290,5 +290,121 @@ public static List<Panel> PanelsFromPhysical(this List<BH.oM.Physical.Elements.I
 
             return panels;
         }
+
+        [Description("Returns the floor panels of a space represented by Environment Panels")]
+        [Input("panelsAsSpace", "A collection of Environment Panels that represent a closed space")]
+        [Output("floorPanels", "BHoM Environment panel representing the floor of the space")]
+        public static List<Panel> FloorPanels(this List<Panel> panelsAsSpace)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Panels.cs]: In hindsight, I think this functionality might be better off within the `Modify` class as that is fundamentally what is being done here, the `PanelType` is being modified based on some parameters, rather than just simply queried.

File: Environment_Engine/Query/Panels.cs [hunk 37]
```diff
@@ -290,5 +290,121 @@ public static List<Panel> PanelsFromPhysical(this List<BH.oM.Physical.Elements.I
...
+            return floorPanels;
+        }
+
+        [Description("Returns the roof panels of a space represented by Environment Panels")]
+        [Input("panelsAsSpace", "A collection of Environment Panels that represent a closed space")]
+        [Output("roofPanels", "BHoM Environment panel representing the roof of the space")]
+        public static List<Panel> RoofPanels(this List<Panel> panelsAsSpace)
+        {
+            //Find the panel(s) that are at the highest point of the space...
+
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Panels.cs]: Remove blank line

File: Environment_Engine/Query/Panels.cs [hunk 38]
```diff
@@ -290,5 +290,121 @@ public static List<Panel> PanelsFromPhysical(this List<BH.oM.Physical.Elements.I
...
+            double minZ = 1e10;
+            foreach (Panel panel in panelsAsSpace)
+            {
+                if (panel.MinimumLevel() == panel.MaximumLevel())
+                    minZ = Math.Min(minZ, panel.MinimumLevel());
+            }
+
+            List<Panel> roofPanels = panelsAsSpace.Where(x => ((x.MinimumLevel() != minZ && x.MaximumLevel() != minZ) && Math.Round(x.Tilt()) != 90) && x.ConnectedSpaces.ToList().Count == 1).ToList();
+
+            foreach (Panel panel in panelsAsSpace)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Panels.cs]: I think this `for` loop is incorrect, this should be on `roofPanels` rather than all of the space panels?

File: Environment_Engine/Query/Panels.cs [hunk 39]
```diff
@@ -290,5 +290,121 @@ public static List<Panel> PanelsFromPhysical(this List<BH.oM.Physical.Elements.I
...
+            {
+                if (roofPanels.Count == 0)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Panels.cs]: Same again, this `if` statement won't execute if you change the `for` loop and should be outside it.

File: Environment_Engine/Query/Panels.cs [hunk 40]
```diff
@@ -290,5 +290,121 @@ public static List<Panel> PanelsFromPhysical(this List<BH.oM.Physical.Elements.I
...
+                {
+                    BH.Engine.Reflection.Compute.RecordWarning("Could not find roof panel");
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Panels.cs]: Same again on changing the error message slightly, see previous comment.

File: Environment_Engine/Query/Panels.cs [hunk 41]
```diff
@@ -290,5 +290,121 @@ public static List<Panel> PanelsFromPhysical(this List<BH.oM.Physical.Elements.I
...
+            return roofPanels;
+        }
+
+        [Description("Returns the wall panels of a space represented by Environment Panels and fixes PanelType")]
+        [Input("panelsAsSpace", "A collection of Environment Panels that represent a closed space")]
+        [Output("wallPanels", "BHoM Environment panel representing the wall of the space")]
+        public static List<Panel> WallPanels(this List<Panel> panelsAsSpace)
+        {
+            //Find the panel(s) that ... is horizontal
+
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Panels.cs]: Remove blank line

File: Environment_Engine/Query/Panels.cs [hunk 42]
```diff
@@ -290,5 +290,121 @@ public static List<Panel> PanelsFromPhysical(this List<BH.oM.Physical.Elements.I
...
+            foreach (Panel panel in wallPanels)
+            {
+                if (panel.ConnectedSpaces.Where(x => x != "-1").ToList().Count == 1)
+                    panel.Type = PanelType.WallExternal;
+                else if (panel.ConnectedSpaces.Where(x => x != "-1").ToList().Count == 2)
+                    panel.Type = PanelType.WallInternal;
+
+
+                if (wallPanels.Count == 0)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Panels.cs]: Same again, `if` statement won't execute here ever.

File: Environment_Engine/Query/Panels.cs [hunk 43]
```diff
@@ -290,5 +290,121 @@ public static List<Panel> PanelsFromPhysical(this List<BH.oM.Physical.Elements.I
...
+            return wallPanels;
+        }
+
+        [Description("Returns the shade panels represented by Environment Panels with no adj spaces and fixes PanelType")]
+        [Input("panels", "A collection of Environment Panels")]
+        [Output("shadePanels", "BHoM Environment panel representing the shade")]
+        public static List<Panel> ShadePanels(this List<Panel> panels)
+        {
+            //Find the panel(s) without connected spaces and set as shade
+
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Panels.cs]: Remove blank line

File: Environment_Engine/Query/Space.cs (hunk 17 above)
Comment (FraserGreenroyd) [reply Environment_Engine/Query/Space.cs]: Formatting is still not fixed.

File: Environment_Engine/Query/Space.cs [hunk 44]
```diff
@@ -44,7 +44,14 @@ public static partial class Query
         [Output("panelsAsSpace", "A collection of Environment Panels which have the given space name as a connected space")]
         public static List<Panel> ToSpace(this List<Panel> panels, string spaceName)
         {
-            return panels.Where(x => x.ConnectedSpaces.Contains(spaceName)).ToList();
+            List<Panel> result= panels.Where(x => x.ConnectedSpaces.Contains(spaceName)).ToList();
+            if(result.Count==0)
+                BH.Engine.Reflection.Compute.RecordWarning("Could not find following space: " + spaceName);
+            if(result.Count > 0 && result.Count<5)
+                BH.Engine.Reflection.Compute.RecordWarning("This space have less than 5 planar panels " + result.Count +" : "+ spaceName);
```
Comment (FraserGreenroyd) [inline Environment_Engine/Query/Space.cs]: This error message needs fixing - we have never specified anything about `planar` panels previously, even if they should be planar, this is a random place to start using the word so remove that word. Just keep it at "less than 5 panels". Format the error message better to say what the `result.Count` refers to.

File: Geometry_Engine/Modify/CleanPolyline.cs (hunk 19 above)
Comment (FraserGreenroyd) [reply Geometry_Engine/Modify/CleanPolyline.cs]: Description still needs updating.

File: Geometry_Engine/Modify/CleanPolyline.cs (hunk 20 above)
Comment (FraserGreenroyd) [reply Geometry_Engine/Modify/CleanPolyline.cs]: Default is still incorrect.

File: Geometry_Engine/Modify/CleanPolyline.cs (hunk 21 above)
Comment (FraserGreenroyd) [reply Geometry_Engine/Modify/CleanPolyline.cs]: Comment still needs removing. It is right to capture the work that needs doing, but it should be in a GitHub issue or discussion, not a comment in code.

File: Environment_Engine/Compute/MergeBuildingElements.cs (hunk 29 above)
Comment (michaldengusiak) [reply Environment_Engine/Compute/MergeBuildingElements.cs]: done

File: Environment_Engine/Compute/MergeBuildingElements.cs (hunk 30 above)
Comment (michaldengusiak) [reply Environment_Engine/Compute/MergeBuildingElements.cs]: done

File: Environment_Engine/Query/FloorGeometry.cs (hunk 32 above)
Comment (michaldengusiak) [reply Environment_Engine/Query/FloorGeometry.cs]: done

File: Environment_Engine/Query/Panels.cs (hunk 33 above)
Comment (michaldengusiak) [reply Environment_Engine/Query/Panels.cs]: done

File: Environment_Engine/Query/Panels.cs (hunk 35 above)
Comment (michaldengusiak) [reply Environment_Engine/Query/Panels.cs]: done

File: Environment_Engine/Query/Panels.cs (hunk 34 above)
Comment (michaldengusiak) [reply Environment_Engine/Query/Panels.cs]: done

File: Environment_Engine/Query/Panels.cs (hunk 36 above)
Comment (michaldengusiak) [reply Environment_Engine/Query/Panels.cs]: current will be moved

File: Environment_Engine/Query/Panels.cs (hunk 37 above)
Comment (michaldengusiak) [reply Environment_Engine/Query/Panels.cs]: done

File: Environment_Engine/Query/Panels.cs (hunk 39 above)
Comment (michaldengusiak) [reply Environment_Engine/Query/Panels.cs]: done

File: Environment_Engine/Query/Panels.cs (hunk 40 above)
Comment (michaldengusiak) [reply Environment_Engine/Query/Panels.cs]: done

File: Environment_Engine/Query/Panels.cs (hunk 41 above)
Comment (michaldengusiak) [reply Environment_Engine/Query/Panels.cs]: done

File: Environment_Engine/Query/Panels.cs (hunk 42 above)
Comment (michaldengusiak) [reply Environment_Engine/Query/Panels.cs]: done

File: Environment_Engine/Query/Panels.cs (hunk 43 above)
Comment (michaldengusiak) [reply Environment_Engine/Query/Panels.cs]: done

File: Environment_Engine/Query/Space.cs (hunk 44 above)
Comment (michaldengusiak) [reply Environment_Engine/Query/Space.cs]: done

File: Environment_Engine/Modify/SetPanelType.cs [hunk 45]
```diff
@@ -119,5 +119,111 @@ public static List<Panel> SetPanelType(this List<Panel> panels, PanelType type)
 
             return panels;
         }
+
+        [Description("Returns the floor panels of a space represented by Environment Panels")]
+        [Input("panelsAsSpace", "A collection of Environment Panels that represent a closed space")]
+        [Output("floorPanels", "BHoM Environment panel representing the floor of the space")]
+        public static List<Panel> FloorPanels(this List<Panel> panelsAsSpace)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Modify/SetPanelType.cs]: Now the method is moved, can we call it `SetFloorPanels` instead - just a last thought I've had

File: Environment_Engine/Modify/SetPanelType.cs [hunk 46]
```diff
@@ -119,5 +119,111 @@ public static List<Panel> SetPanelType(this List<Panel> panels, PanelType type)
...
+            }
+
+
+            return floorPanels;
+        }
+
+        [Description("Returns the roof panels of a space represented by Environment Panels")]
+        [Input("panelsAsSpace", "A collection of Environment Panels that represent a closed space")]
+        [Output("roofPanels", "BHoM Environment panel representing the roof of the space")]
+        public static List<Panel> RoofPanels(this List<Panel> panelsAsSpace)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Modify/SetPanelType.cs]: Now the method is moved, can we call it `SetRoofPanels` instead - just a last thought I've had

File: Environment_Engine/Modify/SetPanelType.cs [hunk 47]
```diff
@@ -119,5 +119,111 @@ public static List<Panel> SetPanelType(this List<Panel> panels, PanelType type)
...
+                    panel.Type = PanelType.Roof;
+            }
+
+            return roofPanels;
+        }
+
+        [Description("Returns the wall panels of a space represented by Environment Panels and fixes PanelType")]
+        [Input("panelsAsSpace", "A collection of Environment Panels that represent a closed space")]
+        [Output("wallPanels", "BHoM Environment panel representing the wall of the space")]
+        public static List<Panel> WallPanels(this List<Panel> panelsAsSpace)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Modify/SetPanelType.cs]: Now the method is moved, can we call it `SetWallPanels` instead - just a last thought I've had

File: Environment_Engine/Modify/SetPanelType.cs [hunk 48]
```diff
@@ -119,5 +119,111 @@ public static List<Panel> SetPanelType(this List<Panel> panels, PanelType type)
...
+                    panel.Type = PanelType.WallInternal;
+            }
+
+            return wallPanels;
+        }
+
+        [Description("Returns the shade panels represented by Environment Panels with no adj spaces and fixes PanelType")]
+        [Input("panels", "A collection of Environment Panels")]
+        [Output("shadePanels", "BHoM Environment panel representing the shade")]
+        public static List<Panel> ShadePanels(this List<Panel> panels)
```
Comment (FraserGreenroyd) [inline Environment_Engine/Modify/SetPanelType.cs]: Now the method is moved, can we call it `SetShadePanels` instead - just a last thought I've had

File: Geometry_Engine/Modify/CleanPolyline.cs (hunk 19 above)
Comment (FraserGreenroyd) [reply Geometry_Engine/Modify/CleanPolyline.cs]: Description still needs updating on this particular line

File: Environment_Engine/Modify/SetPanelType.cs (hunk 45 above)
Comment (michaldengusiak) [reply Environment_Engine/Modify/SetPanelType.cs]: done

File: Environment_Engine/Modify/SetPanelType.cs (hunk 46 above)
Comment (michaldengusiak) [reply Environment_Engine/Modify/SetPanelType.cs]: done

File: Environment_Engine/Modify/SetPanelType.cs (hunk 47 above)
Comment (michaldengusiak) [reply Environment_Engine/Modify/SetPanelType.cs]: done

File: Environment_Engine/Modify/SetPanelType.cs (hunk 48 above)
Comment (michaldengusiak) [reply Environment_Engine/Modify/SetPanelType.cs]: done
