### PR TITLE
Geometry_Engine: Adding proper rigidness check to the Transform methods

### LINKED ISSUE #2339: Incorrect rigid transformation check in Geometry_Engine transforms
#### Description:

As proven in the test file for #2333, the determinant of the entire transform matrix equal to 1 is not equivalent to the transform being rigid. Instead, the rotation part of the matrix needs to be checked for two requirements ([source](https://en.wikipedia.org/wiki/Rigid_transformation)):
- R<sup>T</sup> == R<sup>-1</sup>
- det(R) == 1

This means that `Transform` methods in the Geometry_Engine need revisiting and updating the checks.

### PR DESCRIPTION
**Pull request by LMarkowski**
### Issues addressed by this PR

Closes #2339 

Replacing former matrix determinant check with new `IsRigidTransformation` query.

### Test files

[Here](https://burohappold.sharepoint.com/:f:/s/BHoM/En2Ibg00v25HmGzTJBBz76cBJaFHnTPrNFJoBsnZQo7SVQ?e=aRLQKc) sits the general test for transfom. We can also just run the unit test ☺️ 

### Changelog

- Added `IsRigidTransformation` check to the `Transform` methods in the `Geometry_Engine`.

### CODE REVIEW

**Comment by LMarkowski** [comment]
@BHoMBot check unit-tests

File: Geometry_Engine/Modify/Transform.cs [hunk 1]
```diff
@@ -124,7 +123,7 @@ public static ICurve Transform(this Circle curve, TransformMatrix transform)
                 };
             else
             {
-                Reflection.Compute.RecordNote("Transformation is not rigid. Converting into NurbsCurve. May occure change in shape");
+                Reflection.Compute.RecordNote("Transformation is not rigid or uniform. Converting into NurbsCurve. May occur change in shape");
```
Comment (pawelbaran) [inline Geometry_Engine/Modify/Transform.cs:126]:
```suggestion
                Reflection.Compute.RecordNote("Transformation is not rigid or uniform. Converting into NurbsCurve. Change in shape may occur.");
```

**Review by pawelbaran — COMMENTED** [review]
In general no rocket science, LGTM, I have only suggested a change on messaging (3x).

I also have one question: wouldn't it be worth adding `tolerance` parameter? This will align well with all other `Transform` methods in the engine.

**Comment by LMarkowski** [comment]
@pawelbaran, I've applied the suggestions to the messages. When it comes to passing the tolerance I'd delay it for two reasons:
1. It is en existing and quite a core feature. I'd rather not start doing the versioning for it during the testing sprint.
2. It is not exactly the distance tolerance anyway. Eventually it needs to be approached during the global tolerance rework.

**Review by pawelbaran — APPROVED** [review]
LGTM, agreed it may not be the best moment to introduce the tolerance as it will require versioning and extra testing. However, it would be good to have the one merging this PR to have a final look and confirm he/she is fine with chosen strategy.

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check serialisation

**Comment by pawelbaran** [comment]
@BHoMBot check versioning
