### PR TITLE
Structure_Engine: Refactor of Bar Reinforcement

### LINKED ISSUE #1609: Structure_Engine: Update getting reinforcement layout for a concrete section
#### Description:

Once Reinforcement has been updated in https://github.com/BHoM/BHoM/issues/579 the methods for getting all rebar positions should be updated to follow the new structure.

https://github.com/BHoM/BHoM_Engine/issues/1608

Method to take section curve and return the rebar point positions in relation to the section.

### LINKED ISSUE #1729: Geometry_Engine: Offset is fully crashing for Circles wrapped into polycurves
#### Description:

When a Circle is part of a Polycurve, it makes the offset method crash out badly. Will rely on this for reinforcement work, so would need to get sorted as a quite high priority

#### Steps to reproduce:

Create a polycurve with a circle in it and try offset

### LINKED ISSUE #1742: Matter_Engine: AggregateMaterialComposition runs a bit slow
#### Description:

Should ensure the hashes are only calculated once per material by storing the hashes and then post cleaning all of them off when finished.

### LINKED ISSUE #1775: Geometry_Engine: Normal for Polycurve and Polyline is sometimes returned in the wrong direction
#### Description:

Direction does not always correspond to that of IsCLockwise

#### Expected behaviour:

For IsClockwise and Normal to give consistent results

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/844
   
### Issues addressed by this PR

Closes #1609
Closes #1728 
Closes #1742 
Closes #1729 
Closes #1775 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EpXy3FR30txGs3Q3jTlTwOoBv9zjDu3k-0Z34O9CfSBIBQ?e=OO58dZ

Test of matter engine:

https://burohappold.sharepoint.com/:f:/s/BHoM/EkKKuT_RTYFAoLVZad5J9YkBfn3pm6ElXOonvELiJJqvcg?e=VIvdaP

Test offset:

https://burohappold.sharepoint.com/:f:/s/BHoM/EmsFjWvtqdlFj93FK71gVMwBq7Rou4vYir7Mq5w77UhDIA?e=hhWQ0W

### Changelog

- Refactoring required by changes to Reinforment objects in Structure_oM
- Make use of layout methods in Spacial_Engine to distribute reinforcement
- Pass over Rebar object to FramingElements when created from a structural Bar
- Tweaking `MaterialComposition` for `ConcreteSection`s to account for Reinforcement
- Fixing bug in Geometry_Engine making offsets crash when polycurve contains a circle
- Fixing issue in Matter_Engine, making sure hashes are only calculated once

### CODE REVIEW

File: Structure_Engine/Query/Geometry.cs [hunk 1]
```diff
@@ -101,8 +101,8 @@ public static CompositeGeometry Geometry(this ConcreteSection section)
                 return null;
 
             CompositeGeometry geom = Engine.Geometry.Create.CompositeGeometry(section.SectionProfile.Edges);
-            if(section.Reinforcement != null)
-                geom.Elements.AddRange(section.Layout().Elements);
+            //if(section.Reinforcement != null)
+                //geom.Elements.AddRange(section.Layout().Elements);
```
Comment (LMarkowski) [inline Structure_Engine/Query/Geometry.cs:105]: Is this code relevant?

Comment (IsakNaslundBh) [reply Structure_Engine/Query/Geometry.cs:105]: good catch! Actually, could be, if we want the reinforcement to be automatically displayed. question is if we want to or not, and ofc, it varies across the length (or can vary). Torn if to add it in or not! :)

**Comment by IsakNaslundBh** [comment]
Updating from master to get CI to behave. @LMarkowski do you mind re-checking?

File: Structure_Engine/Query/ReinforcementLayout.cs [hunk 2]
```diff
@@ -0,0 +1,207 @@
...
+            List<ICurve> outerProfileEdges;
+            List<ICurve> innerProfileEdges;
+
+            ExtractInnerAndOuterEdges(section, out outerProfileEdges, out innerProfileEdges);
+
+            //Need at least one external edge curve
+            if (outerProfileEdges.Count == 0)
+                return new List<Point>();
+
+            //TODO: include stirups for offset distance
```
Comment (kThorsager) [inline Structure_Engine/Query/ReinforcementLayout.cs:68]: Would add an issue instead of a TODO comment

File: Structure_Engine/Query/ReinforcingBars.cs [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+    public static partial class Query
+    {
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+
+        [Description("Extract all ReinforcingBars from the structural Bar. Only extract reinforcement for bars owning a ConcreteSection, for other sectiontypes, an empty list will be returned.")]
+        [Input("bar", "The structural Bar to extract Reinforcement from.")]
+        [Output("rebars", "All ReinforcingBar on the provided Bar.")]
+        public static List<IReinforcingBar> ReinforcingBars(this Bar bar)
```
Comment (kThorsager) [inline Structure_Engine/Query/ReinforcingBars.cs:51]: I would highlight in some manner that we're going from Structure objects to Physical objects. 
The difference between `IBarReinforcement` and `IReinforcingBar` is not big enough on its own

File: Structure_Engine/Query/ReinforcingBars.cs [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+            //Need at least one external edge curve
+            if (outerProfileEdges.Count == 0)
+                return new List<IReinforcingBar>();
+
+
+            TransformMatrix transformation = bar.BarSectionTranformation();
+            double length = bar.Length();
+
+            //TODO: include stirups for offset distance
+            double stirupOffset = 0;
```
Comment (kThorsager) [inline Structure_Engine/Query/ReinforcingBars.cs:78]: You forgot to add the minimum cover of the section.

Hence ReinformentLayout and the FramingElement form do not match

File: Structure_Engine/Query/ReinforcingBars.cs [hunk 5]
```diff
@@ -0,0 +1,108 @@
...
+
+            foreach (LongitudinalReinforcement reif in longReif)
+            {
+                Material material;
+                if (reif.Material != null)
+                    material = Engine.Physical.Create.Material(reif.Material);
+                else
+                    material = new Material();
+
+                foreach (Line centreLine in reif.ReinforcementLayout(stirupOffset, outerProfileEdges, innerProfileEdges, length, transformation))
```
Comment (kThorsager) [inline Structure_Engine/Query/ReinforcingBars.cs:91]:
```suggestion
                foreach (Line centreLine in reif.ReinforcementLayout(cover, outerProfileEdges, innerProfileEdges, length, transformation))
```

File: Structure_Engine/Query/ReinforcementLayout.cs (hunk 2 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Query/ReinforcementLayout.cs:68]: Issue raised:
https://github.com/BHoM/BHoM_Engine/issues/1770

File: Structure_Engine/Query/ReinforcingBars.cs (hunk 5 above)
Comment (IsakNaslundBh) [reply Structure_Engine/Query/ReinforcingBars.cs:91]: 🤦

File: Structure_Engine/Query/ReinforcementLayout.cs [hunk 6]
```diff
@@ -0,0 +1,207 @@
...
+        [Input("cover", "Any additional spacing to be added in relation to the edge curves, such as minimum cover and stirups. This will be added on top of half the rebar Diameter.", typeof(Length))]
+        [Input("outerProfileEdges", "The outer profile edges of the ConcreteSection to be populated.")]
+        [Input("innerProfileEdges", "The inner profile edges, or openings, of the ConcreteSection to be populated.")]
+        [Output("points", "The positions of the LongitudinalReinforcement.")]
+        public static List<Point> ReinforcementLayout(this LongitudinalReinforcement reinforcement, double cover, List<ICurve> outerProfileEdges, List<ICurve> innerProfileEdges = null)
+        {
+            innerProfileEdges = innerProfileEdges ?? new List<ICurve>();
+            double offset = cover + reinforcement.Diameter / 2;
+            IEnumerable<ICurve> outerCurves = outerProfileEdges.Select(x => x.IOffset(offset, -Vector.ZAxis));
+            IEnumerable<ICurve> innerCurves = innerProfileEdges.Select(x => x.IOffset(offset, Vector.ZAxis));
```
Comment (kThorsager) [inline Structure_Engine/Query/ReinforcementLayout.cs:98]: This can offset outwards depending on curve orientation if one creates a free form profile.
image

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 7]
```diff
@@ -0,0 +1,193 @@
...
+    public static partial class Create
+    {
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+
+        [Description("Creates a LongitudinalReinforcement placing rebars along the perimiter of host ConcreteSection.")]
+        [InputFromProperty("diameter")]
+        [Input("barCount", "Number of Rebars along the perimiter.")]
+        [Input("rebarsAtProfileDiscontinuities", "If true, bars will be placed at any discontinuities of the perimiter of the crossection.")]
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:46]:
```suggestion
        [Input("barCount", "Number of Rebars along the perimeter.")]
        [Input("rebarsAtProfileDiscontinuities", "If true, bars will be placed at any discontinuities of the perimeter of the cross section.")]
```

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 8]
```diff
@@ -0,0 +1,193 @@
...
+        [InputFromProperty("startLocation")]
+        [InputFromProperty("endLocation")]
+        [Input("material", "Material of the Rebars. If null, a defaul material will be pulled from the Datasets.")]
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:49]:
```suggestion
        [Input("material", "Material of the Rebars. If null, a default material will be pulled from the Datasets.")]
```

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 9]
```diff
@@ -0,0 +1,193 @@
...
+                EndLocation = endLocation,
+            };
+        }
+
+        /***************************************************/
+
+        [Description("Creates a LongitudinalReinforcement placing rebars along a straight line throughout the ConcreteSection")]
+        [InputFromProperty("diameter")]
+        [Input("barCount", "Number of bars along the along the linear distribution.")]
+        [Input("direction", "Direction of the axis of the reinforcement. Should be a vector in the global XY-plane, defaults to the global X-axis.")]
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:69]:
```suggestion
        [Input("direction", "Direction of the axis of the reinforcement. Should be a vector in the global XY-plane. Defaults to the global X-axis.")]
```

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 10]
```diff
@@ -0,0 +1,193 @@
...
+        [Input("offset", "Offset of the linear layout in relation to the reference point, perpendicular to the Direction vector in the XY-plane.\n" +
+                     "A positive value will mean an offset towards the centre of the boundingbox of the ConcreteSection.", typeof(Length))]
+        [Input("referencePoint", "Controls, together with the offset, which point on the ConcreteSection that should be used for the layout.")]
+        [InputFromProperty("startLocation")]
+        [InputFromProperty("endLocation")]
+        [Input("material", "Material of the Rebars. If null, a defaul material will be pulled from the Datasets.")]
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:75]:
```suggestion
        [Input("material", "Material of the Rebars. If null, a default material will be pulled from the Datasets.")]
```

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 11]
```diff
@@ -0,0 +1,193 @@
...
+
+        /***************************************************/
+
+        [Description("Creates a LongitudinalReinforcement placing rebars along multiple linear parallel axes, defined along a vector from one side of the perimeter of ConcreteSection to the other. \n" +
+                 "Starts by fitting in as many points as possible in the first layer, then generates a new one and repeats.")]
+        [InputFromProperty("diameter")]
+        [Input("barCount", "Number of bars along the along the linear distribution axes.")]
+        [Input("parallelSPacing", "Minimum spacing allowed between two rebars in a single layer", typeof(Length))]
+        [Input("perpendicularSpacing", "Minimum spacing allowed between two rebars layers", typeof(Length))]
+        [Input("direction", "Direction of the axis of the reinforcement. Should be a vector in the global XY-plane, defaults to the global X-axis.")]
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:98]:
```suggestion
        [Input("parallelSpacing", "Minimum spacing allowed between two rebars in a single layer", typeof(Length))]
        [Input("perpendicularSpacing", "Minimum spacing allowed between two layers of rebar", typeof(Length))]
        [Input("direction", "Direction of the axis of the reinforcement. Should be a vector in the global XY-plane. Defaults to the global X-axis.")]
```

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 12]
```diff
@@ -0,0 +1,193 @@
...
+        [Input("offset", "Offset of the linear layout in relation to the reference point, perpendicular to the Direction vector in the XY-plane.\n" +
+                     "A positive value will mean an offset towards the centre of the boundingbox of the ConcreteSection.", typeof(Length))]
+        [Input("referencePoint", "Controls, together with the offset, which point on the ConcreteSection that should be used for the layout.")]
+        [InputFromProperty("startLocation")]
+        [InputFromProperty("endLocation")]
+        [Input("material", "Material of the Rebars. If null, a defaul material will be pulled from the Datasets.")]
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:104]:
```suggestion
        [Input("material", "Material of the Rebars. If null, a default material will be pulled from the Datasets.")]
```

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 13]
```diff
@@ -0,0 +1,193 @@
...
+                EndLocation = endLocation,
+            };
+        }
+
+        /***************************************************/
+
+        [Description("Creates a LongitudinalReinforcement placing rebars along multiple linear parallel axes along the local y-axis of the ConcreteSection, defined along a vector from one side of the perimeter of ConcreteSection to the other. \n" +
+                 "Starts by fitting in as many points as possible in a layer towards the bottom of the section, then generates a new one and repeats.")]
+        [InputFromProperty("diameter")]
+        [Input("area", "Total minimum required area of bottom reinforcement. Will be used to calculate required number of bars, based on their diameter, hence the resulting area can get higher the inout value.", typeof(Area))]
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:124]:
```suggestion
        [Input("area", "Total minimum required area of bottom reinforcement. Will be used to calculate required number of bars, based on their diameter, hence the resulting area may be larger than the input value.", typeof(Area))]
```

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 14]
```diff
@@ -0,0 +1,193 @@
...
+        [Input("spacing", "Minimum spacing allowed between any two rebars.")]
+        [InputFromProperty("miniumCover")]
+        [InputFromProperty("startLocation")]
+        [InputFromProperty("endLocation")]
+        [Input("material", "Material of the Rebars. If null, a defaul material will be pulled from the Datasets.")]
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:129]:
```suggestion
        [Input("material", "Material of the Rebars. If null, a default material will be pulled from the Datasets.")]
```

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 15]
```diff
@@ -0,0 +1,193 @@
...
+            int numberOfBars = (int)Math.Ceiling(area / (diameter * diameter * Math.PI / 4));
+            return MultiLinearReinforcement(diameter, numberOfBars, spacing, spacing, Vector.XAxis, 0, ReferencePoint.BottomCenter, startLocation, endLocation, material);
+        }
+
+        /***************************************************/
+
+        [Description("Creates a LongitudinalReinforcement placing rebars along multiple linear parallel axes along the local y-axis of the ConcreteSection, defined along a vector from one side of the perimeter of ConcreteSection to the other. \n" +
+                 "Starts by fitting in as many points as possible in a layer towards the top of the section, then generates a new one and repeats.")]
+        [InputFromProperty("diameter")]
+        [Input("area", "Total minimum required area of bottom reinforcement. Will be used to calculate required number of bars, based on their diameter, hence the resulting area can get higher the inout value.", typeof(Area))]
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:142]:
```suggestion
        [Input("area", "Total minimum required area of bottom reinforcement. Will be used to calculate required number of bars, based on their diameter, hence the resulting area may be larger than the input value.", typeof(Area))]
```

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 16]
```diff
@@ -0,0 +1,193 @@
...
+        [Input("spacing", "Minimum spacing allowed between any two rebars.")]
+        [InputFromProperty("startLocation")]
+        [InputFromProperty("endLocation")]
+        [Input("material", "Material of the Rebars. If null, a defaul material will be pulled from the Datasets.")]
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:146]:
```suggestion
        [Input("material", "Material of the Rebars. If null, a default material will be pulled from the Datasets.")]
```

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 17]
```diff
@@ -0,0 +1,193 @@
...
+                startLocation = 1;
+                Reflection.Compute.RecordWarning("End location need to be smaller or equal to 1. To accomodate, the end location has been set to 1.");
+            }
+
+            if (startLocation > endLocation)
+            {
+                double temp = startLocation;
+                startLocation = endLocation;
+                endLocation = temp;
+                Reflection.Compute.RecordWarning("Start location need to be smaller or equal than the end location. To accomodate, the start and end location have been switched.");
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:187]: I love the word 'accommodate' here! "to accommodate your incompetence, I have assumed you meant the following"

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 18]
```diff
@@ -0,0 +1,193 @@
...
+        /***************************************************/
+        /**** Private Methods                           ****/
+        /***************************************************/
+
+        private static void CheckEndLocations(ref double startLocation, ref double endLocation)
+        {
+            if (startLocation < 0)
+            {
+                startLocation = 0;
+                Reflection.Compute.RecordWarning("Start location need to be larger or equal to 0. To accomodate, the start location has been set to 0.");
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:163]:
```suggestion
                Reflection.Compute.RecordWarning("Start location need to be larger or equal to 0. To accommodate, the start location has been set to 0.");
```

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 19]
```diff
@@ -0,0 +1,193 @@
...
+            }
+            else if (startLocation > 1)
+            {
+                startLocation = 1;
+                Reflection.Compute.RecordWarning("Start location need to be smaller or equal to 1. To accomodate, the start location has been set to 1.");
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:168]:
```suggestion
                Reflection.Compute.RecordWarning("Start location need to be smaller or equal to 1. To accommodate, the start location has been set to 1.");
```

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 20]
```diff
@@ -0,0 +1,193 @@
...
+            }
+
+            if (endLocation < 0)
+            {
+                startLocation = 0;
+                Reflection.Compute.RecordWarning("End location need to be larger or equal to 0. To accomodate, the end location has been set to 0.");
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:174]:
```suggestion
                Reflection.Compute.RecordWarning("End location need to be larger or equal to 0. To accommodate, the end location has been set to 0.");
```

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs [hunk 21]
```diff
@@ -0,0 +1,193 @@
...
+            }
+            else if (startLocation > 1)
+            {
+                startLocation = 1;
+                Reflection.Compute.RecordWarning("End location need to be smaller or equal to 1. To accomodate, the end location has been set to 1.");
```
Comment (JosefTaylor) [inline Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:179]:
```suggestion
                Reflection.Compute.RecordWarning("End location need to be smaller or equal to 1. To accommodate, the end location has been set to 1.");
```

File: Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs (hunk 17 above)
Comment (JosefTaylor) [reply Structure_Engine/Create/SectionProperties/LongitudinalReinforcement.cs:187]:
```suggestion
                Reflection.Compute.RecordWarning("Start location need to be smaller or equal than the end location. To accommodate, the start and end location have been switched.");
```

File: Structure_Engine/Query/ReinforcementLayout.cs [hunk 22]
```diff
@@ -0,0 +1,207 @@
...
+            {
+                barLocations.AddRange(ReinforcementLayout(reif, cover, outerProfileEdges, innerProfileEdges, length, transformation));
+            }
+
+            return barLocations;
+        }
+
+        /***************************************************/
+
+        [Description("Gets the LongitudinalReinforcement centrelines as a list of lines, based on inner and outer profile edges and Bar paramters..")]
```
Comment (JosefTaylor) [inline Structure_Engine/Query/ReinforcementLayout.cs:149]:
```suggestion
        [Description("Gets the LongitudinalReinforcement centrelines as a list of lines, based on inner and outer profile edges and Bar parameters.")]
```

File: Structure_Engine/Query/ReinforcementTransitionPoints.cs [hunk 23]
```diff
@@ -0,0 +1,65 @@
...
+
+namespace BH.Engine.Structure
+{
+    public static partial class Query
+    {
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+
+        [Description("Returns a list of the normalised locations (0 means start, 1 means end) in the crossection where the reinforcement changes. If section is null or does not contain any reinforcement, an empty list will be returned.")]
```
Comment (JosefTaylor) [inline Structure_Engine/Query/ReinforcementTransitionPoints.cs:40]:
```suggestion
        [Description("Returns a list of the normalised locations (0 means start, 1 means end) in the cross section where the reinforcement changes. If section is null or does not contain any reinforcement, an empty list will be returned.")]
```

File: Structure_Engine/Query/ReinforcementTransitionPoints.cs [hunk 24]
```diff
@@ -0,0 +1,65 @@
...
+        [Input("concreteSection", "The ConcreteSection to extract reinforcement changes from.")]
```
Comment (JosefTaylor) [inline Structure_Engine/Query/ReinforcementTransitionPoints.cs:41]:
```suggestion
        [Input("concreteSection", "The ConcreteSection from which to extract reinforcement transitions.")]
```

File: Structure_Engine/Query/ReinforcingBars.cs [hunk 25]
```diff
@@ -0,0 +1,108 @@
...
+
+namespace BH.Engine.Structure
+{
+    public static partial class Query
+    {
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+
+        [Description("Extract all phsyical ReinforcingBars from the structural Bar. Only extract reinforcement for bars owning a ConcreteSection, for other sectiontypes, an empty list will be returned.")]
```
Comment (JosefTaylor) [inline Structure_Engine/Query/ReinforcingBars.cs:48]:
```suggestion
        [Description("Extract all physical ReinforcingBars from the structural Bar. Only extract reinforcement for bars owning a ConcreteSection, for other section types, an empty list will be returned.")]
```

File: Structure_Engine/Query/ReinforcingBars.cs [hunk 26]
```diff
@@ -0,0 +1,108 @@
...
+        [Input("bar", "The structural Bar to extract Reinforcement from.")]
+        [Output("rebars", "All phsyical ReinforcingBar on the provided Bar.")]
```
Comment (JosefTaylor) [inline Structure_Engine/Query/ReinforcingBars.cs:50]:
```suggestion
        [Output("rebars", "All physical ReinforcingBar on the provided Bar.")]
```

**Comment by IsakNaslundBh** [comment]
Have applied changes requested, thanks!

**Comment by LMarkowski** [comment]
> This can offset outwards depending on curve orientation if one creates a free form profile.

@kThorsager, I'm not sure if I get it right, but for closed curves and negative values `IOffset` should always create an internal curve, regardless of its direction.

image

**Comment by IsakNaslundBh** [comment]
@kThorsager have pushed a fix to Normal that seem to have been causing the bug.

https://github.com/BHoM/BHoM_Engine/issues/1775

@LMarkowski I was getting slightly different values depending on normal direction. Negative values where not always inwards facing. Found a bug in Normal method that I ahve attempted to fix though, so hope sorted now.

File: Structure_Engine/Query/ReinforcingBarCount.cs [hunk 27]
```diff
@@ -0,0 +1,96 @@
...
+
+        /***************************************************/
+
+        private static int LayoutCount(ILayout2D layout)
+        {
+            Engine.Reflection.Compute.RecordError("Could not extract number of points from layout of type " + layout.GetType().Name);
+            return 0;
+        }
+
+        /***************************************************/
```
Comment (kThorsager) [inline Structure_Engine/Query/ReinforcingBarCount.cs:94]: This should not be in the Structure_Engine

File: Structure_Engine/Query/ReinforcementTransitionPoints.cs [hunk 28]
```diff
@@ -0,0 +1,65 @@
...
+        [Input("concreteSection", "The ConcreteSection from which to extract reinforcement transitions.")]
+        [Output("locations", "The locations of reinforcement transitions in the crossection.")]
+        public static List<double> ReinforcementTransitionPoints(this ConcreteSection concreteSection)
+        {
+            if (concreteSection == null || concreteSection.Reinforcement == null || concreteSection.Reinforcement.Count == 0)
+            {
+                return new List<double>();
+            }
+
+            HashSet<double> uniquePositions = new HashSet<double>();
```
Comment (kThorsager) [inline Structure_Engine/Query/ReinforcementTransitionPoints.cs:50]: HashSet of doubles can give values quite close to each-other
image
Potentially problematic

**Comment by IsakNaslundBh** [comment]
Not sure how many discussion that have been had about this already, but I disagree with the compliance check. Think the code is alright.

**Comment by FraserGreenroyd** [comment]
> Not sure how many discussion that have been had about this already, but I disagree with the compliance check. Think the code is alright.

The current implementation for the check which has flagged in this PR is up to date following the discussions we had at the beginning of the milestone (discussions you did agree with), so I would say the flagging is correct, the create methods highlighted do not follow the guidance we agreed upon.

As this PR is already a bit large, I am happy for you to raise a separate issue to tackle the compliance rather than fix it as part of this PR if you would like and allow this to be merged with the failure at this time.

**Comment by kThorsager** [comment]
Looks like the CI messed up @FraserGreenroyd ?

"should return same as file or folder", which it does?

**Comment by IsakNaslundBh** [comment]
> Looks like the CI messed up @FraserGreenroyd ?
> 
> "should return same as file or folder", which it does?

Can it come from the fact that we have made use of sub-folders? Or do we have an old check running we need to turn off?

**Comment by FraserGreenroyd** [comment]
> > Looks like the CI messed up @FraserGreenroyd ?
> > "should return same as file or folder", which it does?
> 
> Can it come from the fact that we have made use of sub-folders? Or do we have an old check running we need to turn off?

As discussed on Teams, it is the use of sub-folders. Have offered a solution and will wait your response there. There are no old checks running they were all removed a couple of weeks ago.

**Comment by IsakNaslundBh** [comment]
@kThorsager mind re-testing and re-approving now that the compliance has been fixed?
