### PR TITLE
Reflection_Engine: Fix SetProperty of CustomData

### LINKED ISSUE #362: Library_Engine: Add standard BHoM Issue Labels to Planning Library
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

### LINKED ISSUE #2284: Reflection_Engine: SetProperty does not work on existing CustomData keys
#### Description:

As in the description, using `SetProperty` to overwrite a `CustomData` key does not work, see the screenshot below.

image

#### Test file:
[Here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #2284

Changing a value stored in CustomData is now possible even if the corresponding key already exists

### Test files
See issue

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

File: Reflection_Engine/Modify/SetPropertyValue.cs [hunk 1]
```diff
@@ -107,18 +107,15 @@ private static bool SetValue(this IBHoMObject obj, string propName, object value
...
-                    obj.Fragments.Add(value as IFragment);
-                    Compute.RecordWarning("The objects does not contain any property with the name " + propName + ". The value is being set as a fragment.");
-                }
-                else
-                {
-                    obj.CustomData[propName] = value;
-                    Compute.RecordWarning("The objects does not contain any property with the name " + propName + ". The value is being set as custom data.");
-                }
+                obj.Fragments.Add(value as IFragment);
+                Compute.RecordWarning("The objects does not contain any property with the name " + propName + ". The value is being set as a fragment.");
```
Comment (FraserGreenroyd) [inline Reflection_Engine/Modify/SetPropertyValue.cs:113]:
```suggestion
                Compute.RecordWarning("The object does not contain any property with the name " + propName + ". The value is being set as a fragment.");
```

Or

```suggestion
                Compute.RecordWarning("The objects do not contain any property with the name " + propName + ". The value is being set as a fragment.");
```

`objects does` doesn't read quite right to me, one of them should be singular but not sure what the rest of the method is doing so suggesting both options. Looks like the method takes in a single object so the first one might be more appropriate?

File: Reflection_Engine/Modify/SetPropertyValue.cs [hunk 2]
```diff
@@ -107,18 +107,15 @@ private static bool SetValue(this IBHoMObject obj, string propName, object value
...
+            }
+            else
+            {
+                obj.CustomData[propName] = value;
+                Compute.RecordWarning("The objects does not contain any property with the name " + propName + ". The value is being set as custom data.");
```
Comment (FraserGreenroyd) [inline Reflection_Engine/Modify/SetPropertyValue.cs:118]:
```suggestion
                Compute.RecordWarning("The object does not contain any property with the name " + propName + ". The value is being set as custom data.");
```

Or

```suggestion
                Compute.RecordWarning("The objects do not contain any property with the name " + propName + ". The value is being set as custom data.");
```

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Minor grammar suggestions on the user messages, otherwise LGTM.

**Review by FraserGreenroyd — APPROVED** [review]
Wording LGTM now, will leave @pawelbaran to do a final functionality review has he raised the issue to be fixed :smile:

**Review by pawelbaran — APPROVED** [review]
LGTM

Btw, the issue was originally raised in the BHoM_UI, I have transferred it to BHoM_Engine and updated numbers/links/folders. Should be ready to merge now 👍

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check copyright
