### PR TITLE
Structure_Engine: Fix null handling failures

### LINKED ISSUE #2485: Structure Engine - handle nulls
Note, where the `method` begins with `BH.oM` - this means it is a `Create` method. This is also why there are a couple of `BH.oM.Physical` objects in this list, they are `Create` methods which sit within the Structure_Engine.

The following methods need appropriate `null` handling of their inputs. You can use `@BHoMBot check null-handling` on a draft PR to check progress if needed - you're ultimately looking for a reduction in errors from the `master`/`main` branch. I can run more localised tests to confirm against if needed to confirm specific methods.

 - [x] BH.Engine.Structure.Compute.MapTaperedProfile(List<Bar> bars, IGeometricalSection section)
 - [x] BH.Engine.Structure.Compute.ShearAreaPolyline(Polyline pLine, Double momentOfInertia, Double tol)
 - [x] BH.Engine.Structure.Compute.Integrate(IProfile profile, Double tolerance)
 - [x] BH.oM.Physical.Elements.IFramingElement.FramingElement(Bar bar, StructuralUsage1D structuralUsage)
 - [x] BH.oM.Structure.Elements.Panel.Panel(PlanarSurface surface, ISurfaceProperty property, Vector localX, String name)
 - [x] BH.oM.Structure.Elements.Node.Node(Cartesian coordinates, String name, Constraint6DOF support)
 - [x] BH.oM.Structure.Elements.Bar.Bar(Line line, ISectionProperty sectionProperty, Double orientationAngle, BarRelease release, BarFEAType feaType, String name)
 - [x] BH.oM.Structure.Elements.Bar.Bar(Line line, ISectionProperty sectionProperty, Vector normal, BarRelease release, BarFEAType feaType, String name)
 - [x] BH.oM.Structure.SectionProperties.SteelSection.SteelISection(Double height, Double webThickness, Double flangeWidth, Double flangeThickness, Double rootRadius, Double toeRadius, and 2 more inputs)
 - [x] BH.oM.Structure.SectionProperties.SteelSection.SteelFabricatedISection(Double height, Double webThickness, Double topFlangeWidth, Double topFlangeThickness, Double botFlangeWidth, Double botFlangeThickness, and 3 more inputs)
 - [x] BH.oM.Structure.SectionProperties.SteelSection.SteelBoxSection(Double height, Double width, Double thickness, Double innerRadius, Double outerRadius, Steel material, and 1 more inputs)
 - [x] BH.oM.Structure.SectionProperties.SteelSection.FabricatedSteelBoxSection(Double height, Double width, Double webThickness, Double flangeThickness, Double weldSize, Steel material, and 1 more inputs)
 - [x] BH.oM.Structure.SectionProperties.SteelSection.SteelTubeSection(Double diameter, Double thickness, Steel material, String name)
 - [x] BH.oM.Structure.SectionProperties.SteelSection.SteelRectangleSection(Double height, Double width, Double cornerRadius, Steel material, String name)
 - [x] BH.oM.Structure.SectionProperties.SteelSection.SteelCircularSection(Double diameter, Steel material, String name)
 - [x] BH.oM.Structure.SectionProperties.SteelSection.SteelTSection(Double height, Double webThickness, Double flangeWidth, Double flangeThickness, Double rootRadius, Double toeRadius, and 2 more inputs)
 - [x] BH.oM.Structure.SectionProperties.SteelSection.SteelAngleSection(Double height, Double webThickness, Double width, Double flangeThickness, Double rootRadius, Double toeRadius, and 2 more inputs)
 - [x] BH.oM.Structure.SectionProperties.SteelSection.SteelSectionFromProfile(IProfile profile, Steel material, String name)
 - [x] BH.oM.Structure.Loads.BarVaryingDistributedLoad.BarVaryingDistributedLoadDistanceBothEnds(Loadcase loadcase, BHoMGroup<Bar> group, Boolean relativePositions, Double startToStartDistance, Vector forceAtStart, Vector momentAtStart, and 7 more inputs)
 - [x] BH.oM.Structure.SectionProperties.AluminiumSection.AluminiumSectionFromProfile(IProfile profile, Aluminium material, String name)
 - [x] BH.oM.Physical.FramingProperties.ConstantFramingProperty.ConstantFramingProperty(ISectionProperty sectionProperty, Double orientationAngle, String name)
 - [x] BH.oM.Structure.Elements.FEMesh.FEMesh(Mesh mesh, ISurfaceProperty property, Vector localX, String name)
 - [x] BH.oM.Structure.SectionProperties.ConcreteSection.ConcreteCircularSection(Double diameter, Concrete material, String name, List<IBarReinforcement> reinforcement, Double minimumCover)
 - [x] BH.oM.Structure.SectionProperties.ConcreteSection.ConcreteRectangleSection(Double height, Double width, Concrete material, String name, List<IBarReinforcement> reinforcement, Double minimumCover)
 - [x] BH.oM.Structure.SectionProperties.ConcreteSection.ConcreteSectionFromProfile(IProfile profile, Concrete material, String name, List<IBarReinforcement> reinforcement, Double minimumCover)
 - [x] BH.oM.Structure.SectionProperties.ConcreteSection.ConcreteTSection(Double height, Double webThickness, Double flangeWidth, Double flangeThickness, Concrete material, String name, and 2 more inputs)
 - [x] BH.oM.Structure.SectionProperties.GenericSection.GenericSectionFromProfile(IProfile profile, IMaterialFragment material, String name)
 - [x] BH.oM.Structure.SectionProperties.IGeometricalSection.SectionPropertyFromProfile(IProfile profile, IMaterialFragment material, String name)
 - [x] BH.oM.Structure.SectionProperties.TimberSection.TimberRectangleSection(Double height, Double width, Double cornerRadius, Timber material, String name)
 - [x] BH.oM.Structure.SectionProperties.TimberSection.TimberSectionFromProfile(IProfile profile, Timber material, String name)
 - [x] BH.Engine.Structure.Modify.AddReinforcement(ConcreteSection section, and 1 more inputs)
 - [x] BH.Engine.Structure.Modify.OrientTowards(Bar bar, Point orientationPoint)
 - [x] BH.Engine.Structure.Modify.OrientTowards(FEMesh mesh, Point orientationPoint)
 - [x] BH.Engine.Structure.Modify.OrientTowards(FEMeshFace face, FEMesh mesh, Point orientationPoint)
 - [x] BH.Engine.Structure.Modify.SetLocalOrientation(Panel panel, Vector localX)
 - [x] BH.Engine.Structure.Modify.SetLocalOrientations(FEMesh mesh, Vector localX)
 - [x] BH.Engine.Structure.Modify.SetLocalOrientation(FEMeshFace face, FEMesh mesh, Vector localX)
 - [x] BH.Engine.Structure.Modify.SetMaterial(Bar bar, IMaterialFragment material)
 - [x] BH.Engine.Structure.Modify.SetNormal(Bar bar, Vector normal)
 - [x] BH.Engine.Structure.Modify.SetStructuralFragment(Material material, IMaterialFragment structuralFragment)
 - [x] BH.Engine.Structure.Modify.ApplyModifiers(ISurfaceProperty prop, Double fxx, Double fxy, Double fyy, Double mxx, Double mxy, and 5 more inputs)
 - [x] BH.Engine.Structure.Modify.ApplyModifiers(ISectionProperty prop, Double area, Double iy, Double iz, Double j, Double asy, and 1 more inputs)
 - [x] BH.Engine.Structure.Modify.Flip(Bar bar)
 - [x] BH.Engine.Structure.Modify.Flip(Edge edge)
 - [x] BH.Engine.Structure.Modify.SetReinforcement(ConcreteSection section, and 1 more inputs)
 - [x] BH.Engine.Structure.Query.TorsionalConstant(AngleProfile profile)
 - [x] BH.Engine.Structure.Query.TorsionalConstant(RectangleProfile profile)
 - [x] BH.Engine.Structure.Query.WarpingConstant(ISectionProfile profile)
 - [x] BH.Engine.Structure.Query.WarpingConstant(FabricatedISectionProfile profile)
 - [x] BH.Engine.Structure.Query.WarpingConstant(ChannelProfile profile)
 - [x] BH.Engine.Structure.Query.IsConstrained(Node node)
 - [x] BH.Engine.Structure.Query.BarSectionTranformation(Bar bar)
 - [x] BH.Engine.Structure.Query.ReinforcementLayout(LongitudinalReinforcement reinforcement, Double cover, List<ICurve> outerProfileEdges, List<ICurve> innerProfileEdges)
 - [x] BH.Engine.Structure.Query.ReinforcementLayout(TransverseReinforcement reinforcement, Double cover, List<ICurve> outerProfileEdges, List<ICurve> innerProfileEdges)
 - [x] BH.Engine.Structure.Query.ReinforcementLayout(Bar bar)
 - [x] BH.Engine.Structure.Query.ReinforcementLayout(LongitudinalReinforcement reinforcement, Double cover, List<ICurve> outerProfileEdges, List<ICurve> innerProfileEdges, Double length, TransformMatrix transformation)
 - [x] BH.Engine.Structure.Query.ReinforcementLayout(TransverseReinforcement reinforcement, Double cover, List<ICurve> outerProfileEdges, List<ICurve> innerProfileEdges, Double length, TransformMatrix transformation)
 - [x] BH.Engine.Structure.Query.ReinforcingBarCount(LongitudinalReinforcement reinforcement)
 - [x] BH.Engine.Structure.Query.ReinforcingBars(Bar bar)
 - [x] BH.Engine.Structure.Query.ShearModulus(IIsotropic materialFragment)
 - [x] BH.Engine.Structure.Query.SolidVolume(Bar bar)
 - [x] BH.Engine.Structure.Query.SolidVolume(IAreaElement areaElement)
 - [x] BH.Engine.Structure.Query.StructuralMaterialFragment(Material material)
 - [x] BH.Engine.Structure.Query.Visualize(AreaUniformTemperatureLoad areaTempLoad, Double scaleFactor, Boolean displayForces, Boolean displayMoments, Boolean asResultants, Boolean edgeDisplay, and 1 more inputs)
 - [x] BH.Engine.Structure.Query.Visualize(BarPointLoad barPointForce, Double scaleFactor, Boolean displayForces, Boolean displayMoments, Boolean asResultants)
 - [x] BH.Engine.Structure.Query.Visualize(BarPrestressLoad barPrestressLoad, Double scaleFactor, Boolean displayForces, Boolean displayMoments, Boolean asResultants)
 - [x] BH.Engine.Structure.Query.Visualize(BarUniformTemperatureLoad barTempLoad, Double scaleFactor, Boolean displayForces, Boolean displayMoments, Boolean asResultants)
 - [x] BH.Engine.Structure.Query.Visualize(BarUniformlyDistributedLoad barUDL, Double scaleFactor, Boolean displayForces, Boolean displayMoments, Boolean asResultants)
 - [x] BH.Engine.Structure.Query.Visualize(BarVaryingDistributedLoad barVaryingDistLoad, Double scaleFactor, Boolean displayForces, Boolean displayMoments, Boolean asResultants)
 - [x] BH.Engine.Structure.Query.Visualize(GravityLoad gravityLoad, Double scaleFactor, Boolean displayForces, Boolean displayMoments, Boolean asResultants)
 - [x] BH.Engine.Structure.Query.Visualize(PointAcceleration pointAcceleration, Double scaleFactor, Boolean displayTranslations, Boolean displayRotations, Boolean asResultants)
 - [x] BH.Engine.Structure.Query.Visualize(PointDisplacement pointDisplacement, Double scaleFactor, Boolean displayTranslations, Boolean displayRotations, Boolean asResultants)
 - [x] BH.Engine.Structure.Query.Visualize(PointLoad pointForce, Double scaleFactor, Boolean displayForces, Boolean displayMoments, Boolean asResultants)
 - [x] BH.Engine.Structure.Query.Visualize(PointVelocity pointVelocity, Double scaleFactor, Boolean displayTranslations, Boolean displayRotations, Boolean asResultants)
 - [x] BH.Engine.Structure.Query.Visualize(GeometricalLineLoad lineLoad, Double scaleFactor, Boolean displayForces, Boolean displayMoments, Boolean asResultants)
 - [x] BH.Engine.Structure.Query.WidthAt(IProfile section, Double y)
 - [x] BH.Engine.Structure.Query.WidthAt(IProfile section, Double y, Double[]& range)
 - [x] BH.Engine.Structure.Query.TieDiameter(ConcreteSection property)
 - [x] BH.Engine.Structure.Query.TorsionalConstant(CircleProfile profile)
 - [x] BH.Engine.Structure.Query.TorsionalConstant(TubeProfile profile)
 - [x] BH.Engine.Structure.Query.TorsionalConstant(FabricatedBoxProfile profile)
 - [x] BH.Engine.Structure.Query.TorsionalConstant(BoxProfile profile)
 - [x] BH.Engine.Structure.Query.TorsionalConstant(FabricatedISectionProfile profile)
 - [x] BH.Engine.Structure.Query.TorsionalConstant(ISectionProfile profile)
 - [x] BH.Engine.Structure.Query.TorsionalConstant(ChannelProfile profile)
 - [x] BH.Engine.Structure.Query.TorsionalConstant(ZSectionProfile profile)
 - [x] BH.Engine.Structure.Query.TorsionalConstant(TSectionProfile profile)
 - [x] BH.Engine.Structure.Query.TorsionalConstant(GeneralisedTSectionProfile profile)
 - [x] BH.Engine.Structure.Query.Area(Surface surface)
 - [x] BH.Engine.Structure.Query.Area(LongitudinalReinforcement reinforcement)
 - [x] BH.Engine.Structure.Query.DistributedPoints(Bar bar, Int32 divisions, Double startLength, Double endLength)
 - [x] BH.Engine.Structure.Query.Extrude(Bar bar, Boolean simple)
 - [x] BH.Engine.Structure.Query.Centreline(Bar bar)
 - [x] BH.Engine.Structure.Query.IsValidStructural(Material material)
 - [x] BH.Engine.Structure.Query.Edges(Surface surface)
 - [x] BH.Engine.Structure.Query.MassPerArea(ConstantThickness constantThickness)
 - [x] BH.Engine.Structure.Query.MassPerMetre(ISectionProperty section)
 - [x] BH.Engine.Structure.Query.MassPerMetre(ConcreteSection section)
 - [x] BH.Engine.Structure.Query.MassPerMetre(CompositeSection section)
 - [x] BH.Engine.Structure.Query.MassPerMetre(CableSection section)
 - [x] BH.Engine.Structure.Query.Modifiers(ISurfaceProperty property)
 - [x] BH.Engine.Structure.Query.Modifiers(ISectionProperty property)
 - [x] BH.Engine.Structure.Query.OppositeNode(Bar bar, Node node)
 - [x] BH.Engine.Structure.Query.ElasticValues(Constraint6DOF constraint)
 - [x] BH.Engine.Structure.Query.DepthAt(IProfile section, Double x)
 - [x] BH.Engine.Structure.Query.DepthAt(IProfile section, Double x, Double[]& range)
 - [x] BH.Engine.Structure.Query.PointGrid(FEMesh mesh)
 - [x] BH.Engine.Structure.Query.PointGrid(FEMeshFace face, FEMesh mesh)
 - [x] BH.Engine.Structure.Query.AverageThickness(ConstantThickness property)
 - [x] BH.Engine.Structure.Query.AverageThickness(Ribbed property)
 - [x] BH.Engine.Structure.Query.AverageThickness(Waffle property)
 - [x] BH.Engine.Structure.Query.Fixities(Constraint6DOF constraint)
 - [x] BH.Engine.Structure.Query.Geometry3D(Bar bar, Boolean onlyOuterExtrusion)
 - [x] BH.Engine.Structure.Query.Geometry3D(Panel panel, Boolean onlyCentralSurface)
 - [x] BH.Engine.Structure.Query.HasMergeablePropertiesWith(Edge element, Edge other)
 - [x] BH.Engine.Structure.Query.HasModifiers(ISurfaceProperty property)
 - [x] BH.Engine.Structure.Query.HasModifiers(ISectionProperty property)
 - [x] BH.Engine.Structure.Query.IsNumericallyDependent(Constraint3DOF constraint)
 - [x] BH.Engine.Structure.Query.IsNumericallyDependent(Constraint4DOF constraint)
 - [x] BH.Engine.Structure.Query.IsNumericallyDependent(Constraint6DOF constraint)
 - [x] BH.Engine.Structure.Query.MaterialComposition(Bar bar)
 - [x] BH.Engine.Structure.Query.MaterialComposition(IAreaElement areaElement)
 - [x] BH.Engine.Structure.Query.MaterialComposition(ISectionProperty sectionProperty)
 - [x] BH.Engine.Structure.Query.MaterialComposition(ConcreteSection sectionProperty)

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #2485 

- @rolyhudson as discussed `IsNull` method added to Geometry_Engine and Spatial_Engine to centralise null checking.

### Test files

To be verified with CI `null-handling` check.

For versioning: 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Structure_Engine/%232504-FixNullHandlingComplianceFailures?csf=1&web=1&e=S1iDZa

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot null-handling

**Comment by peterjamesnugent** [comment]
@BHoMBot check null-handling

**Comment by peterjamesnugent** [comment]
@BHoMBot check null-handling

File: Spatial_Engine/Query/IsNull.cs [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+    public static partial class Query
+    {
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+
+        [Description("Checks if an IProfile is null and outputs relevant error message.")]
+        [Input("profile", "The IProfile to test for null.")]
+        [Input("methodName", "The name of the method to reference in the error message.")]
+        [Output("pass", "A boolean which is true if the bar passes the null check.")]
```
Comment (rolyhudson) [inline Spatial_Engine/Query/IsNull.cs:42]:
```suggestion
        [Output("pass", "A boolean which is true if the profile passes the null check.")]
```

File: Geometry_Engine/Query/IsNull.cs [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+    public static partial class Query
+    {
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+
+        [Description("Checks if an IGeometry is null and outputs relevant error message.")]
+        [Input("geometry", "The geometry to test for null.")]
+        [Input("methodName", "The name of the method to reference in the error message.")]
+        [Output("pass", "A boolean which is true if the bar passes the null check.")]
```
Comment (rolyhudson) [inline Geometry_Engine/Query/IsNull.cs:44]:
```suggestion
        [Output("pass", "A boolean which is true if the geometry passes the null check.")]
```

File: Spatial_Engine/Query/IsNull.cs [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+                //If the methodName is not provided, use StackTrace to get it, if the method was called indepedently use "Method".
+                if (string.IsNullOrEmpty(methodName))
+                {
+                    StackTrace st = new StackTrace();
+                    methodName = st.FrameCount > 0 ? st.GetFrame(1).GetMethod().Name : "Method";
+                }
+                else
+                    methodName = "Method";
+
+                Reflection.Compute.RecordError($"Cannot evaluate {methodName} because geometry failed a null check.");
```
Comment (rolyhudson) [inline Spatial_Engine/Query/IsNull.cs:56]:
```suggestion
                Reflection.Compute.RecordError($"Cannot evaluate {methodName} because profile failed a null check.");
```

File: Geometry_Engine/Query/IsNull.cs [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+        public static bool IsNull(this IGeometry geometry, string methodName = "")
+        {
+            if (geometry == null)
+            {
+                //If the methodName is not provided, use StackTrace to get it, if the method was called indepedently use "Method".
+                if (string.IsNullOrEmpty(methodName))
+                {
+                    StackTrace st = new StackTrace();
+                    methodName = st.FrameCount > 0 ? st.GetFrame(1).GetMethod().Name : "Method";
```
Comment (rolyhudson) [inline Geometry_Engine/Query/IsNull.cs:53]: I think the method name should be cleaned up to given the user a nice readable message. Right now this generates:
Screenshot 2021-05-17 163641
But should read:
1. Cannot evaluate Integrate because geometry failed a null check.

File: Spatial_Engine/Query/IsNull.cs [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+        [Output("pass", "A boolean which is true if the bar passes the null check.")]
+        public static bool IsNull(this IProfile profile, string methodName = "")
+        {
+            if (profile == null)
+            {
+                //If the methodName is not provided, use StackTrace to get it, if the method was called indepedently use "Method".
+                if (string.IsNullOrEmpty(methodName))
+                {
+                    StackTrace st = new StackTrace();
+                    methodName = st.FrameCount > 0 ? st.GetFrame(1).GetMethod().Name : "Method";
```
Comment (rolyhudson) [inline Spatial_Engine/Query/IsNull.cs:51]: We should avoid messages with symbols and numbers that may confuse a user.
Can we clean the methodname string here too?

File: Structure_Engine/Create/Framing/ConstantFramingProperty.cs [hunk 6]
```diff
@@ -63,7 +64,7 @@ public static ConstantFramingProperty ConstantFramingProperty(ISectionProperty s
             }
             else
             {
-                Engine.Reflection.Compute.RecordWarning("Material from sectiion property of the bar is null.");
+                Reflection.Compute.RecordWarning("Material from sectiion property of the bar is null.");
```
Comment (rolyhudson) [inline Structure_Engine/Create/Framing/ConstantFramingProperty.cs:67]:
```suggestion
                Reflection.Compute.RecordWarning("Material from section property of the bar is null.");
```

File: Geometry_Engine/Query/IsNull.cs [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+
+        [Description("Checks if an IGeometry is null and outputs relevant error message.")]
+        [Input("geometry", "The geometry to test for null.")]
+        [Input("methodName", "The name of the method to reference in the error message.")]
+        [Output("pass", "A boolean which is true if the bar passes the null check.")]
+        public static bool IsNull(this IGeometry geometry, string methodName = "")
+        {
```
[the remark this answers is not in the document]
Comment (peterjamesnugent) [reply Geometry_Engine/Query/IsNull.cs:46]: My only hesitation in doing so would be the decentralisation of error messages but I can see the benefit of more bespoke/custom error messages.

**Comment by peterjamesnugent** [comment]
@BHoMBot check null-handling

**Comment by peterjamesnugent** [comment]
@BHoMBot check installer

**Comment by peterjamesnugent** [comment]
@BHoMBot check null-handling

**Comment by peterjamesnugent** [comment]
@BHoMBot check null-handling

**Comment by peterjamesnugent** [comment]
@FraserGreenroyd I've run this check locally see [MethodsFaillingNullChecks.txt](https://github.com/BHoM/BHoM_Engine/files/6504870/MethodsFaillingNullChecks.txt). I can't find any reference to Structure_Engine methods or Structure_oM or Physical_oM (there's a create method or two that outputs this).

File: Geometry_Engine/Query/IsNull.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (rolyhudson) [reply Geometry_Engine/Query/IsNull.cs:47]: Sorry I should have explained better. I think we should always have the standard message and allow for a second customised, but optional line - rather than a complete override.

**Comment by FraserGreenroyd** [comment]
@peterjamesnugent I think the check difference is being caused by something that was merged while this PR has been open, hence `master` has some fixes which your branch doesn't and thus the message that this PR has reduced some failures but introduced some which aren't on `master`. I have had a local look of comparing `master` to this branch and am happy that this branch removes all issues relating to the Structure_Engine.

I would be happy to approve on a CI/CD basis, and will dispensate the check depending on the nature of any subsequent commits. I will leave full approval to discipline owing to the nature of the code, but from a CI/CD perspective, I am happy.

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

File: Structure_Engine/Compute/Integrate.cs [hunk 8]
```diff
@@ -82,11 +83,46 @@ public static partial class Compute
                 results["Asy"] = 0;
                 results["Asz"] = 0;
 
-                #endregion 
+                #endregion
                 return results;
             }
+            else if (curves.Count == 0)
```
Comment (IsakNaslundBh) [inline Structure_Engine/Compute/Integrate.cs:89]: Not sure I like the copy paste here..

Understand it has to do with wanting to give an error or not, but maybe worth changing to something like adding a private "ZeroConstantsDictionary" method (or similar better name if you can think of anything) that returns a dictionary filled up with the 0 values, and then return that method instead.

File: Structure_Engine/Compute/Integrate.cs [hunk 9]
```diff
@@ -142,6 +178,9 @@ public static partial class Compute
         [MultiOutput(1, "constants", "The section constants calculated based on the provided section profile.")]
         public static Output<IProfile, Dictionary<string, double>> Integrate(IProfile profile, double tolerance = Tolerance.Distance)
         {
+            if (profile.IsNull())
+                return null;
```
Comment (IsakNaslundBh) [inline Structure_Engine/Compute/Integrate.cs:182]: Not sure if we have a convention for what to return to multi outputs if one of the items is null, but would probably rather go with something like returning a correct output type, but setting both of the items in it to null. Just nitpicking, but wanting to keep it clean for UIs etc.

@FraserGreenroyd @adecler any ideas?

File: Structure_Engine/Convert/FEMeshToPanel.cs [hunk 10]
```diff
@@ -41,37 +41,21 @@ public static partial class Convert
...
+            if (feMesh.IsNull("FEMeshToPanel"))
             {
-                Engine.Reflection.Compute.RecordError("FEMesh is null, please check inputs.");
                 return null;
             }
-            if (feMesh.Nodes == null || feMesh.Nodes.Count < 3)
+            if (feMesh.Nodes.Count < 3)
             {
-                Engine.Reflection.Compute.RecordError("FEMesh Nodes are null, please check inputs");
+                Reflection.Compute.RecordError("FEMesh Nodes are null, please check inputs");
```
Comment (IsakNaslundBh) [inline Structure_Engine/Convert/FEMeshToPanel.cs:50]:
```suggestion
                Reflection.Compute.RecordError("Insufficient number of nodes to be able to convert FEMesh to a Panel.");
```

File: Structure_Engine/Convert/FEMeshToPanel.cs [hunk 11]
```diff
@@ -41,37 +41,21 @@ public static partial class Convert
...
                 return null;
             }
-            if (feMesh.Faces == null || feMesh.Faces.Count < 1)
+            if (feMesh.Faces.Count < 1)
             {
-                Engine.Reflection.Compute.RecordError("FEMesh Faces are null, please check inputs.");
+                Reflection.Compute.RecordError("FEMesh Faces are null, please check inputs.");
```
Comment (IsakNaslundBh) [inline Structure_Engine/Convert/FEMeshToPanel.cs:55]:
```suggestion
                Reflection.Compute.RecordError("At least one FEFace required to construct a Panel from FEMesh.");
```

**Review by IsakNaslundBh — CHANGES_REQUESTED** [review]
Initial comments. Have not looked through all files yet.

Also various compliance issues that would be good to get sorted reported by the Bot :)

File: Geometry_Engine/Query/IsNull.cs [hunk 12]
```diff
@@ -0,0 +1,71 @@
...
+            if (geometry == null)
+            {
+                //If the methodName is not provided, use StackTrace to get it, if the method was called indepedently use "Method".
+                    if (string.IsNullOrEmpty(methodName))
+                    {
+                        StackTrace st = new StackTrace();
+                        if (st.FrameCount > 0)
+                        {
+                            methodName = st.GetFrame(1).GetMethod().Name;
+                            methodName.Substring(methodName.IndexOf("<") + 1, methodName.IndexOf("<") + 1 - methodName.IndexOf(">"));
```
[the remark this answers is not in the document]
Comment (rolyhudson) [reply Geometry_Engine/Query/IsNull.cs:57]: This was suggested by me to help message legibility. It cleans up he method name from `GetFrame(1).GetMethod().Name` which otherwise comes out something like `<Integrate>b__39_1`

[the remark this answers is not in the document]
Comment (IsakNaslundBh) [reply Geometry_Engine/Query/IsNull.cs:57]: Ok, cool! Does this apply for all methods, or only when called via Linq?

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check null-handling

**Comment by peterjamesnugent** [comment]
@BHoMBot fix documentation punctuation ref. 2726403612

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

File: Spatial_Engine/Query/IsNull.cs [hunk 13]
```diff
@@ -0,0 +1,105 @@
...
+
+            return false;
+        }
+
+        [Description("Checks if an Layout2D is null and outputs relevant error message.")]
+        [Input("layout", "The Layout2D to test for null.")]
+        [Input("methodName", "The name of the method to reference in the error message.")]
+        [Input("msg", "Optional error message to override the default error message. Only the contents of this string will be returned as an error.")]
+        [Output("isNull", "True if the Layout2D is null.")]
+        public static bool IsNull(this ILayout2D layout, string methodName = "", string msg = "")
```
Comment (IsakNaslundBh) [inline Spatial_Engine/Query/IsNull.cs:67]:
```suggestion
        public static bool IsNull(this ILayout2D layout, [CallerMemberName] string methodName = "", string msg = "")
```

And same for all methods in this file

File: Structure_Engine/Query/IsNull.cs [hunk 14]
```diff
@@ -0,0 +1,459 @@
...
+        /**** Public Methods                            ****/
+        /***************************************************/
+
+        [PreviousVersion("4.2", "BH.Engine.Structure.Compute.NullCheck(BH.oM.Structure.Elements.Node, System.String)")]
+        [Description("Checks if a Node or its defining properties are null and outputs relevant error message.")]
+        [Input("node", "The Node to test for null.")]
+        [Input("methodName", "The name of the method to reference in the error message.")]
+        [Input("msg", "Optional message to be returned in addition to the generated error message.")]
+        [Output("isNull", "True if the Node or its defining properties are null.")]
+        public static bool IsNull(this Node node, string methodName = "Method", string msg = "")
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/IsNull.cs:53]: For this and all other methods in this file
```suggestion
        public static bool IsNull(this Node node, [CallerMemberName] string methodName = "Method", string msg = "")
```

**Review by IsakNaslundBh — CHANGES_REQUESTED** [review]
Some more attributes

**Comment by peterjamesnugent** [comment]
@BHoMBot check unit-tests

File: Geometry_Engine/Query/IsNull.cs [hunk 15]
```diff
@@ -0,0 +1,64 @@
...
+        /***************************************************/
+        /**** Public Methods                            ****/
+        /***************************************************/
+
+        [Description("Checks if an Geometry is null and outputs relevant error message.")]
+        [Input("geometry", "The Geometry to test for null.")]
+        [Input("methodName", "The name of the method to reference in the error message.")]
+        [Input("msg", "Optional message to be returned in addition to the generated error message.")]
+        [Output("isNull", "True if the Geometry is null.")]
+        public static bool IsNull(this IGeometry geometry, [CallerMemberName] string methodName = "", string msg = "")
```
Comment (IsakNaslundBh) [inline Geometry_Engine/Query/IsNull.cs:47]: Probably one for later, to not bloat this PR as it is supposed to handle structures_Engine, but raising now to potentially avoid refactoring later.

Was thinking if we wanted to have this method look deeper, as in, if for example a line is first checked if it is null itself, then have both of its points checked. This could be controlled via some boolean input on the method like `deepCheck` or similar, and then would need a specific method for each type.

again, not for this PR to implement, but raising jsut in case we want to add the bool straight away.

File: Structure_Engine/Compute/MapTaperedProfile.cs [hunk 16]
```diff
@@ -42,16 +42,19 @@ public static partial class Compute
         /***************************************************/
         [Description("Maps a TaperedProfile to a series of sequential Bars by interpolating the profiles at the startNode and endNode of each bar using a polynomial defined by the interpolationOrder. " +
             "For nonlinear profiles a concave profile is achieved by setting the larger profile at the smallest position. To achieve a convex profile, the larger profile must be at the largest position.")]
-        [Input("section", "The section containing the TaperedProfile to be mapped to the series of Bars")]
+        [Input("section", "The section containing the TaperedProfile to be mapped to the series of Bars.")]
         [Input("bars", "The Bars in sequential order for the TaperedProfile to be mapped to.")]
         [Output("bars", "The Bars with interpolated SectionProperties based on the TaperedProfile provided.")]
         public static List<Bar> MapTaperedProfile(List<Bar> bars, IGeometricalSection section)
         {
+            if (bars.Any(x => x.IsNull("MapTaperedProfile")) || section.IsNull("MapTaperedProfile"))
```
Comment (IsakNaslundBh) [inline Structure_Engine/Compute/MapTaperedProfile.cs:50]: If we add the attribute to the IsNull methods in Structure_Engine, we should not have to include the method name here

File: Structure_Engine/Convert/FEMeshToPanel.cs [hunk 17]
```diff
@@ -41,37 +41,21 @@ public static partial class Convert
 
         public static List<Panel> FEMeshToPanel(this FEMesh feMesh)
         {
-            if (feMesh == null)
+            if (feMesh.IsNull("FEMeshToPanel"))
```
Comment (IsakNaslundBh) [inline Structure_Engine/Convert/FEMeshToPanel.cs:44]: as above, can leave the method name out here if we add the attribute.

File: Structure_Engine/Convert/PanelToFEMesh.cs [hunk 18]
```diff
@@ -44,7 +44,7 @@ public static partial class Convert
 
         public static FEMesh PanelToFEMesh(this Panel panel)
         {
-            if (BH.Engine.Structure.Compute.NullCheck(panel) == false)
+            if (panel.IsNull("PanelToFEMesh"))
```
Comment (IsakNaslundBh) [inline Structure_Engine/Convert/PanelToFEMesh.cs:47]: as above

File: Structure_Engine/Create/Loads/BarVaryingDistributedLoad/BarVaryingDistributedLoadDistanceBothEnds.cs [hunk 19]
```diff
@@ -65,6 +65,15 @@ public static partial class Create
         [Output("barVarLoad", "The created BarVaryingDistributedLoads with bars grouped by length.")]
         public static List<BarVaryingDistributedLoad> BarVaryingDistributedLoadDistanceBothEnds(Loadcase loadcase, BHoMGroup<Bar> group, bool relativePositions, double startToStartDistance = 0, Vector forceAtStart = null, Vector momentAtStart = null, double endToEndDistance = 0, Vector forceAtEnd = null, Vector momentAtEnd = null, LoadAxis axis = LoadAxis.Global, bool projected = false, string name = "", double groupingTolerance = Tolerance.Distance)
         {
+            if (group == null)
+            {
+                Reflection.Compute.RecordError("The group of Bars provided is null");
+                return null;
+            }
+
+            if (group.Elements.Any(x => x.IsNull("BarVaryingDistributedLoadDistanceBothEnds")) || loadcase.IsNull("BarVaryingDistributedLoadDistanceBothEnds"))
```
Comment (IsakNaslundBh) [inline Structure_Engine/Create/Loads/BarVaryingDistributedLoad/BarVaryingDistributedLoadDistanceBothEnds.cs:74]: as above

**Review by IsakNaslundBh — CHANGES_REQUESTED** [review]
Started reviewing again, but will hold off to the comments already given has been ironed out. THink a lot of them will be "add the attribute and remove the explicit method name" to make it cleaner.

File: Geometry_Engine/Query/IsNull.cs (hunk 15 above)
Comment (peterjamesnugent) [reply Geometry_Engine/Query/IsNull.cs:47]: Add to the Geometry_Engine null check handling issue here: https://github.com/BHoM/BHoM_Engine/issues/2487

File: Structure_Engine/Query/ElasticValues.cs [hunk 20]
```diff
@@ -33,12 +33,12 @@ public static partial class Query
...
 
-        [Description("Gets the spring values from a constraint as a double array. Values returned in the following order: TransX, TranxY, TransZ, RotX, RotY, RotZ.")]
-        [Input("constraint", "The constraint to spring values from.")]
+        [Description("Gets the spring values from a Constraint6DOF as a double array. Values returned in the following order: TransX, TranxY, TransZ, RotX, RotY, RotZ.")]
+        [Input("constraint", "The Constraint6DOF to spring values from.")]
         [Output("springValues", "The elastic values, or spring values, from a constraint as a double array in the following order: TransX, TransY, TransZ, RotX, RotY, RotZ.")]
         public static double[] ElasticValues(this Constraint6DOF constraint)
         {
-            return new double[] 
+            return constraint.IsNull() ? null : new double[]
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/ElasticValues.cs:41]: scope to return a `new double[6]` here instead of null. Kind of similar discussion to the one for setting orientations and area for that matter. Does a null constraint means it has invalid elastic values (null) or does it mean it has zero stiffness (`new double[6]`).

Not 100% sure myself again, but returning null here I see as equivalent to returning double.NaN for area, while returning `new double[6]` I would see as equivalent to returning 0 area.

Might not be 100% equivalent, but pretty close.

Glad to get others opinions on this. @al-fisher @rolyhudson @peterjamesnugent @JosefTaylor @FraserGreenroyd

File: Structure_Engine/Query/Fixities.cs [hunk 21]
```diff
@@ -38,7 +38,7 @@ public static partial class Query
         [Output("springValues", "The fixity values from a constraint as a bool array, where true indicates a fixity, in the following order: TransX, TransY, TransZ, RotX, RotY, RotZ.")]
         public static bool[] Fixities(this Constraint6DOF constraint)
         {
-            return new bool[] 
+            return constraint.IsNull() ? null : new bool[]
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/Fixities.cs:41]: As for the elastic values, but even trickier for this one due to null values for this class (i.e. defaults) would be different for BarRestraint and Nodal supports (bar restraint defaults being all fixed and node support defaults being all free).

For that reason I think it is reasonable to keep this one returning null, why it might be a good reason to keep the elastic values returning null as well, for symmetry.

Again, good to get this cleared and aligned, so glad for other peoples input. @peterjamesnugent @JosefTaylor @al-fisher @rolyhudson @FraserGreenroyd

File: Structure_Engine/Query/IsNull.cs [hunk 22]
```diff
@@ -0,0 +1,460 @@
...
+        [PreviousVersion("4.2", "BH.Engine.Structure.Compute.NullCheck(BH.oM.Structure.Elements.FEMesh, System.String, System.Boolean, System.Boolean, System.Collections.Generic.List<System.Int32>)")]
+        [Description("Checks if an FEMesh or its defining properties are null and outputs relevant error message.")]
+        [Input("mesh", "The FEMesh to test for null.")]
+        [Input("methodName", "Optional name of the method to reference in the error message.")]
+        [Input("checkFaces", "Optional bool to tell the method whether to check FEMeshFaces or not.")]
+        [Input("checkNodes", "Optional bool to tell the method whether to check mesh Nodes or not.")]
+        [Input("nodeListIndices", "Optional list of nodes to limit check to.")]
+        [Input("msg", "Optional message to be returned in addition to the generated error message.")]
+        [Output("isNull", "True if the FEMesh or its defining properties are null.")]
+        public static bool IsNull(this FEMesh mesh, [CallerMemberName] string methodName = "Method", bool checkFaces = true, bool checkNodes = true, List<int> nodeListIndices = null, string msg = "")
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/IsNull.cs:102]: As mentioned in above comment. Scope to put the `methodName` last in the argument chain, even after the additional `msg`, to all other parameters can be changed, while still always keeping the benefit of the `[CallerMemberName]` attribute.

Would mean some additional refactoring, but might be worth it..

If change is made, need to trickle down to all the methods in the class, and would if so also change the Geometry and Spatial methods.

File: Structure_Engine/Query/LocalOrientation.cs [hunk 23]
```diff
@@ -57,7 +57,7 @@ public static Basis LocalOrientation(this Panel panel)
         [Output("orienations", "The local orientations of the mesh faces as a list of vector Bases.")]
         public static List<Basis> LocalOrientations(this FEMesh mesh)
         {
-            return mesh.NullCheck("LocalOrientations", false, false) ? mesh.Faces.Select(x => x.LocalOrientation(mesh)).ToList() : null;
+            return mesh.IsNull("", false, false) ? null : mesh.Faces.Select(x => x.LocalOrientation(mesh)).ToList();
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/LocalOrientation.cs:60]: As above, need to pass on method name, unless method name is moved to the last argument of the method.

File: Structure_Engine/Query/MassPerArea.cs [hunk 24]
```diff
@@ -39,7 +39,7 @@ public static partial class Query
         [Output("massPerArea", "The mass per area for the property.", typeof(MassPerUnitArea))]
         public static double MassPerArea(this ConstantThickness constantThickness)
         {
-            return constantThickness.Thickness * constantThickness.Material.Density;
+            return constantThickness.IsNull() ? 0 : constantThickness.Thickness * constantThickness.Material.Density;
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/MassPerArea.cs:42]: Same as discussion regarding area and thickness values

File: Structure_Engine/Query/MassPerMetre.cs [hunk 25]
```diff
@@ -39,7 +39,7 @@ public static partial class Query
         [Output("massPerLength", "The mass per length for the section.", typeof(MassPerUnitLength))]
         public static double MassPerMetre(this ISectionProperty section)
         {
-            return section.Area * section.Material.Density;
+            return section.IsNull() ? 0 : section.Area * section.Material.Density;
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/MassPerMetre.cs:42]: Same as discussion regarding area and thickness values

File: Structure_Engine/Query/Normal.cs [hunk 26]
```diff
@@ -55,7 +55,7 @@ public static Vector Normal(this Bar bar)
         [Output("normal", "List of vectors representing the local z-axes of mesh faces. List order corresponds to the order of the faces.")]
         public static List<Vector> Normals(this FEMesh mesh)
         {
-            return mesh.NullCheck("Normals", false, false) ? mesh.Faces.Select(x => x.Normal(mesh)).ToList() : null;
+            return mesh.IsNull("", false, false) ? null : mesh.Faces.Select(x => x.Normal(mesh)).ToList();
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/Normal.cs:58]: Method name again, depending on outcome of refactoring

File: Structure_Engine/Query/Normal.cs [hunk 27]
```diff
@@ -66,7 +66,7 @@ public static List<Vector> Normals(this FEMesh mesh)
         [Output("normal", "Vector representing the local z-axis of a mesh face.")]
         public static Vector Normal(this FEMeshFace face, FEMesh mesh)
         {
-            if (!face.NullCheck(mesh, "Normal"))
+            if (face.IsNull(mesh, "Normal"))
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/Normal.cs:69]: here I do not think providing method name is required, as it is the last argument.

File: Structure_Engine/Query/ReinforcementLayout.cs [hunk 28]
```diff
@@ -203,8 +221,11 @@ public static List<ICurve> ReinforcementLayout(Bar bar)
         [Input("length", "Length of the host Bar used to generate the lines", typeof(Length))]
         [Input("transformation", "Transformation needed to move the lines from the position of the host element.")]
         [Output("points", "The centrelines of the LongitudinalReinforcement.")]
-        public static List<Line> ReinforcementLayout(this LongitudinalReinforcement reinforcement, double cover, List<ICurve> outerProfileEdges, List<ICurve> innerProfileEdges, double length, TransformMatrix transformation)
+        public static List<Line> ReinforcementLayout(this LongitudinalReinforcement reinforcement, double cover, List<ICurve> outerProfileEdges, List<ICurve> innerProfileEdges, double length, TransformMatrix transformation = null)
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/ReinforcementLayout.cs:224]: Not sure I agree with making this argument optional, especially as it is not handled. Would revert this change, requiring a transformation matrix to be provided.

File: Structure_Engine/Query/ReinforcementLayout.cs [hunk 29]
```diff
@@ -230,8 +251,11 @@ public static List<Line> ReinforcementLayout(this LongitudinalReinforcement rein
         [Input("length", "Length of the host Bar used to generate the lines.", typeof(Length))]
         [Input("transformation", "Transformation needed to move the lines from the position of the host element.")]
         [Output("points", "The centrelines of the LongitudinalReinforcement.")]
-        public static List<ICurve> ReinforcementLayout(this TransverseReinforcement reinforcement, double cover, List<ICurve> outerProfileEdges, List<ICurve> innerProfileEdges, double length, TransformMatrix transformation)
+        public static List<ICurve> ReinforcementLayout(this TransverseReinforcement reinforcement, double cover, List<ICurve> outerProfileEdges, List<ICurve> innerProfileEdges, double length, TransformMatrix transformation = null)
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/ReinforcementLayout.cs:254]: As above

File: Structure_Engine/Query/ReinforcementLayout.cs [hunk 30]
```diff
@@ -273,8 +297,11 @@ public static List<ICurve> ReinforcementLayout(this TransverseReinforcement rein
         [Input("length", "Length of the host Bar used to generate the lines.", typeof(Length))]
         [Input("transformation", "Transformation needed to move the lines from the position of the host element.")]
         [Output("points", "The centrelines of the LongitudinalReinforcement.")]
-        public static List<ICurve> IReinforcementLayout(this IBarReinforcement reinforcement, double cover, List<ICurve> outerProfileEdges, List<ICurve> innerProfileEdges, double length, TransformMatrix transformation)
+        public static List<ICurve> IReinforcementLayout(this IBarReinforcement reinforcement, double cover, List<ICurve> outerProfileEdges, List<ICurve> innerProfileEdges, double length, TransformMatrix transformation = null)
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/ReinforcementLayout.cs:300]: as above

File: Structure_Engine/Query/ReinforcingBarCount.cs [hunk 31]
```diff
@@ -45,12 +45,12 @@ public static partial class Query
...
 
-        [Description("Return the number of rebars in one particular Reinforcement object.")]
-        [Input("reinforcement", "The reinforcement object to extract the count from.")]
+        [Description("Return the number of reinforcing bars in one a LongtudinalReinforcement object.")]
+        [Input("reinforcement", "The LongitudinalReinforcement object to extract the count from.")]
         [Output("count", "Number of bars in the provided LongitudinalReinforcement.")]
         public static int ReinforcingBarCount(this LongitudinalReinforcement reinforcement)
         {
-            return LayoutCount(reinforcement.RebarLayout as dynamic);
+            return reinforcement.IsNull() ? null : LayoutCount(reinforcement.RebarLayout as dynamic);
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/ReinforcingBarCount.cs:53]: Not sure why this is not flagged by the compiler tbh, but need to change to this I think:

```suggestion
            return reinforcement.IsNull() ? 0 : LayoutCount(reinforcement.RebarLayout as dynamic);
```

File: Structure_Engine/Query/ShearModulus.cs [hunk 32]
```diff
@@ -43,12 +43,12 @@ public static partial class Query
         [Output("G", "Shear modulus of the material fragment.", typeof(ShearModulus))]
         public static double ShearModulus(this IIsotropic materialFragment)
         {
-            return materialFragment.YoungsModulus / (2 * (1 + materialFragment.PoissonsRatio));
+            return materialFragment.IsNull() ? 0 : materialFragment.YoungsModulus / (2 * (1 + materialFragment.PoissonsRatio));
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/ShearModulus.cs:46]: Again, candidate for `double.NaN`

File: Structure_Engine/Query/SolidVolume.cs [hunk 33]
```diff
@@ -40,11 +40,14 @@ public static partial class Query
...
 
-        [Description("Returns a Bar's solid volume based on its SectionProperty area and the CentreLine length")]
-        [Input("bar", "The Bar to get the volume from")]
+        [Description("Returns a Bar's solid volume based on its SectionProperty area and the CentreLine length.")]
+        [Input("bar", "The Bar to get the volume from.")]
         [Output("volume", "The Bar solid material volume.", typeof(Volume))]
         public static double SolidVolume(this Bar bar)
         {
+            if (bar.IsNull())
+                return 0;
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/SolidVolume.cs:49]: Again, depending on the discussion on Area

File: Structure_Engine/Query/TorsionalConstant.cs [hunk 34]
```diff
@@ -75,7 +76,7 @@ public static partial class Query
         [Output("J", "Torsional constant of the profile. Note that this is not the polar moment of inertia.", typeof(TorsionConstant))]
         public static double TorsionalConstant(this CircleProfile profile)
         {
-            return Math.PI * Math.Pow(profile.Diameter, 4) / 32;
+            return profile.IsNull() ? 0 : Math.PI * Math.Pow(profile.Diameter, 4) / 32;
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/TorsionalConstant.cs:79]: And, again, `double.NaN` candidate, same as for area

File: Structure_Engine/Query/Visualize.cs [hunk 35]
```diff
@@ -54,6 +52,9 @@ public static partial class Query
         [Output("lines", "A list of lines representing the load.")]
         public static List<ICurve> Visualize(this AreaUniformTemperatureLoad areaTempLoad, double scaleFactor = 1.0, bool displayForces = true, bool displayMoments = true, bool asResultants = true, bool edgeDisplay = true, bool gridDisplay = false)
         {
+            if (areaTempLoad.IsNull())
+                return null;
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/Visualize.cs:56]: Some scope to just return an empty list here instead of nulls. Same for all methods in this file

File: Structure_Engine/Query/WarpingConstant.cs [hunk 36]
```diff
@@ -103,6 +103,9 @@ public static double WarpingConstant(this RectangleProfile profile)
         [Output("Iw", "The warping constant of the profile.", typeof(WarpingConstant))]
         public static double WarpingConstant(this ISectionProfile profile)
         {
+            if (profile.IsNull())
+                return 0;
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/WarpingConstant.cs:107]: Again, depending on outcome of discussion regarding area

**Review by IsakNaslundBh — DISMISSED** [review]
A bit of a bombardment of comments here, but quite few files changed.

Generally I really like this and the direction with the `IsNull` methods etc. 👍 

Some comments on things I think need changing bellow, and some comments for discussion to just reach some form of consensus going forward.

File: Structure_Engine/Modify/SetLocalOrientation.cs [hunk 37]
```diff
@@ -44,12 +44,15 @@ public static partial class Modify
         [Output("panel", "The Panel with updated orientation.")]
         public static Panel SetLocalOrientation(this Panel panel, Vector localX)
         {
+            if (panel.IsNull() || localX.IsNull())
+                return null;
```
[the remark this answers is not in the document]
Comment (peterjamesnugent) [reply Structure_Engine/Modify/SetLocalOrientation.cs:48]: I think returning `null` makes sense based on your fourth bullet point - it essentially breaks your script at a point so you can identify where the issue is instead of lulling you in to a false sense of security. 

On the third point how useful would a `Panel` that is `null` be downstream? Anything you try to do it will fail.

[the remark this answers is not in the document]
Comment (IsakNaslundBh) [reply Structure_Engine/Modify/SetLocalOrientation.cs:48]: > On the third point how useful would a Panel that is null be downstream? Anything you try to do it will fail.

Mainly if the panel is not null, but the vector is, then you would still have the unchanged panel rather than a null.

File: Structure_Engine/Query/Area.cs [hunk 38]
```diff
@@ -45,7 +45,7 @@ public static partial class Query
         [Output("area", "The area of the FEMesh.", typeof(Area))]
         public static double Area(this FEMesh mesh)
         {
-            return Engine.Analytical.Query.Geometry(mesh).Area();
+            return mesh.IsNull() ? 0 : Analytical.Query.Geometry(mesh).Area();
```
[the remark this answers is not in the document]
Comment (peterjamesnugent) [reply Structure_Engine/Query/Area.cs:48]: I am happy with either, although if it does return 0 you will still get an error message telling you what is null - so it's not like the user will be completely unaware.

[the remark this answers is not in the document]
Comment (IsakNaslundBh) [reply Structure_Engine/Query/Area.cs:48]: > I am happy with either, although if it does return 0 you will still get an error message telling you what is null - so it's not like the user will be completely unaware.

Very good point. That makes it feel more comfortable returning 0 rather than `NaN`.

Still happy for more opinions though!

File: Structure_Engine/Compute/Integrate.cs (hunk 9 above)
Comment (IsakLarbornBH) [reply Structure_Engine/Compute/Integrate.cs]: @IsakNaslundBh I had to try to figure out something for this when I added null checks to DisplayMeshResults. The only solution I found which removed the UI errors relating to mismatched output types was to return a MultiOutput containing empty objects of the expected types - returning a MultiOutput containing nulls resulted in the same error as just returning null when I tried that.

I'm aware that it's probably not a good idea to do that for most methods though, since you wouldn't want the empty objects to be mistaken for real ones, so maybe a UI fix is needed to handle nulls in MultiOutputs. (Assuming there's no other way to fix it, maybe casting the nulls into the expected types?)

Comment (peterjamesnugent) [reply Structure_Engine/Compute/Integrate.cs]:
```
            if (profile.IsNull())
                return new Output<IProfile, Dictionary<string, double>> { Item1 = null, Item2 = null };
```

I've gone for returning nulls - the file above is now outdated.

File: Structure_Engine/Query/Area.cs (hunk 38 above)
[the remark this answers is not in the document]
Comment (al-fisher) [reply Structure_Engine/Query/Area.cs:48]: Agreed with returning 0.

Summarising and I think reinforcing points made by @peterjamesnugent and @IsakNaslundBh above - returning `double.NaN` is not additionally helpful here (in fact it will simply make more problems downstream potententally forcing further filtering and data clean up of `NaN`s in operations on lists of doubles). 

It is the incoming object that  is `null` and that is already  being flagged and error thrown in `.IsNull()` method. 

A case as to whether `0` or `NaN` is the "right" answer can easily be made either way I think - so keeping primitives "simple" and avoiding `NaN`s would be my preference.

And so, wrt query methods returning primitives, returning 0  is best I think.

File: Structure_Engine/Modify/SetLocalOrientation.cs (hunk 37 above)
[the remark this answers is not in the document]
Comment (al-fisher) [reply Structure_Engine/Modify/SetLocalOrientation.cs:48]: Agreed - think return `null`.

Here I think as we are trying to Modify a valid object with a `Null` input - the actual method should indeed fail. And returning a `null` object makes sense.

I think this is slightly different to the query case [here](https://github.com/BHoM/BHoM_Engine/pull/2504#discussion_r646505189) where we do not what to make the return type _too intelligent!_ It is just a double. So should avoid `NaN`s.

In this case the modify action is indeed invalidating the original panel - and so should return a null object (and in the case of workflows - disrupt downstream)

To me this makes sense 😄 - will be good to summarise the above/agreed conventions in the wiki.
@IsakNaslundBh @peterjamesnugent @FraserGreenroyd

File: Structure_Engine/Compute/Integrate.cs (hunk 9 above)
Comment (IsakLarbornBH) [reply Structure_Engine/Compute/Integrate.cs]: Yeah that seems to work - it doesn't when I try to do the same thing for DisplayMeshResults. I'd guess it's because one of the return types is a list (a nested one, even.) Alright, well I guess you can disregard most of what I wrote above.

File: Structure_Engine/Query/Edges.cs [hunk 39]
```diff
@@ -39,10 +39,12 @@ public static partial class Query
...
 
         [Description("Extracts the edge curves from the geometric surface of the element.")]
-        [Input("surface","The structural surface to extract edges from.")]
+        [Input("surface", "The structural surface to extract edges from.")]
         [Output("edges", "The list of curves representing the edges of the underlying surface.")]
         public static List<ICurve> Edges(this Surface surface)
         {
+            if (surface.IsNull())
+                return null;
             if (surface.Extents != null)
```
[the remark this answers is not in the document]
Comment (peterjamesnugent) [reply Structure_Engine/Query/Edges.cs:48]: Added the null checking of extents to the `IsNull` method.

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

File: Structure_Engine/Query/IsNull.cs [hunk 40]
```diff
@@ -0,0 +1,469 @@
...
+        [Output("pass", "True if the AreaElement is null.")]
+        public static bool IIsNull(this IAreaElement element, string msg = "", [CallerMemberName] string methodName = "Method")
+        {
+            if (element == null)
+            {
+                ErrorMessage(methodName, "AreaElement", msg);
+                return true;
+            }
+
+            return IsNull(element as dynamic, msg, methodName);
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/IsNull.cs:441]: THis will never reach the method for the FEMesh after my request to move the method name last. WIll need to do type checking and call the appropriate method here unfortunately.

File: Structure_Engine/Query/LocalOrientation.cs [hunk 41]
```diff
@@ -57,7 +57,7 @@ public static Basis LocalOrientation(this Panel panel)
         [Output("orienations", "The local orientations of the mesh faces as a list of vector Bases.")]
         public static List<Basis> LocalOrientations(this FEMesh mesh)
         {
-            return mesh.NullCheck("LocalOrientations", false, false) ? mesh.Faces.Select(x => x.LocalOrientation(mesh)).ToList() : null;
+            return mesh.IsNull(false, false) ? null : mesh.Faces.Select(x => x.LocalOrientation(mesh)).ToList();
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/LocalOrientation.cs:60]: Not sure why this is using false for if nodes and faces should be checked? they are required, no?

File: Structure_Engine/Query/Normal.cs [hunk 42]
```diff
@@ -55,7 +55,7 @@ public static Vector Normal(this Bar bar)
         [Output("normal", "List of vectors representing the local z-axes of mesh faces. List order corresponds to the order of the faces.")]
         public static List<Vector> Normals(this FEMesh mesh)
         {
-            return mesh.NullCheck("Normals", false, false) ? mesh.Faces.Select(x => x.Normal(mesh)).ToList() : null;
+            return mesh.IsNull(false, false) ? null : mesh.Faces.Select(x => x.Normal(mesh)).ToList();
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/Normal.cs:58]: as above? Or is it left out cause checked in method for face?

**Review by IsakNaslundBh — CHANGES_REQUESTED** [review]
Few more comments

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
Have run through a nullcheck on Structure_Engine only, and no Errors are shown any longer, but the following methods are still giving warnings, which means they are crashing but returning another error than the `NullReferenceException`. It can for exmple be the ambiguous call exception (trying to cast a null as dynamic) or `ArgumentNullException`, which for whatever reason is not the same as the `NullReferenceException`. There are also some legacy code in places where explicit Exceptions are thrown rather than an Error message logged and a null returned. `BarUniformlyDistributedLoad` is an example of this, as is a few other Load creation methods.

I have placed a script in the PR Test script folder, and I also moved a copy of the Versioning test file there.

List of methods still crashing, with exceptions other than `NullReferenceException`:

- BH.Engine.Structure.Compute.PlasticModulus(Polyline pLine, IEnumerable<ICurve> curves, Double trueArea)
- BH.oM.Structure.Elements.Opening.Opening(ICurve outline)
- BH.oM.Structure.Elements.Opening.Opening(IEnumerable<ICurve> edges)
- BH.oM.Structure.Loads.AreaDifferentialTemperatureLoad.AreaDifferentialTemperatureLoad(Loadcase loadcase, List<Double> positions, List<Double> temperatures, IEnumerable<IAreaElement> objects, String name)
- BH.oM.Structure.Loads.AreaDifferentialTemperatureLoad.AreaDifferentialTemperatureLoad(Loadcase loadcase, Double topTemperature, Double bottomTemperature, IEnumerable<IAreaElement> objects, String name)
- BH.oM.Structure.Loads.AreaUniformTemperatureLoad.AreaUniformTemperatureLoad(Loadcase loadcase, Double temperatureChange, IEnumerable<IAreaElement> objects, LoadAxis axis, Boolean projected, String name)
- BH.oM.Structure.Loads.AreaUniformlyDistributedLoad.AreaUniformlyDistributedLoad(Loadcase loadcase, Vector pressure, IEnumerable<IAreaElement> objects, LoadAxis axis, Boolean projected, String name)
- BH.oM.Structure.Loads.BarPointLoad.BarPointLoad(Loadcase loadcase, BHoMGroup<Bar> group, Double distFromA, Vector force, Vector moment, LoadAxis axis, and 1 more inputs)
- BH.oM.Structure.Loads.BarPointLoad.BarPointLoad(Loadcase loadcase, Double distFromA, IEnumerable<Bar> objects, Vector force, Vector moment, LoadAxis axis, and 1 more inputs)
- BH.oM.Structure.Loads.BarPrestressLoad.BarPrestressLoad(Loadcase loadcase, Double prestress, IEnumerable<Bar> objects, String name)
- BH.oM.Structure.Loads.BarDifferentialTemperatureLoad.BarDifferentialTemperatureLoad(Loadcase loadcase, Double topTemperature, Double bottomTemperature, and 3 more inputs)
- BH.oM.Structure.Loads.BarUniformTemperatureLoad.BarUniformTemperatureLoad(Loadcase loadcase, Double temperatureChange, IEnumerable<Bar> objects, LoadAxis axis, Boolean projected, String name)
- BH.oM.Structure.Loads.BarUniformlyDistributedLoad.BarUniformlyDistributedLoad(Loadcase loadcase, BHoMGroup<Bar> group, Vector force, Vector moment, LoadAxis axis, Boolean projected, and 1 more inputs)
- BH.oM.Structure.Loads.BarUniformlyDistributedLoad.BarUniformlyDistributedLoad(Loadcase loadcase, IEnumerable<Bar> objects, Vector force, Vector moment, LoadAxis axis, Boolean projected, and 1 more inputs)
- BH.oM.Structure.Loads.BarVaryingDistributedLoad.BarVaryingDistributedLoadDistanceBothEnds(Loadcase loadcase, IEnumerable<Bar> objects, Boolean relativePositions, Double startToStartDistance, Vector forceAtStart, Vector momentAtStart, and 7 more inputs)
- BH.oM.Structure.Loads.BarVaryingDistributedLoad.BarVaryingDistributedLoad(Loadcase loadcase, IEnumerable<Bar> objects, Double startPosition, Vector forceAtStart, Vector momentAtStart, Double endPosition, and 6 more inputs)
- BH.oM.Structure.Loads.GravityLoad.GravityLoad(Loadcase loadcase, Vector gravityDirection, IEnumerable<IBHoMObject> objects, String name)
- BH.oM.Structure.Loads.PointVelocity.PointVelocity(Loadcase loadcase, BHoMGroup<Node> group, Vector translationalVelocity, Vector rotationalVelocity, LoadAxis axis, String name)
- BH.oM.Structure.Loads.PointVelocity.PointVelocity(Loadcase loadcase, IEnumerable<Node> objects, Vector translationalVelocity, Vector rotationalVelocity, LoadAxis axis, String name)
- BH.oM.Structure.Loads.PointLoad.PointLoad(Loadcase loadcase, BHoMGroup<Node> group, Vector force, Vector moment, LoadAxis axis, String name)
- BH.oM.Structure.Loads.PointLoad.PointLoad(Loadcase loadcase, IEnumerable<Node> objects, Vector force, Vector moment, LoadAxis axis, String name)
- BH.oM.Structure.Loads.PointDisplacement.PointDisplacement(Loadcase loadcase, BHoMGroup<Node> group, Vector translation, Vector rotation, LoadAxis axis, String name)
- BH.oM.Structure.Loads.PointDisplacement.PointDisplacement(Loadcase loadcase, IEnumerable<Node> objects, Vector translation, Vector rotation, LoadAxis axis, String name)
- BH.oM.Structure.Loads.PointAcceleration.PointAcceleration(Loadcase loadcase, BHoMGroup<Node> group, Vector translationAcc, Vector rotationAcc, LoadAxis axis, String name)
- BH.oM.Structure.Loads.PointAcceleration.PointAcceleration(Loadcase loadcase, IEnumerable<Node> objects, Vector translationAcc, Vector rotationAcc, LoadAxis axis, String name)
- BH.oM.Structure.Constraints.Constraint6DOF.Constraint6DOF(String name, List<Boolean> fixity, List<Double> values)
- BH.oM.Structure.Loads.ILoad.Load(LoadType type, Loadcase loadCase, List<Double> magnitude, String groupName, LoadAxis axis, Boolean isProjected, and 1 more inputs)
- BH.oM.Structure.Elements.Panel.Panel(ICurve outline, List<ICurve> openings, ISurfaceProperty property, Vector localX, String name)
- BH.oM.Structure.Constraints.LinkConstraint.LinkConstraint(String name, List<Boolean> fixity)
- BH.Engine.Structure.Query.IsLongitudinal(Reinforcement reinforcement)
- BH.Engine.Structure.Query.TorsionalConstant(IProfile profile)
- BH.Engine.Structure.Query.WarpingConstant(IProfile profile)
- BH.Engine.Structure.Query.AverageElement(List<Node> nodes, List<Double> weights)
- BH.Engine.Structure.Query.Geometry(ISectionProperty section)
- BH.Engine.Structure.Query.Mass(Bar bar)
- BH.Engine.Structure.Query.Mass(Panel panel)
- BH.Engine.Structure.Query.MassPerArea(Ribbed ribbedProperty)
- BH.Engine.Structure.Query.MassPerArea(Waffle ribbedProperty)
- BH.Engine.Structure.Query.Normal(IAreaElement areaElement)
- BH.Engine.Structure.Query.SelectCase(List<T> results, Object loadcase)
- BH.Engine.Structure.Query.HasAssignedObjectIds(IElementLoad<T> load, Type adapterIdType)
- BH.Engine.Structure.Query.MaterialType(IMaterialFragment materialFragment)

**Review by IsakNaslundBh — CHANGES_REQUESTED** [review]
Some null returns that require doubles

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

File: Structure_Engine/Create/Loads/BarPointLoad.cs [hunk 43]
```diff
@@ -50,7 +51,9 @@ public static partial class Create
         public static BarPointLoad BarPointLoad(Loadcase loadcase, BHoMGroup<Bar> group, double distFromA, Vector force = null, Vector moment = null, LoadAxis axis = LoadAxis.Global, string name = "")
         {
             if (force == null && moment == null)
-                throw new ArgumentException("Bar point load requires either the force and/or the moment vector to be defined");
+            {
+                Reflection.Compute.RecordError("BarPointLoad requires at least the force or the moment vector to be defined.");
```
Comment (IsakNaslundBh) [inline Structure_Engine/Create/Loads/BarPointLoad.cs:55]:
```suggestion
                Reflection.Compute.RecordError("BarPointLoad requires at least the force or the moment vector to be defined.");
                return null;
```

File: Structure_Engine/Create/Loads/BarUniformlyDistributedLoad.cs [hunk 44]
```diff
@@ -50,7 +51,9 @@ public static partial class Create
         public static BarUniformlyDistributedLoad BarUniformlyDistributedLoad(Loadcase loadcase, BHoMGroup<Bar> group, Vector force = null, Vector moment = null, LoadAxis axis = LoadAxis.Global, bool projected = false, string name = "")
         {
             if (force == null && moment == null)
-                throw new ArgumentException("Bar uniform load requires either the force and/or the moment vector to be defined");
+            {
+                Reflection.Compute.RecordError("BarUniformLoad requires at least the force or the moment vector to be defined");
```
Comment (IsakNaslundBh) [inline Structure_Engine/Create/Loads/BarUniformlyDistributedLoad.cs:55]:
```suggestion
                Reflection.Compute.RecordError("BarUniformLoad requires at least the force or the moment vector to be defined");
                return null;
```

File: Structure_Engine/Create/Loads/PointAcceleration.cs [hunk 45]
```diff
@@ -49,7 +51,7 @@ public static partial class Create
         public static PointAcceleration PointAcceleration(Loadcase loadcase, BHoMGroup<Node> group, Vector translationAcc = null, Vector rotationAcc = null, LoadAxis axis = LoadAxis.Global, string name = "")
         {
             if (translationAcc == null && rotationAcc == null)
-                throw new ArgumentException("Point acceleration requires either the translation or the rotation vector to be defined");
+                Reflection.Compute.RecordError("PointAcceleration requires at least the translation or rotation vector to be defined");
```
Comment (IsakNaslundBh) [inline Structure_Engine/Create/Loads/PointAcceleration.cs:54]:
```suggestion
            {
                Reflection.Compute.RecordError("PointAcceleration requires at least the translation or rotation vector to be defined");
                return null;
            }
```

File: Structure_Engine/Create/Loads/PointVelocity.cs [hunk 46]
```diff
@@ -49,7 +51,9 @@ public static partial class Create
         public static PointVelocity PointVelocity(Loadcase loadcase, BHoMGroup<Node> group, Vector translationalVelocity = null, Vector rotationalVelocity = null, LoadAxis axis = LoadAxis.Global, string name = "")
         {
             if (translationalVelocity == null && rotationalVelocity == null)
-                throw new ArgumentException("Point velocity requires either the translation or the rotation vector to be defined");
+            {
+                Reflection.Compute.RecordError("PointVelocity requires at least the translation or the rotation vector to be defined");
```
Comment (IsakNaslundBh) [inline Structure_Engine/Create/Loads/PointVelocity.cs:55]:
```suggestion
                Reflection.Compute.RecordError("PointVelocity requires at least the translation or the rotation vector to be defined");
                return null;
```

File: Structure_Engine/Query/Geometry.cs [hunk 47]
```diff
@@ -84,9 +84,11 @@ public static IGeometry Geometry(this RigidLink link)
                 {
                     if (sn?.Position != null)
                         lines.Add(new Line() { Start = link.PrimaryNode.Position, End = sn.Position });
-                }   
+                }
             }
-            
+            else
+                return null;
+
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/Geometry.cs:91]: Not sure what benefit this addition has? Retuning empty geometry and protected from crashing as is anyway?

File: Structure_Engine/Query/SelectCase.cs [hunk 48]
```diff
@@ -40,11 +41,19 @@ public static partial class Query
...
         public static List<T> SelectCase<T>(this List<T> results, object loadcase) where T : IResult
         {
+            if (results.IsNullOrEmpty())
+                return null;
+            else if (loadcase == null)
+            {
+                Reflection.Compute.RecordError("Loadcase provided is null, therefore SelectCase cannot be evaluated.");
+                return null;
+            }
+
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/SelectCase.cs:56]: This is handled below. Providing no case filters returns everything, which was the intended behaviour of this method.
```suggestion
```

File: Structure_Engine/Query/SelectCase.cs [hunk 49]
```diff
@@ -56,7 +65,7 @@ public static partial class Query
                 else if (loadcase is int || loadcase is double)
                     loadCaseId = loadcase.ToString();
 
-                if (!string.IsNullOrWhiteSpace(loadCaseId))
+                if (string.IsNullOrWhiteSpace(loadCaseId))
```
Comment (IsakNaslundBh) [inline Structure_Engine/Query/SelectCase.cs:68]: Pretty sure this was right as it was
```suggestion
                if (!string.IsNullOrWhiteSpace(loadCaseId))
```

**Review by IsakNaslundBh — CHANGES_REQUESTED** [review]
Some more comments bellow

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by peterjamesnugent** [comment]
#### Dispensation requests
Code compliance - `Modify` methods in question cannot be `void`
Documentation compliance - `MultiOutputAttribute` has been fixed in Test_Toolkit - descriptions for other methods outside scope of PR
Null handling - Master branch has 170 null handling errors/warnings and this branch has 2. The check has been failing since updating from master: https://github.com/BHoM/BHoM_Engine/pull/2504#issuecomment-843886548

**Comment by IsakNaslundBh** [comment]
### Reason for dispensation
- Code-compliance - Modify methods should not be changed to void return in Structure_Engine yet
- Documentation-Compliance - Error is Test itself
- null-check Have manually run the test, and this PR is going from 170 errors and warnings to 2. The ones left are failing because the test method could not generate data for generics method.

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2803424982

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2803424800

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2803425492

**Review by IsakNaslundBh — APPROVED** [review]
All looks good to me now!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge
