### PR TITLE
Reflection_Engine: SetProperty - Ability to set nested property names (e.g. Bar.Node.Name)

### LINKED ISSUE #1475: Reflection_Engine: SetProperty not calling properties correctly
#### Description:

Using set property for a property that does exist, is reporting it doesn't/using customdata. Have not tested in other UI's so unsure if it's GH or UI. 

image

#### Steps to reproduce:

Call get/set property on any nested property of same name and try to set. 

#### Expected behaviour:

SetProperty should set the property

### PR DESCRIPTION
**Pull request by rwemay**
### Issues addressed by this PR

Closes #1475 

### Test files
[Test Files](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FReflection%5FEngine%2FReflectionEngine%2DIssue982%2DGetSetNestedProperties&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

### CODE REVIEW

File: Reflection_Engine/Modify/SetPropertyValue.cs [hunk 1]
```diff
@@ -125,8 +137,5 @@ public static bool SetPropertyValue(this List<IBHoMObject> objects, Type objectT
             }
 
         }
-
-
-        /***************************************************/
```
Comment (adecler) [inline Reflection_Engine/Modify/SetPropertyValue.cs]: why? 😢

**Comment by adecler** [comment]
It looks like adding the comment back made AppVeyor happy again 😄. Good to have a CI system as OCD as me 😋 .
More seriously, I am not entirely why Rob's commit was failing. @FraserGreenroyd ?
