### PR TITLE
Architecture_Engine: Fix null handling

### LINKED ISSUE #2462: Architecture_Engine - handle nulls
For the following methods:

 - [x] BH.Engine.Architecture.Compute.CeilingTiles(Ceiling ceiling, List<Line> ceilingTileLines, Double angleTolerance, Double distanceTolerance, Int32 decimalPlaces)
 - [x] BH.Engine.Architecture.Modify.CleanRoom(Room room, Double angleTolerance, Double minimumSegmentLength)
 - [x] BH.Engine.Architecture.Modify.SetGeometry(Room room, Point locationPoint, ICurve perimeterCurve)
 - [x] BH.Engine.Architecture.Modify.SetOutlineElements1D(Room room, List<IElement1D> outlineElements1D)
 - [x] BH.Engine.Architecture.Query.OutlineElements1D(Room room)
 - [x] BH.Engine.Architecture.Query.OutlineElements1D(Ceiling ceiling)
 - [x] BH.oM.Architecture.Theatron.TheatronPlan.CircularPlan(StadiaParameters parameters)
 - [x] BH.oM.Architecture.Theatron.TheatronPlan.EightArcPlan(StadiaParameters parameters)
 - [x] BH.oM.Architecture.Theatron.TheatronPlan.NoCornersPlan(StadiaParameters parameters)
 - [x] BH.oM.Architecture.Theatron.TheatronPlan.OrthogonalPlan(StadiaParameters parameters)
 - [x] BH.oM.Architecture.Theatron.ActivityArea.ActivityArea(Polyline activityArea, Point activityFocalPoint)
 - [x] BH.oM.Architecture.Theatron.ProfileOrigin.ProfileOrigin(Point origin, Vector direction)
 - [x] BH.oM.Architecture.Theatron.SeatingBlock.SeatingBlock(ProfileOrigin start, ProfileOrigin vom, ProfileOrigin end, SeatingBlockType t, Double seatWidth, Double aisleWidth)
 - [x] BH.oM.Architecture.Theatron.TheatronGeometry.TheatronGeometry(TheatronPlan planFull, TheatronFullProfile profile, StadiaParameters sParams, List<ProfileParameters> pParams)
 - [x] BH.oM.Architecture.Theatron.TheatronGeometry.TheatronGeometry(TheatronPlan planPart, TheatronFullProfile profile, List<ProfileParameters> pParams)
 - [x] BH.oM.Architecture.Theatron.TheatronFullProfile.TheatronFullProfile(List<ProfileParameters> parameters, TheatronPlan planGeometry)
 - [x] BH.oM.Architecture.Theatron.TheatronFullProfile.TheatronFullProfile(List<ProfileParameters> parameters, Point focalPoint, ProfileOrigin sectionOrigin)
 - [x] BH.oM.Architecture.Theatron.TheatronPlan.PlanGeometry(StadiaParameters parameters)
 - [x] BH.oM.Architecture.Theatron.TierProfile.TierProfile(ProfileParameters parameters, Point lastPointPrevTier)
 - [x] BH.oM.Architecture.Theatron.TierProfile.TransformProfile(TierProfile originalSection, Vector scale, Point source, Point target, Double angle)

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #2462

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2360229150

File: Architecture_Engine/Modify/TransformProfile.cs [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+
+        public static ProfileOrigin DefineTierOrigin(List<Point> flrPoints)
+        {
+            ProfileOrigin profOrigin = Create.ProfileOrigin(flrPoints[0], flrPoints[1] - flrPoints[0]);
+            return profOrigin;
+        }
+
+        /***************************************************/
+
+        public static void TransformTier(ref TierProfile profile, TransformMatrix xTrans)
```
Comment (pawelbaran) [inline Architecture_Engine/Modify/TransformProfile.cs:90]: I would keep this method private to avoid mess with `ref` method parameters in the UI - assuming that neither of us has a solid grip over what is going on here @FraserGreenroyd 😄

File: Architecture_Engine/Query/OutlineElements1D.cs [hunk 2]
```diff
@@ -47,6 +47,12 @@ public static partial class Query
         [Output("outlineElements", "A collection of outline 1D elements")]
         public static List<IElement1D> OutlineElements1D(this Room room)
         {
+            if(room == null)
+            {
+                BH.Engine.Reflection.Compute.RecordError("Cannot query the outline 1D elements of a null room.");
+                return null;
```
Comment (pawelbaran) [inline Architecture_Engine/Query/OutlineElements1D.cs:53]: Why null and not an empty list?
```suggestion
                return new List<IElement1D>();
```

File: Architecture_Engine/Query/OutlineElements1D.cs [hunk 3]
```diff
@@ -57,6 +63,12 @@ public static List<IElement1D> OutlineElements1D(this Room room)
         [Output("outlineElements", "A collection of outline 1D elements")]
         public static List<IElement1D> OutlineElements1D(this Ceiling ceiling)
         {
+            if(ceiling == null)
+            {
+                BH.Engine.Reflection.Compute.RecordError("Cannot query the outline 1D elements of a null ceiling.");
+                return null;
```
Comment (pawelbaran) [inline Architecture_Engine/Query/OutlineElements1D.cs:69]: Why null and not an empty list?
```suggestion
                return new List<IElement1D>();
```

File: Architecture_Engine/Modify/TransformProfile.cs [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+            var xTrans = Geometry.Create.TranslationMatrix(target - source);
+            TransformTier(ref transformedTier, xScale);
+            TransformTier(ref transformedTier, xRotate);
+            TransformTier(ref transformedTier, xTrans);
+            return transformedTier;
+        }
+
+        /***************************************************/
+
+        public static ProfileOrigin DefineTierOrigin(List<Point> flrPoints)
```
Comment (pawelbaran) [inline Architecture_Engine/Modify/TransformProfile.cs:82]: Same as in case of the method below (`TransformTier`) - this method is definitely not a `Modify` method, plus we dunno what it is doing. I would keep it private for safety reasons, letting the more competent consumer make it public if needed.

File: Architecture_Engine/Compute/CeilingTiles.cs [hunk 5]
```diff
@@ -49,6 +49,12 @@ public static partial class Compute
         [Output("ceilingTiles", "Closed Ceiling Tile regions contained within the Ceiling.")]
         public static List<CeilingTile> CeilingTiles(Ceiling ceiling, List<Line> ceilingTileLines, double angleTolerance = BH.oM.Geometry.Tolerance.Angle, double distanceTolerance = BH.oM.Geometry.Tolerance.Distance, int decimalPlaces = 6)
         {
+            if(ceiling == null)
+            {
+                BH.Engine.Reflection.Compute.RecordError("Cannot compute the ceiling tiles for a null ceiling.");
+                return null;
```
Comment (pawelbaran) [inline Architecture_Engine/Compute/CeilingTiles.cs:55]: Why null and not an empty list?
```suggestion
                return new List<CeilingTile>();
```

**Review by pawelbaran — CHANGES_REQUESTED** [review]
See the code comments

File: Architecture_Engine/Modify/TransformProfile.cs (hunk 1 above)
Comment (FraserGreenroyd) [reply Architecture_Engine/Modify/TransformProfile.cs:90]: My main issue with this one is that these methods are used both in modify methods and create methods. I guess the easiest way is actually to avoid trying to fix the compliance of a create in modify and let @rolyhudson sort it out given it's his ~~mess~~ code 😝 he'll know best how to resolve it I imagine. @rolyhudson I'm happy to help with versioning, but following discussion with @pawelbaran I am going to revert the attempt to resolve that bit of compliance for now.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

File: Architecture_Engine/Architecture_Engine.csproj [hunk 6]
```diff
@@ -123,6 +123,7 @@
   <ItemGroup>
     <Folder Include="Convert\" />
     <Folder Include="Create\SettingOut\" />
+    <Folder Include="Objects\" />
```
Comment (pawelbaran) [inline Architecture_Engine/Architecture_Engine.csproj:126]: why

File: Architecture_Engine/Create/Theatron/TierProfile.cs [hunk 7]
```diff
@@ -55,26 +67,49 @@ public static TierProfile TierProfile(ProfileParameters parameters, Point lastPo
...
-
-        /***************************************************/
         [Description("Scale, rotate and translate a TierProfile")]
         [Input("originalSection", "TierProfile to transform")]
         [Input("scale", "Scaling amount")]
         [Input("source", "Origin point for the transform")]
         [Input("target", "Target point for the transform")]
         [Input("angle", "Rotation angle")]
-        //this should be a modify method
+        [PreviousVersion("4.2", "BH.Engine.Architecture.Theatron.Create.TransformProfile(BH.oM.Architecture.Theatron.TierProfile, BH.oM.Geometry.Vector, BH.oM.Geometry.Point, BH.oM.Geometry.Point, System.Double)")]
```
Comment (pawelbaran) [inline Architecture_Engine/Create/Theatron/TierProfile.cs:76]: this is not needed any more, I would revert back to the comment about the method to be moved to `Modify`

**Review by pawelbaran — CHANGES_REQUESTED** [review]

File: Architecture_Engine/Architecture_Engine.csproj (hunk 6 above)
Comment (FraserGreenroyd) [reply Architecture_Engine/Architecture_Engine.csproj:126]: Because

**Review by pawelbaran — APPROVED** [review]
I have no objections outside of what I have mentioned in my previous comments in previous PRs of this type.

As mentioned in #2465, I am a bit concerned about the creep that these changes may possibly introduce, but it seems that the only way to check it is to merge and see how many weird behaviours bubble up.

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check dataset-compliance
